### ISSUE TITLE
[HttpClient] Request stream seems still being occupied even if the `HttpClientRequest` has been aborted

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/sdk#54392]
This tracker is for issues related to: `dart:io`.

The following issue can be easily reproduced on Windows.

```console
Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "windows_x64"
```

Reproducible code:
```dart
test('delete file when write socket exception', () async {
  final f = File('test/mock/flutter.png'); // Any files can do this.
  final client = HttpClient();
  final request = await client.openUrl(
    'put',
    Uri.parse('https://httpbun.com/put'),
  );
  try {
    final requestStream = f.openRead();
    final future = request.addStream(requestStream); // Set a breakpoint here.
    await future.catchError((e, s) {
      request.abort(e, s);
      print('Aborted');
      return future;
    });
  } catch (e, s) {
    print('$e\n$s');
    await request.flush();
    f.deleteSync();
    rethrow;
  }
});
```

When the debugger stops at the breakpoint, disconnect the network and continue. The exception will thrown:

```console
Testing started at 9:08 AM ...
The Dart VM service is listening on http://127.0.0.1:60523/KXJ8lfJajgs=/

The Dart DevTools debugger and profiler is available at: http://127.0.0.1:60523/KXJ8lfJajgs=/devtools?uri=ws://127.0.0.1:60523/KXJ8lfJajgs=/ws
Aborted
SocketException: Write failed (OS Error: An existing connection was forcibly closed by the remote host.
, errno = 10054), address = httpbun.com, port = 60900
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1246:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:2004:15)
#2      _ExternalBuffer.readToSocket (dart:io/secure_socket.dart:1329:26)
#3      _RawSecureSocket._writeSocket (dart:io/secure_socket.dart:1091:16)
#4      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1037:13)
<asynchronous suspension>
#5      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:928:9)
<asynchronous suspension>
#6      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1049:13)
<asynchronous suspension>
dart:io                     FileSystemEntity.deleteSync
test\upload_test.dart 73:9  main.<fn>

PathAccessException: Cannot delete file, path = 'test/mock/flutter.png' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)


Process finished with exit code 1
```

**Comment by AlexV525** [comment]
*(upstream https://github.com/cfug/dio/issues/1920)*

Our source:

https://github.com/cfug/dio/blob/4b1f1ec6ee04b006ffb7c8ac11ee7b30978acbe6/dio/lib/src/adapters/io_adapter.dart#L152-L169

**Comment by AlexV525** [comment]
https://github.com/dart-lang/sdk/assets/15884415/d5988683-bf07-45f7-a0ad-da77694a4df9

**Comment by brianquinlan** [comment]
Hmmm...the likely cause is that the stream is not being closed if an exception occurs.

**Comment by introvert** [comment]
The same issue appears to us, making it impossible to launch or even debug the app written in Flutter.

Surprised that there aren't more reports - perhaps Flutter has not really gotten on serious use yet?

**Comment by AlexV525** [comment]
> The same issue appears to us, making it impossible to launch or even debug the app written in Flutter.

You can try destroying the `HttpClient` instead of the request, or make copies of files into a temporary directory and ignore them if the deletion fails.

> Surprised that there aren't more reports - perhaps Flutter has not really gotten on serious use yet?

Arguing with frameworks is not interesting, we should focus on the problem.

**Comment by NightFeather0615** [comment]
Greetings! I've facing the same problem when solving issue in [localsend/localsend](https://github.com/localsend/localsend) and I found a few solution for this.

The simplest solution is using `Stream.asBroadcastStream()` to cancel the file stream when there are no subscribers,

```dart
const fileName = "some/file/path";

final file = File(fileName);
final fileStream = file.openRead().asBroadcastStream();

final client = HttpClient();

try {
  final request = await client.postUrl(
    Uri.parse('https://httpbun.com/post'),
  );
  final future = request.addStream(fileStream);
  await future.catchError((e, s) {
    request.abort(e, s);
    debugPrint("Aborted");
    return future;
  });
} catch (_) {
  await file.delete(); // Still throws `PathAccessException` because the file stream has not yet canceled
  
  // Using the `retry` package may solve the problem, but it's not the best approach in this case
}
```

but the downside is that you have to wait until the broadcast stream cancels itself, so here's a more complex but manageable way to do it, 

```dart
const fileName = "some/file/path";

final file = File(fileName);
final fileStream = file.openRead();
final fileReadController = StreamController<List<int>>();
final fileReadSubscription = fileStream.listen(
  fileReadController.add,
  onError: fileReadController.addError,
  onDone: () => fileReadController.close()
);

final client = HttpClient();

try {
  final request = await client.postUrl(
    Uri.parse('https://httpbun.com/post'),
  );
  final future = request.addStream(fileReadController.stream);
  await future.catchError((e, s) {
    request.abort(e, s);
    debugPrint("Aborted");
    return future;
  });
} catch (_) {
  await fileReadSubscription.cancel(); // Cancel manually to delete files right away
  await file.delete();
}
```

which is basically just extracting the implementation of the `AsBroadcastStream` class.

That's my solution, let me know if there are any problems or there is a better solution.
