### ISSUE TITLE
[dart2wasm] LateInitializationError in Flutter app

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#54406]
Originally reported in https://github.com/flutter/flutter/issues/140110. Moving it here to keep track of all dart2wasm bugs in one place.

Clone https://github.com/tylandercasper/getx_badcompile and run `flutter build web --wasm` in `example` directory. dart2wasm crashes with:

```
Unhandled exception:
LateInitializationError: Field 'currentLocal' has not been initialized.
#0      CodeGenerator.visitVariableDeclaration (package:dart2wasm/code_generator.dart)
#1      VariableDeclaration.accept (package:kernel/ast.dart:10748)
#2      CodeGenerator.visitStatement (package:dart2wasm/code_generator.dart:889)
#3      CodeGenerator.visitLet (package:dart2wasm/code_generator.dart:1709)
#4      Let.accept1 (package:kernel/ast.dart:8725)
#5      CodeGenerator.wrap (package:dart2wasm/code_generator.dart:878)
#6      CodeGenerator.visitEqualsCall (package:dart2wasm/code_generator.dart:1954)
#7      EqualsCall.accept1 (package:kernel/ast.dart:6302)
#8      CodeGenerator.wrap (package:dart2wasm/code_generator.dart:878)
#9      CodeGenerator.branchIf (package:dart2wasm/code_generator.dart:1387)
#10     CodeGenerator.branchIf (package:dart2wasm/code_generator.dart:1384)
#11     AsyncCodeGenerator.jumpToTarget (package:dart2wasm/async.dart:829)
#12     AsyncCodeGenerator.visitWhileStatement (package:dart2wasm/async.dart:1229)
#13     WhileStatement.accept (package:kernel/ast.dart:9526)
#14     CodeGenerator.visitStatement (package:dart2wasm/code_generator.dart:889)
#15     CodeGenerator.visitBlock (package:dart2wasm/code_generator.dart:1011)
#16     Block.accept (package:kernel/ast.dart:9199)
#17     CodeGenerator.visitStatement (package:dart2wasm/code_generator.dart:889)
#18     AsyncCodeGenerator._generateInner (package:dart2wasm/async.dart:770)
#19     AsyncCodeGenerator._generateBodies (package:dart2wasm/async.dart:596)
#20     AsyncCodeGenerator.generate (package:dart2wasm/async.dart:542)
#21     Translator.translate (package:dart2wasm/translator.dart:349)
#22     compileToModule (package:dart2wasm/compile.dart:151)
<asynchronous suspension>
#23     main (package:dart2wasm/dart2wasm.dart:144)
<asynchronous suspension>
#24     main (file:///b/s/w/ir/x/w/sdk/pkg/dart2wasm/bin/dart2wasm.dart:7)
<asynchronous suspension>
```

It should be easy to fix but I'm unable to figure out how to build this with a local dart2wasm. With `flutter build web --wasm --verbose` I see this invocation of dart2wasm:

```
/usr/local/google/home/omersa/dart/flutter/bin/cache/dart-sdk/bin/dartaotruntime \
    --disable-dart-dev \
    /usr/local/google/home/omersa/dart/flutter/bin/cache/dart-sdk/bin/snapshots/dart2wasm_product.snapshot \
    --packages=.dart_tool/package_config.json \
    --dart-sdk=/usr/local/google/home/omersa/dart/flutter/bin/cache/dart-sdk \
    --platform=/usr/local/google/home/omersa/dart/flutter/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill \
    -Ddart.vm.product=true \
    -DFLUTTER_WEB_AUTO_DETECT=true \
    -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/6f499ecea6570f1b7df5c7813ef9e4456d56c426/ \
    --depfile=/usr/local/google/home/omersa/dart/getx_badcompile/example/.dart_tool/flutter_build/af0191ce039bb4770bc6a3450c7f725f/dart2wasm.d \
    /usr/local/google/home/omersa/dart/getx_badcompile/example/.dart_tool/flutter_build/af0191ce039bb4770bc6a3450c7f725f/main.dart \
    /usr/local/google/home/omersa/dart/getx_badcompile/example/.dart_tool/flutter_build/af0191ce039bb4770bc6a3450c7f725f/main.dart.unopt.wasm
```

To run this command with a local dart2wasm:

- Remove `--disable-dart-dev`, it's a `dartaotruntime` argument that we don't support.
- Similarly remove the snapshot file argument.

Which gives me:

```
/usr/local/google/home/omersa/dart/sdk/sdk/sdk/bin/dart2wasm \
    --packages=.dart_tool/package_config.json \
    --dart-sdk=/usr/local/google/home/omersa/dart/flutter/bin/cache/dart-sdk \
    --platform=/usr/local/google/home/omersa/dart/flutter/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill \
    -Ddart.vm.product=true \
    -DFLUTTER_WEB_AUTO_DETECT=true \
    -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/6f499ecea6570f1b7df5c7813ef9e4456d56c426/ \
    --depfile=/usr/local/google/home/omersa/dart/getx_badcompile/example/.dart_tool/flutter_build/af0191ce039bb4770bc6a3450c7f725f/dart2wasm.d \
    /usr/local/google/home/omersa/dart/getx_badcompile/example/.dart_tool/flutter_build/af0191ce039bb4770bc6a3450c7f725f/main.dart \
    /usr/local/google/home/omersa/dart/getx_badcompile/example/.dart_tool/flutter_build/af0191ce039bb4770bc6a3450c7f725f/main.dart.unopt.wasm
```

Which fails with

```
Unexpected Kernel Format Version 113 (expected 114) when reading file:///usr/local/google/home/omersa/dart/flutter/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill.
```

When I remove the platform argument:

```
/usr/local/google/home/omersa/dart/sdk/sdk/sdk/bin/dart2wasm \
    --packages=.dart_tool/package_config.json \
    --dart-sdk=/usr/local/google/home/omersa/dart/flutter/bin/cache/dart-sdk \
    -Ddart.vm.product=true \
    -DFLUTTER_WEB_AUTO_DETECT=true \
    -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/6f499ecea6570f1b7df5c7813ef9e4456d56c426/ \
    --depfile=/usr/local/google/home/omersa/dart/getx_badcompile/example/.dart_tool/flutter_build/af0191ce039bb4770bc6a3450c7f725f/dart2wasm.d \
    /usr/local/google/home/omersa/dart/getx_badcompile/example/.dart_tool/flutter_build/af0191ce039bb4770bc6a3450c7f725f/main.dart \
    /usr/local/google/home/omersa/dart/getx_badcompile/example/.dart_tool/flutter_build/af0191ce039bb4770bc6a3450c7f725f/main.dart.unopt.wasm
```

I get hundreds of undefined method, type etc. errors.

I also tried to remove `--packages`, `--dart-sdk`, and `--depfile` arguments individually and all at once, but got the same erorrs.

**Comment by osa1** [comment]
@mraleph showed me how to build this with a local SDK. We need to rebuild the `dart2wasm_platform.dill` with the same local SDK as the SDK we want to build the project with. The steps for that:

1. Build SDK.
2. In `engine/src/flutter/prebuilts/linux-x64`, move the `dart-sdk` directory to somewhere (or remove it), and symlink the local build `$SDK_CHECKOUT/out/ReleaseX64/dart-sdk` with the same name.
3. In `engine/src`, run `flutter/tools/gn --wasm; ninja -C out/wasm_debug -v flutter_web_sdk/kernel/dart2wasm_platform.dill`.
4. The new platform file built with the local SDK will be in `out/wasm_debug/flutter_web_sdk/kernel/dart2wasm_platform.dill`.

Pass the path to the new platform file as `--platform=...`.

**Comment by osa1** [comment]
Smaller repro:

```dart
class PageSettings {
  String name;

  PageSettings(this.name);
}

class GetDelegate {
  PageSettings? get pageSettings => PageSettings("a");

  Future<void> popModeUntil(String fullRoute) async {
    while (pageSettings?.name != fullRoute) {
      await null;
    }
  }
}

void main() async {
  await GetDelegate().popModeUntil("");
}
```

Output:

```
Unhandled exception:
LateInitializationError: Field 'currentLocal' has not been initialized.
#0      CodeGenerator.visitVariableDeclaration (package:dart2wasm/code_generator.dart)
#1      VariableDeclaration.accept (package:kernel/ast.dart:10744)
#2      CodeGenerator.visitStatement (package:dart2wasm/code_generator.dart:892)
#3      CodeGenerator.visitLet (package:dart2wasm/code_generator.dart:1718)
#4      Let.accept1 (package:kernel/ast.dart:8721)
#5      CodeGenerator.wrap (package:dart2wasm/code_generator.dart:881)
#6      CodeGenerator.visitEqualsCall (package:dart2wasm/code_generator.dart:1963)
#7      EqualsCall.accept1 (package:kernel/ast.dart:6298)
#8      CodeGenerator.wrap (package:dart2wasm/code_generator.dart:881)
#9      CodeGenerator.branchIf (package:dart2wasm/code_generator.dart:1396)
#10     AsyncCodeGenerator.jumpToTarget (package:dart2wasm/async.dart:855)
#11     AsyncCodeGenerator.visitWhileStatement (package:dart2wasm/async.dart:1255)
#12     WhileStatement.accept (package:kernel/ast.dart:9522)
#13     CodeGenerator.visitStatement (package:dart2wasm/code_generator.dart:892)
#14     CodeGenerator.visitBlock (package:dart2wasm/code_generator.dart:1014)
#15     Block.accept (package:kernel/ast.dart:9195)
#16     CodeGenerator.visitStatement (package:dart2wasm/code_generator.dart:892)
#17     AsyncCodeGenerator._generateInner (package:dart2wasm/async.dart:778)
#18     AsyncCodeGenerator._generateBodies (package:dart2wasm/async.dart:597)
#19     AsyncCodeGenerator.generate (package:dart2wasm/async.dart:542)
#20     Translator.translate (package:dart2wasm/translator.dart:352)
#21     compileToModule (package:dart2wasm/compile.dart:151)
<asynchronous suspension>
#22     generateWasm (package:dart2wasm/generate_wasm.dart:21)
<asynchronous suspension>
#23     main (file:///usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/dart2wasm.dart:10)
<asynchronous suspension>
```
