### ISSUE TITLE
service/resume_shutdown_race_test pass->fail on vm-win-release-arm64 

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#54408]
[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8761318711098448049/+/u/test_results/new_test_failures__logs_)

This test seems to be evading deflakiness infrastructure as there are multiple similar failures for this test.

```
/===========================================================================\
| service/resume_shutdown_race_test/dds broke (Pass -> Fail, expected Pass) |
\===========================================================================/

--- Command "vm" (took 375ms):
set DART_CONFIGURATION=ReleaseARM64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=c:\opt\s\w\ir\cache\builder\sdk\out\ReleaseARM64\crashpad_handler.exe & out\ReleaseARM64\dart.exe --pause-isolate-on-exit --enable-vm-service=0 --disable-service-auth-codes -DUSE_DDS=true --sound-null-safety -Dtest_runner.configuration=vm-win-release-arm64 --ignore-unrecognized-flags --packages=C:\opt\s\w\ir\cache\builder\sdk\.dart_tool\package_config.json C:\opt\s\w\ir\cache\builder\sdk\runtime\observatory\tests\service\resume_shutdown_race_test.dart

exit code:
1

stderr:
ProcessException: The system cannot find the file specified.

  Command: C:\opt\s\w\ir\cache\builder\sdk\out\bin\dartaotruntime C:\opt\s\w\ir\cache\builder\sdk\out\ReleaseARM64\dds_aot.dart.snapshot http://127.0.0.1:63764// localhost 0 true true C:\opt\s\w\ir\cache\builder\sdk\out\ReleaseARM64\devtools false false
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _DebuggingSession.start (package:dartdev/src/commands/run.dart:417:35)
<asynchronous suspension>
#3      RunCommand.run (package:dartdev/src/commands/run.dart:290:14)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      DartdevRunner.runCommand (package:dartdev/dartdev.dart:249:18)
<asynchronous suspension>
#6      runDartdev (package:dartdev/dartdev.dart:57:16)
<asynchronous suspension>
#7      main (file:///c:/opt/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-win-release-arm64 service/resume_shutdown_race_test/dds


/===============================================================================\
| service/resume_shutdown_race_test/service broke (Pass -> Fail, expected Pass) |
\===============================================================================/

--- Command "vm" (took 390ms):
set DART_CONFIGURATION=ReleaseARM64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=c:\opt\s\w\ir\cache\builder\sdk\out\ReleaseARM64\crashpad_handler.exe & out\ReleaseARM64\dart.exe --pause-isolate-on-exit --enable-vm-service=0 --disable-service-auth-codes --sound-null-safety -Dtest_runner.configuration=vm-win-release-arm64 --ignore-unrecognized-flags --packages=C:\opt\s\w\ir\cache\builder\sdk\.dart_tool\package_config.json C:\opt\s\w\ir\cache\builder\sdk\runtime\observatory\tests\service\resume_shutdown_race_test.dart

exit code:
1

stderr:
ProcessException: The system cannot find the file specified.

  Command: C:\opt\s\w\ir\cache\builder\sdk\out\bin\dartaotruntime C:\opt\s\w\ir\cache\builder\sdk\out\ReleaseARM64\dds_aot.dart.snapshot http://127.0.0.1:63763// localhost 0 true true C:\opt\s\w\ir\cache\builder\sdk\out\ReleaseARM64\devtools false false
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _DebuggingSession.start (package:dartdev/src/commands/run.dart:417:35)
<asynchronous suspension>
#3      RunCommand.run (package:dartdev/src/commands/run.dart:290:14)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      DartdevRunner.runCommand (package:dartdev/dartdev.dart:249:18)
<asynchronous suspension>
#6      runDartdev (package:dartdev/dartdev.dart:57:16)
<asynchronous suspension>
#7      main (file:///c:/opt/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-win-release-arm64 service/resume_shutdown_race_test/service
```

cc @bkonyi

**Comment by aam** [comment]
Failed again https://dart-ci.appspot.com/log/vm-win-release-arm64/vm-win-release-arm64/1029/service/resume_shutdown_race_test/dds

**Comment by a-siva** [comment]
Fixed by derek's change https://dart-review.googlesource.com/c/sdk/+/342640
