### ISSUE TITLE
Failures on [vm/ffi] Improve error messages on Windows

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#54424]
There are new test failures on [[vm/ffi] Improve error messages on Windows](https://github.com/dart-lang/sdk/commit/ada6b817613b2fc74ac8ac83cbf2c04ccd874a1e).

The tests
```
ffi/dylib_open_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-mac-debug-x64
vm-mac-release-x64
```

Log:
```
--- Command "vm" (took 879ms):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --sound-null-safety -Dtest_runner.configuration=vm-mac-release-x64 --ignore-unrecognized-flags --packages=/opt/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json /opt/s/w/ir/cache/builder/sdk/tests/ffi/dylib_open_test.dart

exit code:
255

stderr:
Unhandled exception:
String 'no such file' not found within 'Failed to load dynamic library 'libdoesnotexist1234.dylib': dlopen(libdoesnotexist1234.dylib, 1): image not found'
#0      Expect._fail (package:expect/expect.dart:721:5)
#1      Expect.contains (package:expect/expect.dart:463:7)
#2      testDoesNotExist (file:///opt/s/w/ir/cache/builder/sdk/tests/ffi/dylib_open_test.dart:29:12)
#3      main (file:///opt/s/w/ir/cache/builder/sdk/tests/ffi/dylib_open_test.dart:13:3)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n vm-mac-release-x64 ffi/dylib_open_test
```

/cc @dcharkes @simolus3

**Comment by dcharkes** [comment]
Note to self: Request more bots in the footer commit. 🙃

**Comment by simolus3** [comment]
Will do! I've only tested these locally and it seems like the error message is different on my mac :(

**Comment by dcharkes** [comment]
Yeah, let's try to add a bot for each OS in the CL footer next time we land CLs that have OS-specific things.
