### ISSUE TITLE
Reverse DNS lookup on LAN ip Android regression

### ISSUE THREAD

**Issue by guyluz11** [dart-lang/sdk#54435]
Reverse DNS lookup on LAN IP Android does not work in the last Flutter version.
I understand that this is dart-lang and my issue is with Flutter Android but I got redirected https://github.com/flutter/flutter/issues/140506

Can reproduce for Android, tested also on Flutter Linux and couldn't reproduce.
I think this is a regression.
Only for local IP (LAN).

1. Create an app and prepare an Android device.
2. Find a local network's IP with a hostname.
3. Add internet permission to Android `<uses-permission android:name="android.permission.INTERNET"/>`
4. Paste the example code and replace `ip_with_host_name` with the IP you found.

Getting an error in the console that the devices can't be found.

### Logs

<details open><summary>Logs</summary>

```console
E/flutter ( 6212): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed reverse host lookup (OS Error: hostname nor servname provided, or not known, errno = 8), address = 192.168.31.81
E/flutter ( 6212): #0      _NativeSocket.reverseLookup.<anonymous closure> (dart:io-patch/socket_patch.dart:538:9)
E/flutter ( 6212): <asynchronous suspension>
E/flutter ( 6212): #1      _MyHomePageState.initialize (package:untitled/main.dart:42:18)
E/flutter ( 6212): <asynchronous suspension>
```

</details>

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();

    initialize();
  }

  initialize() async {
    print('go');
    print('Ip ${(await InternetAddress('ip_with_host_name').reverse()).host}');
  }

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: SizedBox(),
    );
  }
}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (2 days ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4

```

</details>

**Comment by a-siva** [comment]
@guyluz11 You mention above that this is a regression.
Which version onwards you are seeing this failure. That would help us track down the potential change which could have triggered the regression.

**Comment by guyluz11** [comment]
I can't really tell sorry, I'm pretty sure it worked a year ago.

**Comment by a-siva** [comment]
@guyluz11 Have you also upgraded the version of Android you are using or is it the same version you had when it was working? I am trying to determine if there could be a potential regression in Android OS.

**Comment by guyluz11** [comment]
Android version got upgraded as well

**Comment by brianquinlan** [comment]
InternetAddress.reverse() uses [`getnameinfo`](https://github.com/dart-lang/sdk/blob/807f2a3281a36e0a3c4d4a212e3a9b208cecccd3/runtime/bin/socket_base_android.cc#L279) on Android.

**Comment by iadept** [comment]
I have the same problem, tested on Android emulator starting from version 9

**Comment by a-siva** [comment]
Not sure if there is anything to do on the Dart side if this is a regression in Android's getnameinfo function.
