### ISSUE TITLE
The analyzer keeps crashing in VSCode when using extension type

### ISSUE THREAD

**Issue by microtears** [dart-lang/sdk#54454]
Unhandled exception:

```
[16:07:14] [Analyzer] [Error] Unhandled exception:
Bad state: Empty path: [Object?, JsonValue]
#0      InterfaceLeastUpperBoundHelper._computeTypeAtMaxUniqueDepth (package:analyzer/src/dart/element/least_upper_bound.dart:315:5)
#1      InterfaceLeastUpperBoundHelper._computeLeastUpperBound (package:analyzer/src/dart/element/least_upper_bound.dart:182:12)
#2      InterfaceLeastUpperBoundHelper.compute (package:analyzer/sr
```

Minimal example：

[DartPad](https://dartpad.dev/?id=7fac700a5ef720fdce1b7a80647c171f&channel=master)

[extension_type_example](https://github.com/microtears/extension_type_example)

<details>

<summary>dart info</summary>

```plain
If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.3.0-174.3.beta (beta) (Tue Dec 12 14:49:22 2023 +0000) on "macos_arm64"
- on macos / Version 14.1 (Build 23B74)
- locale is zh-Hans-CN

#### Project info

- sdk constraint: '>=3.3.0-0 <4.0.0'
- dependencies: async, collection, meta
- dev_dependencies: checks, logging, test

#### Process info

No Dart processes found.
```
</details>

<details>

<summary>VSCode log</summary>

```plain
[15:50:51] [General] [Info]         /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
[15:50:51] [General] [Info]         /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
[15:50:51] [General] [Info]         /Library/Apple/usr/bin
[15:50:51] [General] [Info]         /opt/puppetlabs/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/
[15:50:51] [General] [Info]         /opt/homebrew/bin
[15:50:51] [General] [Info]         /opt/homebrew/sbin
[15:50:51] [General] [Info]         /Users/anya/.local/share/fig/plugins/git-open
[15:50:51] [General] [Info]         /Users/anya/.local/share/fig/plugins/git-open -> /Users/anya/.local/share/fig/plugins/git-open/bin
[15:50:51] [General] [Info]         /usr/local/sbin
[15:50:51] [General] [Info]         /Users/anya/ysy/scala-2.11.8/bin
[15:50:51] [General] [Info]         /home/linuxbrew/.linuxbrew/Cellar/gcc/13.1.0/bin
[15:50:51] [General] [Info]         /usr/local/opt/mysql-client/bin
[15:50:51] [General] [Info]         /Users/anya/go/bin
[15:50:51] [General] [Info]         /Users/anya/.cargo/bin
[15:50:51] [General] [Info]         /usr/local/opt/inetutils/libexec/gnubin
[15:50:51] [General] [Info]         /usr/local/opt/inetutils/libexec/gnubin -> /usr/local/opt/inetutils/libexec/gnubin/bin
[15:50:51] [General] [Info]         /usr/local/opt/sqlite/bin
[15:50:51] [General] [Info]         /Users/anya/.npm-global/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin
[15:50:51] [General] [Info]         /Users/anya/.pub-cache/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin/cache/dart-sdk/bin
[15:50:51] [General] [Info]         /Users/anya/Library/Android/sdk/tools/bin
[15:50:51] [General] [Info]         /Users/anya/Library/Android/sdk/platform-tools
[15:50:51] [General] [Info]         /Users/anya/Library/Android/sdk/platform-tools -> /Users/anya/Library/Android/sdk/platform-tools/bin
[15:50:51] [General] [Info]         /Users/anya/.fig/bin
[15:50:51] [General] [Info]         /Users/anya/.local/bin
[15:50:51] [General] [Info]         /Users/anya/Library/Application Support/JetBrains/Toolbox/scripts
[15:50:51] [General] [Info]         /Users/anya/Library/Application Support/JetBrains/Toolbox/scripts -> /Users/anya/Library/Application Support/JetBrains/Toolbox/scripts/bin
[15:50:51] [General] [Info]         /Users/anya/Library/Application Support/JetBrains/Toolbox/scripts
[15:50:51] [General] [Info]         /Users/anya/Library/Application Support/JetBrains/Toolbox/scripts -> /Users/anya/Library/Application Support/JetBrains/Toolbox/scripts/bin
[15:50:51] [General] [Info]     Found at:
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin
[15:50:51] [General] [Info] Following symlink: /Users/anya/fvm/default/bin/flutter -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/flutter
[15:50:51] [General] [Info] Following symlink: /Users/anya/fvm/default/bin/flutter -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/flutter
[15:50:51] [General] [Info] Following symlink: /Users/anya/fvm/default/bin/flutter -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/flutter
[15:50:51] [General] [Info]     Candidate paths to be post-filtered:
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin -> /Users/anya/fvm/versions/3.18.0-0.2.pre
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin -> /Users/anya/fvm/versions/3.18.0-0.2.pre
[15:50:51] [General] [Info]         /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/ -> /Users/anya/fvm/versions/3.18.0-0.2.pre
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin -> /Users/anya/fvm/versions/3.18.0-0.2.pre
[15:50:51] [General] [Info]     Found at /Users/anya/fvm/default/bin -> /Users/anya/fvm/versions/3.18.0-0.2.pre
[15:50:51] [General] [Info]     Returning SDK path /Users/anya/fvm/versions/3.18.0-0.2.pre for flutter
[15:50:51] [General] [Info] Searching for dart
[15:50:51] [General] [Info]     Looking for dart in:
[15:50:51] [General] [Info]         /opt/homebrew/bin
[15:50:51] [General] [Info]         /opt/homebrew/sbin
[15:50:51] [General] [Info]         /opt/homebrew/bin
[15:50:51] [General] [Info]         /usr/local/sbin
[15:50:51] [General] [Info]         /Users/anya/ysy/scala-2.11.8/bin
[15:50:51] [General] [Info]         /home/linuxbrew/.linuxbrew/Cellar/gcc/13.1.0/bin
[15:50:51] [General] [Info]         /usr/local/opt/mysql-client/bin
[15:50:51] [General] [Info]         /Users/anya/go/bin
[15:50:51] [General] [Info]         /Users/anya/.cargo/bin
[15:50:51] [General] [Info]         /usr/local/opt/inetutils/libexec/gnubin
[15:50:51] [General] [Info]         /usr/local/opt/inetutils/libexec/gnubin -> /usr/local/opt/inetutils/libexec/gnubin/bin
[15:50:51] [General] [Info]         /usr/local/opt/sqlite/bin
[15:50:51] [General] [Info]         /Users/anya/.npm-global/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin
[15:50:51] [General] [Info]         /Users/anya/.pub-cache/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin/cache/dart-sdk/bin
[15:50:51] [General] [Info]         /Users/anya/Library/Android/sdk/tools/bin
[15:50:51] [General] [Info]         /Users/anya/Library/Android/sdk/platform-tools
[15:50:51] [General] [Info]         /Users/anya/Library/Android/sdk/platform-tools -> /Users/anya/Library/Android/sdk/platform-tools/bin
[15:50:51] [General] [Info]         /Users/anya/.local/share/fig/plugins/git-open
[15:50:51] [General] [Info]         /Users/anya/.local/share/fig/plugins/git-open -> /Users/anya/.local/share/fig/plugins/git-open/bin
[15:50:51] [General] [Info]         /opt/homebrew/bin
[15:50:51] [General] [Info]         /usr/local/sbin
[15:50:51] [General] [Info]         /Users/anya/ysy/scala-2.11.8/bin
[15:50:51] [General] [Info]         /home/linuxbrew/.linuxbrew/Cellar/gcc/13.1.0/bin
[15:50:51] [General] [Info]         /usr/local/opt/mysql-client/bin
[15:50:51] [General] [Info]         /Users/anya/go/bin
[15:50:51] [General] [Info]         /Users/anya/.cargo/bin
[15:50:51] [General] [Info]         /usr/local/opt/inetutils/libexec/gnubin
[15:50:51] [General] [Info]         /usr/local/opt/inetutils/libexec/gnubin -> /usr/local/opt/inetutils/libexec/gnubin/bin
[15:50:51] [General] [Info]         /usr/local/opt/sqlite/bin
[15:50:51] [General] [Info]         /Users/anya/.npm-global/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin
[15:50:51] [General] [Info]         /Users/anya/.pub-cache/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin/cache/dart-sdk/bin
[15:50:51] [General] [Info]         /Users/anya/Library/Android/sdk/tools/bin
[15:50:51] [General] [Info]         /Users/anya/Library/Android/sdk/platform-tools
[15:50:51] [General] [Info]         /Users/anya/Library/Android/sdk/platform-tools -> /Users/anya/Library/Android/sdk/platform-tools/bin
[15:50:51] [General] [Info]         /usr/local/bin
[15:50:51] [General] [Info]         /System/Cryptexes/App/usr/bin
[15:50:51] [General] [Info]         /usr/bin
[15:50:51] [General] [Info]         /bin
[15:50:51] [General] [Info]         /usr/sbin
[15:50:51] [General] [Info]         /sbin
[15:50:51] [General] [Info]         /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
[15:50:51] [General] [Info]         /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
[15:50:51] [General] [Info]         /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
[15:50:51] [General] [Info]         /Library/Apple/usr/bin
[15:50:51] [General] [Info]         /opt/puppetlabs/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/
[15:50:51] [General] [Info]         /opt/homebrew/bin
[15:50:51] [General] [Info]         /opt/homebrew/sbin
[15:50:51] [General] [Info]         /Users/anya/.local/share/fig/plugins/git-open
[15:50:51] [General] [Info]         /Users/anya/.local/share/fig/plugins/git-open -> /Users/anya/.local/share/fig/plugins/git-open/bin
[15:50:51] [General] [Info]         /usr/local/sbin
[15:50:51] [General] [Info]         /Users/anya/ysy/scala-2.11.8/bin
[15:50:51] [General] [Info]         /home/linuxbrew/.linuxbrew/Cellar/gcc/13.1.0/bin
[15:50:51] [General] [Info]         /usr/local/opt/mysql-client/bin
[15:50:51] [General] [Info]         /Users/anya/go/bin
[15:50:51] [General] [Info]         /Users/anya/.cargo/bin
[15:50:51] [General] [Info]         /usr/local/opt/inetutils/libexec/gnubin
[15:50:51] [General] [Info]         /usr/local/opt/inetutils/libexec/gnubin -> /usr/local/opt/inetutils/libexec/gnubin/bin
[15:50:51] [General] [Info]         /usr/local/opt/sqlite/bin
[15:50:51] [General] [Info]         /Users/anya/.npm-global/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin
[15:50:51] [General] [Info]         /Users/anya/.pub-cache/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin/cache/dart-sdk/bin
[15:50:51] [General] [Info]         /Users/anya/Library/Android/sdk/tools/bin
[15:50:51] [General] [Info]         /Users/anya/Library/Android/sdk/platform-tools
[15:50:51] [General] [Info]         /Users/anya/Library/Android/sdk/platform-tools -> /Users/anya/Library/Android/sdk/platform-tools/bin
[15:50:51] [General] [Info]         /Users/anya/.fig/bin
[15:50:51] [General] [Info]         /Users/anya/.local/bin
[15:50:51] [General] [Info]         /Users/anya/Library/Application Support/JetBrains/Toolbox/scripts
[15:50:51] [General] [Info]         /Users/anya/Library/Application Support/JetBrains/Toolbox/scripts -> /Users/anya/Library/Application Support/JetBrains/Toolbox/scripts/bin
[15:50:51] [General] [Info]         /Users/anya/Library/Application Support/JetBrains/Toolbox/scripts
[15:50:51] [General] [Info]         /Users/anya/Library/Application Support/JetBrains/Toolbox/scripts -> /Users/anya/Library/Application Support/JetBrains/Toolbox/scripts/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk
[15:50:51] [General] [Info]         /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk/bin
[15:50:51] [General] [Info]     Found at:
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin/cache/dart-sdk/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin/cache/dart-sdk/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin/cache/dart-sdk/bin
[15:50:51] [General] [Info]         /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk/bin
[15:50:51] [General] [Info] Following symlink: /Users/anya/fvm/default/bin/dart -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/dart
[15:50:51] [General] [Info] Following symlink: /Users/anya/fvm/default/bin/cache/dart-sdk/bin/dart -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk/bin/dart
[15:50:51] [General] [Info] Following symlink: /Users/anya/fvm/default/bin/dart -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/dart
[15:50:51] [General] [Info] Following symlink: /Users/anya/fvm/default/bin/cache/dart-sdk/bin/dart -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk/bin/dart
[15:50:51] [General] [Info] Following symlink: /Users/anya/fvm/default/bin/dart -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/dart
[15:50:51] [General] [Info] Following symlink: /Users/anya/fvm/default/bin/cache/dart-sdk/bin/dart -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk/bin/dart
[15:50:51] [General] [Info]     Candidate paths to be post-filtered:
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin -> /Users/anya/fvm/versions/3.18.0-0.2.pre
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin/cache/dart-sdk/bin -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin -> /Users/anya/fvm/versions/3.18.0-0.2.pre
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin/cache/dart-sdk/bin -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk
[15:50:51] [General] [Info]         /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/ -> /Users/anya/fvm/versions/3.18.0-0.2.pre
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin -> /Users/anya/fvm/versions/3.18.0-0.2.pre
[15:50:51] [General] [Info]         /Users/anya/fvm/default/bin/cache/dart-sdk/bin -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk
[15:50:51] [General] [Info]         /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk
[15:50:51] [General] [Info]     Found at /Users/anya/fvm/default/bin/cache/dart-sdk/bin -> /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk
[15:50:51] [General] [Info]     Returning SDK path /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk for dart
[15:50:51] [General] [Info] Experiment random number is 89 for experiment 'sdkDaps'. Experiment is enabled for <= 100
[15:50:51] [General] [Info] Experiment 'sdkDaps' is activating (not first time)
[15:50:51] [General] [Info] Experiment random number is 89 for experiment 'sdkDaps'. Experiment is enabled for <= 100
[15:50:51] [General] [Info] Experiment 'sdkDaps' is activating (not first time)
[15:50:51] [General] [Info] Experiment random number is 89 for experiment 'sdkDaps'. Experiment is enabled for <= 10
[15:50:51] [General] [Info] Experiment 'sdkDaps' does not apply and will not be activated
[15:50:51] [General] [Info] !! ⚠️ PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!
Dart Code extension: 3.79.20231221
Flutter extension: 3.79.20231130 (not activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.85.1

Workspace type: Dart (LSP)

Dart (3.3.0-174.3.beta): /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk
Flutter (3.18.0-0.2.pre): /Users/anya/fvm/versions/3.18.0-0.2.pre (No device)
[15:50:51] [Analyzer] [Info] Spawning /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.79.20231221"]
[15:50:51] [Analyzer] [Info]     PID: 61273
[15:50:51] [General] [Info] Returning cached results for project search
[15:50:51] [General] [Info] Found 0 folders requiring "pub get" or "pub upgrade":
[15:50:51] [Analyzer] [Info] ==> Content-Length: 6474
[15:50:51] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":61244,"clientInfo":{"name":"Visual Studio Code","version":"1.85.1"},"locale":"en","rootPath":"/Users/anya/workspace/workspace/dart/packages/common","rootUri":"file:///Users/anya/workspace/workspace/dart/packages/common","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"…
[15:50:51] [General] [Info] Loaded 20000 package names from vscode-userdata:/Users/anya/Library/Application%20Support/Code/User/globalStorage/dart-code.dart-code/package_cache.json
[15:50:52] [Analyzer] [Info] <== Content-Length: 652
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":0,"jsonrpc":"2.0","result":{"capabilities":{"executeCommandProvider":{"commands":["edit.sortMembers","edit.organizeImports","edit.fixAll","edit.sendWorkspaceEdit","refactor.perform","refactor.validate","dart.logAction","dart.refactor.convert_all_formal_parameters_to_named","dart.refactor.convert_selected_formal_parameters_to_named","dart.refactor.move_selected_formal_parameters_left","dart.refactor.move_top…
[15:50:52] [Analyzer] [Info] ==> Content-Length: 86
[15:50:52] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"initialized","params":{},"clientRequestTime":1703577052334}
[15:50:52] [Analyzer] [Info] <== Content-Length: 191
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":1,"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///Users/anya/workspace/workspace/dart/packages/common","section":"dart"},{"section":"dart"}]}}
[15:50:52] [Analyzer] [Info] ==> Content-Length: 7659
[15:50:52] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":1,"result":[{"additionalAnalyzerFileExtensions":[],"analysisExcludedFolders":["discontinued","bricks"],"analyzeAngularTemplates":true,"analyzerAdditionalArgs":[],"analyzerVmAdditionalArgs":[],"analyzerDiagnosticsPort":null,"analyzerPath":null,"analyzerSshHost":null,"analyzerVmServicePort":null,"includeDependenciesInWorkspaceSymbols":true,"notifyAnalyzerErrors":true,"onlyAnalyzeProjectsWithOpenFiles":false,"showTodos":false,"showExtensionRecommendations":true,"useLegacyA…
[15:50:52] [Analyzer] [Info] <== Content-Length: 97
Content-Type: application/vscode-jsonrpc; charset=utf-8
[15:50:52] [Analyzer] [Info] <== {"id":2,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"ANALYZING"}}
[15:50:52] [Analyzer] [Info] ==> Content-Length: 72
[15:50:52] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":2,"result":null,"clientRequestTime":1703577052622}
[15:50:52] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8
[15:50:52] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}}}
[15:50:52] [Analyzer] [Info] <== Content-Length: 5354
Content-Type: application/vscode-jsonrpc; charset=utf-8
[15:50:52] [Analyzer] [Info] <== {"id":3,"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"0","method":"textDocument/prepareCallHierarchy","registerOptions":{"documentSelector":[{"language":"dart","scheme":"file"}]}},{"id":"1","method":"textDocument/codeAction","registerOptions":{"codeActionKinds":["source","source.organizeImports","source.fixAll","source.sortMembers","quickfix","refactor"],"documentSelector":[{"language":"dart","scheme":"file"}]}},{"id":"2","method":"textDocument/comple…
[15:50:52] [Analyzer] [Info] ==> Content-Length: 72
[15:50:52] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":3,"result":null,"clientRequestTime":1703577052807}
[15:50:53] [Analyzer] [Info] <== Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8
[15:50:53] [Analyzer] [Error] Unhandled exception:
Bad state: Empty path: [Object?, JsonValue]
#0      InterfaceLeastUpperBoundHelper._computeTypeAtMaxUniqueDepth (package:analyzer/src/dart/element/least_upper_bound.dart:315:5)
#1      InterfaceLeastUpperBoundHelper._computeLeastUpperBound (package:analyzer/src/dart/element/least_upper_bound.dart:182:12)
#2      InterfaceLeastUpperBoundHelper.compute (package:analyzer/src/dart/element/least_upper_bound.dart:102:18)
#3      LeastUpperBoundHelper.getLeastUpperBound (package:an…
[15:50:53] [Analyzer] [Info] Spawning /Users/anya/fvm/versions/3.18.0-0.2.pre/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.79.20231221"]
[15:50:53] [Analyzer] [Info]     PID: 61304
[15:50:53] [Analyzer] [Info] ==> Content-Length: 6474
[15:50:53] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":61244,"clientInfo":{"name":"Visual Studio Code","version":"1.85.1"},"locale":"en","rootPath":"/Users/anya/workspace/workspace/dart/packages/common","rootUri":"file:///Users/anya/workspace/workspace/dart/packages/common","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"…
```
</details>

**Comment by parlough** [comment]
Thanks for reporting the issue and for providing the reproduction on DartPad!

\cc @scheglov

**Comment by scheglov** [comment]
Even more reduced example
```dart
extension type const E1(Object? value) {}

extension type const E2(Object? value) implements E1 {}

extension type const E3(Object? value) implements E1 {}

E1 f(bool b, Object? value) {
  return b ? E2(value) : E3(value);
}
```
