### ISSUE TITLE
Dart2JS crash with extension type variable double nested into type parameter bounds

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#54451]
Example:
```dart

void main() {
  1.st();
}

extension <T> on T {
  void st() {
    void g<Z extends void Function<Y extends T>()>() {}
    print(g.runtimeType); // Crashes compiler.
    // print(g is void Function()); // Also crashes compiler. Either line works.
  }
}
```
fails (DartPad, master branch, 3.3.0-238.0.dev), with the error
```
Internal Error: Runtime type information not available for type_variable_local(j:type_variable(_extension#0|st.T)) in (local(_extension#0|st#g)) for j:signature(_extension_0_st_g.:signature).
  void st() {
       ^
```
and a stack trace of       
```
The compiler crashed: Assertion failure: Runtime type information not available for type_variable_local(j:type_variable(_extension#0|st.T)) in (local(_extension#0|st#g)) for j:signature(_extension_0_st_g.:signature).
#0      failedAt (package:compiler/src/diagnostics/invariant.dart:39:3)
#1      LocalsHandler.readLocal (package:compiler/src/ssa/locals_handler.dart:346:11)
#2      TypeBuilder._buildEnvironmentForType (package:compiler/src/ssa/type_builder.dart:267:12)
#3      TypeBuilder.analyzeTypeArgumentNewRti (package:compiler/src/ssa/type_builder.dart:185:9)
#4      TypeBuilder.analyzeTypeArgument (package:compiler/src/ssa/type_builder.dart:169:12)
#5      KernelSsaGraphBuilder._computeTypeArgumentDefaultValue (package:compiler/src/ssa/builder.dart:6491:25)
#6      KernelSsaGraphBuilder._addFunctionTypeVariablesIfNeeded (package:compiler/src/ssa/builder.dart:695:17)
#7      KernelSsaGraphBuilder._openFunction (package:compiler/src/ssa/builder.dart:1825:5)
#8      KernelSsaGraphBuilder._buildMethodSignatureNewRti (package:compiler/src/ssa/builder.dart:1198:5)
#9      KernelSsaGraphBuilder.build.<anonymous closure> (package:compiler/src/ssa/builder.dart:515:11)
#10     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:154:15)
#11     KernelSsaGraphBuilder.build (package:compiler/src/ssa/builder.dart:427:21)
#12     KernelSsaBuilder.build.<anonymous closure> (package:compiler/src/js_model/js_strategy.dart:521:22)
#13     CompilerTask.measure (package:compiler/src/common/tasks.dart:66:51)
#14     KernelSsaBuilder.build (package:compiler/src/js_model/js_strategy.dart:503:18)
#15     SsaBuilderTask.build (package:compiler/src/ssa/ssa.dart:351:21)
#16     SsaFunctionCompiler.compile (package:compiler/src/ssa/ssa.dart:87:28)
#17     OnDemandCodegenResults.getCodegenResults (package:compiler/src/common/codegen.dart:409:30)
#18     JsBackendStrategy.generateCode (package:compiler/src/js_model/js_strategy.dart:327:43)
#19     KernelCodegenWorkItem.run (package:compiler/src/js_model/js_strategy.dart:462:29)
#20     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:747:70)
#21     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#22     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:747:32)
#23     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#24     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:745:28)
#25     DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:154:15)
#26     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:743:18)
#27     CodegenEnqueuer._forEach (package:compiler/src/js_backend/enqueuer.dart:249:12)
#28     CodegenEnqueuer.forEach (package:compiler/src/js_backend/enqueuer.dart:265:5)
#29     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:739:16)
#30     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#31     Compiler.emptyQueue (package:compiler/src/compiler.dart:738:14)
#32     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:762:7)
#33     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#34     Compiler.processQueue (package:compiler/src/compiler.dart:756:14)
#35     Compiler.runCodegenEnqueuer (package:compiler/src/compiler.dart:467:5)
#36     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:675:27)
<asynchronous suspension>
#37     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:315:7)
<asynchronous suspension>
#38     Compiler.runInternal (package:compiler/src/compiler.dart:314:5)
<asynchronous suspension>
#39     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:235:11)
<asynchronous suspension>
#40     compile.<anonymous closure> (package:compiler/compiler_api.dart:256:30)
<asynchronous suspension>
#41     compile.compilationDone (package:compiler/src/dart2js.dart:729:3)
<asynchronous suspension>
#42     main (package:compiler/src/dart2js.dart:1233:3)
<asynchronous suspension>
```

**Comment by biggs0125** [comment]
This also fails for a similar reason:
```
class A<T> {
  void st() {
    void g<Z extends void Function<Y extends T>()>() {}
    print(g.runtimeType); // Crashes compiler because A.T is not accessible.
  }
}

void main() {
  A<int>().st();
}
```

Dart2js is failing to analyze the bound for the type parameter on the local function `g`. So then the RTI builder is unable to find the necessary scope info to build the signature for `g`.

I'm working on a fix for this.

**Comment by biggs0125** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/343660
