### ISSUE TITLE
[vm_service] `HttpProfileRequestRef` parsing breaks with null check issue on `events` property

### ISSUE THREAD

**Issue by yahu1031** [dart-lang/sdk#54483]
During the `HttpProfile` response from the `onRecieve` listener, It breaks while we parse the `HttpProfile` data. Here is the data I'm trying to parse

<details><summary>Json socket Response</summary>

```json
{
  "jsonrpc": "2.0",
  "result": {
    "type": "HttpProfile",
    "timestamp": 661215288666,
    "requests": [
      {
        "type": "@HttpProfileRequest",
        "id": "3478858945988351483",
        "isolateId": "isolates/5308327655987107",
        "method": "POST",
        "uri": "https://hdfcsky.com/api/v2/user/login",
        "startTime": 656890833092,
        "endTime": 656894232739,
        "request": {
          "events": [ # Problem comes here
            {
              "timestamp": 656894229568,
              "event": "Connection established"
            },
            {
              "timestamp": 656894229769,
              "event": "Request sent"
            },
            {
              "timestamp": 656894643911,
              "event": "Waiting (TTFB)"
            },
            {
              "timestamp": 656894650065,
              "event": "Content Download"
            }
          ],
          "headers": {
            "user-agent": [
              "Dart/2.16 (dart:io)"
            ],
            "content-secstringty-policy": [
              "script-src 'self'"
            ],
            "accept-encoding": [
              "gzip"
            ],
            "content-length": [
              "43"
            ],
            "x-device-id": [
              "C7C5EE9B-8C67-4EF6-86A6-FE5DD8D1282E"
            ],
            "host": [
              "hdfcsky.com"
            ],
            "x-device-type": [
              "IOS"
            ],
            "content-type": [
              "application/json"
            ],
            "x-frame-options": [
              "Deny/sameorigin"
            ],
            "x-xss-protection": [
              "1; mode=block"
            ],
            "x-content-type-options": [
              "nosniff"
            ]
          },
          "connectionInfo": {
            "localPort": 64643,
            "remoteAddress": "52.66.157.54",
            "remotePort": 443
          },
          "contentLength": 43,
          "cookies": [],
          "followRedirects": true,
          "maxRedirects": 5,
          "method": "POST",
          "persistentConnection": true,
          "uri": "https://hdfcsky.com/api/v2/user/login",
          "filterKey": "HTTP/client"
        },
        "response": {
          "startTime": 656894649127,
          "headers": {
            "connection": [
              "keep-alive"
            ],
            "set-cookie": [
              "recaptcha=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT; max-age=0; HttpOnly",
              "referenceToken=A2z94ylBwlUGE9FQepos5OB1CF262j6KbnaYowd3qI2ZAAN8Aqzj3kQakt9592NNmML3CuQsVmeL0RdDgooloHSWz6gtUPvlTQuGw0K4JmWWgtcF6wDlIB5FMrdP7SQjMKdlFXWwTawTFAn2i7fvZTAABiibCepIsIFMbaLVSkjbEABPoPHYvbXPYRC3mTFOsOlXSVmd80bipOeI34iNxIwT4baUnFBFlVOT6R4Jv757YQOELisquFgIdJorPcAUULSTK3IXux6Htndb7wmH7kcC06EK5L4eZt39nIBnXRk8qVzax4PT2XZOuLMxs4YDZOPRmXXEBnk; path=/; secure; SameSite=Strict"
            ],
            "cache-control": [
              "max-age=0, private, must-revalidate"
            ],
            "date": [
              "Sun, 31 Dec 2023 18:13:10 GMT"
            ],
            "content-length": [
              "680"
            ],
            "strict-transport-security": [
              "max-age=31536000; includeSubDomains"
            ],
            "x-frame-options": [
              "SAMEORIGIN"
            ],
            "content-type": [
              "application/json; charset=utf-8"
            ],
            "x-xss-protection": [
              "1"
            ],
            "x-content-type-options": [
              "nosniff"
            ],
            "content-security-policy": [
              "frame-ancestors 'self' https://microapps.google.com/"
            ],
            "x-request-id": [
              "bf10a0bf7faa9e1693787233fb89630d"
            ]
          },
          "compressionState": "HttpClientResponseCompressionState.notCompressed",
          "connectionInfo": {
            "localPort": 64643,
            "remoteAddress": "52.66.157.54",
            "remotePort": 443
          },
          "contentLength": 680,
          "cookies": [
            "recaptcha=; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/; HttpOnly",
            "referenceToken=A2z94ylBwlUGE9FQepos5OB1CF262j6KbnaYowd3qI2ZAAN8Aqzj3kQakt9592NNmML3CuQsVmeL0RdDgooloHSWz6gtUPvlTQuGw0K4JmWWgtcF6wDlIB5FMrdP7SQjMKdlFXWwTawTFAn2i7fvZTAABiibCepIsIFMbaLVSkjbEABPoPHYvbXPYRC3mTFOsOlXSVmd80bipOeI34iNxIwT4baUnFBFlVOT6R4Jv757YQOELisquFgIdJorPcAUULSTK3IXux6Htndb7wmH7kcC06EK5L4eZt39nIBnXRk8qVzax4PT2XZOuLMxs4YDZOPRmXXEBnk; Path=/; Secure; SameSite=Strict"
          ],
          "isRedirect": false,
          "persistentConnection": true,
          "reasonPhrase": "OK",
          "redirects": [],
          "statusCode": 200,
          "endTime": 656894650023
        }
      }
    ]
  },
  "id": "2"
}
```

</details>

Here is the sample code (May be a little clumsy)

<details><summary>Sample Code</summary>

```dart
import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:vm_service/vm_service.dart';
import 'package:vm_service/vm_service_io.dart';

import '../../meta/widgets/loader.dart';
import '../consts/enum.dart';
import '../consts/global.dart';
import '../consts/theme.const.dart';

class NetworkLoggerScreen extends StatefulWidget {
  const NetworkLoggerScreen(this.vmServiceUri, {super.key});
  final String vmServiceUri;

  @override
  State<NetworkLoggerScreen> createState() => _NetworkLoggerScreenState();
}

class _NetworkLoggerScreenState extends State<NetworkLoggerScreen> {
  late FocusNode focusNode;
  late Future<VmService> vmService;
  DateTime timeStamp = DateTime.fromMillisecondsSinceEpoch(0);
  @override
  void initState() {
    focusNode = FocusNode();
    vmService =
        vmServiceConnectUri(widget.vmServiceUri).then((VmService value) async {
      VM vm = await value.getVM();
      List<IsolateRef>? isolates = vm.isolates;
      List<String?>? isolateIds =
          isolates?.map((IsolateRef i) => i.id).toList();
      Timer.periodic(const Duration(seconds: 1), (Timer timer) {
        unawaited(
            value.getHttpProfile(isolateIds!.first!, updatedSince: timeStamp));
        timeStamp = DateTime.now();
      });
      return value;
    });
    focusNode.requestFocus();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return KeyboardListener(
      onKeyEvent: (KeyEvent event) {
        if (event.logicalKey == LogicalKeyboardKey.escape) {
          navigatorKey.currentState?.maybePop();
        }
      },
      focusNode: focusNode,
      child: Scaffold(
        body: FutureBuilder<VmService>(
            future: vmService,
            builder: (_, __) {
              if (__.hasError) {
                return Center(
                  child: Text(
                    __.error.toString(),
                    style: Theme.of(context).textTheme.bodySmall?.copyWith(
                          color: AppTheme.errorColor,
                        ),
                  ),
                );
              }
              if (__.connectionState != ConnectionState.done ||
                  __.data == null) {
                return const Center(
                  child: Column(
                    children: <Widget>[
                      LoaderWidget(),
                      SizedBox(
                        height: 10,
                      ),
                      Text(
                        'Connecting to VM Service...',
                        style: TextStyle(
                          color: Colors.grey,
                          fontSize: 12,
                        ),
                      ),
                    ],
                  ),
                );
              }
              return SizedBox(
                width: double.infinity,
                child: SingleChildScrollView(
                  // controller: scrollController,
                  child: StreamBuilder<String>(
                      stream: __.data!.onReceive,
                      builder: (BuildContext context,
                          AsyncSnapshot<String> snapshot) {
                        if (snapshot.hasError) {
                          return Center(
                            child: Text(
                              snapshot.error.toString(),
                              style: Theme.of(context)
                                  .textTheme
                                  .bodySmall
                                  ?.copyWith(
                                    color: AppTheme.errorColor,
                                  ),
                            ),
                          );
                        }
                        if (snapshot.hasData && snapshot.data!.isNotEmpty) {
                          var jsonData = json.decode(snapshot.data!);

                          var type = jsonData['result']['type'];
                          bool isReqAvailable = jsonData['result']
                                      ['requests'] !=
                                  null &&
                              (jsonData['result']['requests'] as List<dynamic>)
                                  .isNotEmpty;
                          String id = type.toString() == 'HttpProfile'
                              ? (isReqAvailable
                                      ? jsonData['result']['requests'][0]['id']
                                      : '-1')
                                  .toString()
                              : jsonData['result']['number'].toString();
                          HttpProfile? httpData;
                          if (type.toString() == 'HttpProfile') {
                            httpData = HttpProfile.parse(jsonData['result']); // BREAKS HERE
                          }
                          return !(type == 'HttpProfile' &&
                                  isReqAvailable &&
                                  httpData != null)
                              ? const SizedBox.shrink()
                              : DataTable(
                                  border: TableBorder.all(
                                    color: Colors.transparent,
                                    width: 0,
                                    borderRadius: BorderRadius.circular(15),
                                  ),
                                  headingRowColor: MaterialStateProperty.all(
                                    Colors.grey.withOpacity(0.1),
                                  ),
                                  headingTextStyle: const TextStyle(
                                    fontWeight: FontWeight.bold,
                                  ),
                                  columns: <DataColumn>[
                                    DataColumn(
                                      label: Text(
                                        'Method',
                                        style: Theme.of(context)
                                            .textTheme
                                            .bodySmall,
                                      ),
                                    ),
                                    DataColumn(
                                      label: Text(
                                        'Uri',
                                        style: Theme.of(context)
                                            .textTheme
                                            .bodySmall,
                                      ),
                                    ),
                                    DataColumn(
                                      label: Text(
                                        'Status',
                                        style: Theme.of(context)
                                            .textTheme
                                            .bodySmall,
                                      ),
                                    ),
                                    DataColumn(
                                      label: Text(
                                        'Duration',
                                        style: Theme.of(context)
                                            .textTheme
                                            .bodySmall,
                                      ),
                                    ),
                                  ],
                                  showCheckboxColumn: false,
                                  columnSpacing: 0,
                                  dataRowMinHeight: 30,
                                  dataRowMaxHeight: 33,
                                  dividerThickness: 0,
                                  headingRowHeight: 40,
                                  rows: <DataRow>[
                                    DataRow(
                                      key: ValueKey<String>(id),
                                      selected: false,
                                      onSelectChanged:
                                          (bool? selected) async {},
                                      mouseCursor: MaterialStateProperty.all(
                                        MaterialStateMouseCursor.clickable,
                                      ),
                                      cells: <DataCell>[
                                        DataCell(
                                          Container(
                                            decoration: BoxDecoration(
                                              borderRadius:
                                                  BorderRadius.circular(5),
                                              color: AppTheme()
                                                  .getColor(jsonData['result']
                                                                      ['requests'][0]
                                                                  ['method'] ==
                                                              'POST' ||
                                                          jsonData['result']
                                                                      ['requests'][0]
                                                                  ['method'] ==
                                                              'PUT'
                                                      ? LogType.warning
                                                      : jsonData['result']
                                                                      ['requests'][0]
                                                                  ['method'] ==
                                                              'GET'
                                                          ? LogType.success
                                                          : jsonData['result']
                                                                          ['requests'][0]
                                                                      ['method'] ==
                                                                  'DELETE'
                                                              ? LogType.error
                                                              : LogType.info)
                                                  .withOpacity(.1),
                                              border: Border.all(
                                                color: AppTheme().getColor(jsonData['result']
                                                                    ['requests']
                                                                [0]['method'] ==
                                                            'POST' ||
                                                        jsonData['result']
                                                                    ['requests']
                                                                [0]['method'] ==
                                                            'PUT'
                                                    ? LogType.warning
                                                    : jsonData['result']
                                                                    ['requests']
                                                                [0]['method'] ==
                                                            'GET'
                                                        ? LogType.success
                                                        : jsonData['result']
                                                                        ['requests'][0]
                                                                    ['method'] ==
                                                                'DELETE'
                                                            ? LogType.error
                                                            : LogType.info),
                                                width: 1,
                                              ),
                                            ),
                                            child: Padding(
                                              padding:
                                                  const EdgeInsets.symmetric(
                                                      vertical: 2.0,
                                                      horizontal: 4.0),
                                              child: Text(
                                                jsonData['result']['requests']
                                                        [0]['method']
                                                    .toString()
                                                    .toUpperCase(),
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .bodySmall
                                                    ?.copyWith(
                                                      color: AppTheme().getColor(jsonData['result']
                                                                          ['requests'][0][
                                                                      'method'] ==
                                                                  'POST' ||
                                                              jsonData['result']
                                                                          ['requests'][0][
                                                                      'method'] ==
                                                                  'PUT'
                                                          ? LogType.warning
                                                          : jsonData['result']['requests'][0]
                                                                      ['method'] ==
                                                                  'GET'
                                                              ? LogType.success
                                                              : jsonData['result']['requests'][0]['method'] == 'DELETE'
                                                                  ? LogType.error
                                                                  : LogType.info),
                                                      fontWeight:
                                                          FontWeight.bold,
                                                    ),
                                              ),
                                            ),
                                          ),
                                        ),
                                        DataCell(
                                          Text(
                                            httpData.requests.first.uri
                                                .toString(),
                                            style: Theme.of(context)
                                                .textTheme
                                                .bodySmall,
                                          ),
                                        ),
                                        DataCell(
                                          Text(
                                            httpData.requests.first.response!
                                                .statusCode
                                                .toString(),
                                            style: Theme.of(context)
                                                .textTheme
                                                .bodySmall,
                                          ),
                                        ),
                                        DataCell(
                                          Text(
                                            '${(httpData.requests.first.startTime.millisecondsSinceEpoch - httpData.requests.first.endTime!.millisecondsSinceEpoch)} ms'
                                                .toString(),
                                            style: Theme.of(context)
                                                .textTheme
                                                .bodySmall,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ],
                                );
                        } else {
                          return const Center(
                            child: LoaderWidget(),
                          );
                        }
                      }),
                ),
              );
            }),
      ),
    );
  }
}
```

</details>

This is due to the expected json parsing is not happening with the package.

## More Information
Package: [vm_service](https://pub.dev/packages/vm_service/versions/14.0.0)
Version: 14.0.0
Dart version: 
```console
Dart SDK version: 3.3.0-273.0.dev (dev) (Fri Dec 29 04:03:30 2023 -0800) on "macos_arm64"
```
Flutter:
```console
Flutter 3.18.0-18.0.pre.47 • channel master • https://github.com/flutter/flutter.git
Framework • revision 3df4e735d5 (2 days ago) • 2023-12-29 14:07:39 -0500
Engine • revision 9e03a57cde
Tools • Dart 3.3.0 (build 3.3.0-273.0.dev) • DevTools 2.31.0-dev.0
```

**Comment by yahu1031** [comment]
JSON RPC response is incompatible with `vm_service` parsings.

**Comment by a-siva** [comment]
//cc @derekxu16 @brianquinlan @bkonyi

**Comment by brianquinlan** [comment]
@yahu1031 Could you provide a link to the actual code?

[HttpProfileRequestRef._fromJson](https://github.com/dart-lang/sdk/blob/2a07d71f145b19be25ae525994f1bdd321e55d92/pkg/vm_service/lib/src/dart_io_extensions.dart#L450) doesn't seem to have the code that you cited.

**Comment by yahu1031** [comment]
This is coming from package. I couldn't find it in this code 😞.

**Comment by bkonyi** [comment]
@yahu1031 can you try using `vm_service` 13.0.0 instead? The changes needed for 14.0.0 to work correctly haven't landed in the SDK, so that's probably why you're seeing errors.

**Comment by yahu1031** [comment]
```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'int' is not a subtype of type 'String'
#0      new HttpProfileRequestRef._fromJson (package:vm_service/src/dart_io_extensions.dart:351:12)
#1      new HttpProfileRequest._fromJson (package:vm_service/src/dart_io_extensions.dart:420:15)
#2      new HttpProfile._fromJson.<anonymous closure> (package:vm_service/src/dart_io_extensions.dart:326:44)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#7      new List.of (dart:core-patch/array_patch.dart:39:18)
#8      ListIterable.toList (dart:_internal/iterable.dart:224:7)
#9      new HttpProfile._fromJson (package:vm_service/src/dart_io_extensions.dart:327:14)
#10     HttpProfile.parse (package:vm_service/src/dart_io_extensions.dart:320:41)
#11     SocketLogger.listenHttpTraffic.<anonymous closure> (package:sky_logger/core/helpers/socket.dart:103:50)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#16     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#17     VmService._processMessageStr (package:vm_service/src/vm_service.dart:1830:18)
#18     VmService._processMessage (package:vm_service/src/vm_service.dart:1798:7)
#19     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#21     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#22     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

Version 13.0.0 gives this issue.

```dart
HttpProfileRequestRef._fromJson(Map<String, dynamic> json)
    : isolateId = json['isolateId'],
      id = json['id'], // Line 351
      method = json['method'],
      uri = Uri.parse(json['uri']),
      startTime = json['startTime'],
      endTime = json['endTime'],
      request = HttpProfileRequestData.parse(json['request']),
      response = HttpProfileResponseData.parse(json['response']);
```

**Comment by yahu1031** [comment]
`HttpProfileRequestRef` -> `id` is `String` but data comes as `int`.

**Comment by bkonyi** [comment]
Can you check which version of the dart:io service extension you're communicating with using [this API](https://pub.dev/documentation/vm_service/latest/vm_service/DartIOExtension/getDartIOVersion.html)? We changed the type of `id` from `int` to `String` over a year ago, so it sounds like you might be trying to communicate with an old application.

**Comment by yahu1031** [comment]
yes, you mean this right `2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "ios_x64"` dart tools version `2.9.2`

**Comment by bkonyi** [comment]
> yes, you mean this right `2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "ios_x64"` dart tools version `2.9.2`

Not quite what I meant, but it does help in this case. The application you're communicating with is using an older version of the protocol and isn't compatible with the newer `package:vm_service` (we changed `id` from `int` to `String` in [version 11.0.0](https://pub.dev/packages/vm_service/changelog#1100) to resolve a bug).

You should be calling [`VmService.getDartIOVersion()`](https://pub.dev/documentation/vm_service/latest/vm_service/DartIOExtension/getDartIOVersion.html) to get the version of the `dart:io` service extensions available in the target application to make sure they're compatible with the version of `package:vm_service` you're using. We don't currently have a constant to compare against ([I've filed an issue to add this](https://github.com/dart-lang/sdk/issues/54544)), but `package:vm_service` versions >= 11.0.0 support `dart:io` service extensions `3.x`.

**Comment by yahu1031** [comment]
Lemme check this and i think i have some other issue with the latest one too lemme check and update here

**Comment by yahu1031** [comment]
```console
#0      new HttpProfileRequestRef._fromJson (package:vm_service/src/dart_io_extensions.dart:356:32)
#1      new HttpProfileRequest._fromJson (package:vm_service/src/dart_io_extensions.dart:434:15)
#2      new HttpProfile._fromJson.<anonymous closure> (package:vm_service/src/dart_io_extensions.dart:327:44)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#5      CastIterator.moveNext (dart:_internal/cast.dart:61:30)
#6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#7      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#8      new List.of (dart:core-patch/array_patch.dart:39:18)
#9      Iterable.toList (dart:core/iterable.dart:497:7)
#10     new HttpProfile._fromJson (package:vm_service/src/dart_io_extensions.dart:329:14)
#11     HttpProfile.parse (package:vm_service/src/dart_io_extensions.dart:321:41)
#12     SocketLogger.listenHttpTraffic.<anonymous closure> (package:sky_logger/core/helpers/socket.dart:105:50)
#13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#16     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#17     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#18     VmService._processMessageStr (package:vm_service/src/vm_service.dart:1833:18)
#19     VmService._processMessage (package:vm_service/src/vm_service.dart:1798:7)
#20     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#22     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#23     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

`vm_service` - 14.0.0

@bkonyi

**Comment by bkonyi** [comment]
> `vm_service` - 14.0.0

`package:vm_service` `14.0.0` isn't compatible with the current SDK (it requires [this change to land](https://dart-review.googlesource.com/c/sdk/+/341120)), you need to use `>=11.0.0 <14.0.0` to interact with version `3.x` of the Dart IO service extensions.

**Comment by yahu1031** [comment]
But the application I'm trying yo do is a kind of network logger. And it should work irrespective to the dart/flutter versions. Is there any possible way?
