### ISSUE TITLE
RandomFileAccess.readInto(buffer) gives (OS Error: Invalid argument, errno = 22) for bytes larger than ~2GB

### ISSUE THREAD

**Issue by osaxma** [dart-lang/sdk#54566]
I am not sure if this is an OS limitation or a Dart limitation.

Take the following example:

```dart
void issue() {
  final file = File(largeFilePath).openSync();
  final size = file.lengthSync();
  final bytes = Uint8List(size);
  file.readIntoSync(bytes);
}

void noIssue() {
  final file = File(largeFilePath);
  final bytes = file.readAsBytesSync(); // no issue
  print(bytes.length); 
}
```

The `issue` function gives the following error for `size` above ~2GB:

```
Unhandled exception:
FileSystemException: readInto failed, path = 'largeFile.txt' (OS Error: Invalid argument, errno = 22)
#0      _RandomAccessFile.readIntoSync (dart:io/file_impl.dart:835:7)
.... 
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

I came across this issue as I am reading quite a large file into chunks and I found the error to go away when the chunks are less than around 2GB. But `File.readAsBytesSync()` doesn't have an issue reading an entire 12GB file at once (it takes around ~9 seconds on my machine). 

> Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_x64"

**Comment by brianquinlan** [comment]
[`File.readAsBytesSync` avoids the 2GB limit by reading smaller chunks](https://github.com/dart-lang/sdk/blob/9d3e923bf3c928bc3485aca9bba9c17207221e7a/sdk/lib/io/file_impl.dart#L543). See this [code comment](https://github.com/dart-lang/sdk/blob/9d3e923bf3c928bc3485aca9bba9c17207221e7a/sdk/lib/io/file_impl.dart#L10).

I think that `File.readAsBytes` ends up calling `File_ReadInto`, which does not have that protection.
