### ISSUE TITLE
[dart2wasm] co19/LibTest/async/Timer/Timer.periodic_A02_t01 failure

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#54598]
The following tests fail on dart2wasm (works well on all other platforms)
```
co19/LibTest/async/Timer/Timer.periodic_A02_t01
co19/LibTest/async/Timer/Timer_A02_t01
```
Failure log:
```
/=============================================================================================\
| co19/LibTest/async/Timer/Timer.periodic_A02_t01 broke (Pass -> RuntimeError, expected Pass) |
\=============================================================================================/

--- Command "dart2wasm" (took 03.000861s):
DART_CONFIGURATION=ReleaseX64 sdk/bin/dart2wasm_developer -Dtest_runner.configuration=dart2wasm-linux-d8 /b/s/w/ir/cache/builder/sdk/tests/co19/src/LibTest/async/Timer/Timer.periodic_A02_t01.dart /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/dart2wasm-linux-d8/tests_co19_src_LibTest_async_Timer_Timer.periodic_A02_t01/Timer.periodic_A02_t01.wasm

exit code:
0

--- Command "d8" (took 185ms):
DART_CONFIGURATION=ReleaseX64 TEST_COMPILATION_DIR=/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/dart2wasm-linux-d8/tests_co19_src_LibTest_async_Timer_Timer.periodic_A02_t01 /b/s/w/ir/cache/builder/sdk/third_party/d8/linux/x64/d8 --turboshaft-wasm --experimental-wasm-imported-strings pkg/dart2wasm/bin/run_wasm.js -- /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/dart2wasm-linux-d8/tests_co19_src_LibTest_async_Timer_Timer.periodic_A02_t01/Timer.periodic_A02_t01.mjs /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/dart2wasm-linux-d8/tests_co19_src_LibTest_async_Timer_Timer.periodic_A02_t01/Timer.periodic_A02_t01.wasm

exit code:
1

stdout:
unittest-suite-wait-for-done
Expect.isTrue(false) fails.
    at _fail (wasm://wasm/0008fb3e:wasm-function[714]:0x1afc6)
    at Expect.isTrue (wasm://wasm/0008fb3e:wasm-function[704]:0x1ae93)
    at check closure at file:///b/s/w/ir/cache/builder/sdk/tests/co19/src/LibTest/async/Timer/Timer.periodic_A02_t01.dart:30:56 (wasm://wasm/0008fb3e:wasm-function[689]:0x1a880)
    at closure wrapper at file:///b/s/w/ir/cache/builder/sdk/tests/co19/src/LibTest/async/Timer/Timer.periodic_A02_t01.dart:30:56 trampoline (wasm://wasm/0008fb3e:wasm-function[700]:0x1ae04)
    at _PeriodicTimer._schedule closure at org-dartlang-sdk:///lib/_internal/wasm/lib/timer_patch.dart:114:67 (wasm://wasm/0008fb3e:wasm-function[756]:0x1b7a4)
    at closure wrapper at org-dartlang-sdk:///lib/_internal/wasm/lib/timer_patch.dart:114:67 trampoline (wasm://wasm/0008fb3e:wasm-function[759]:0x1b83d)
    at _invokeCallback (wasm://wasm/0008fb3e:wasm-function[84]:0xce5f)
    at /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/dart2wasm-linux-d8/tests_co19_src_LibTest_async_Timer_Timer.periodic_A02_t01/Timer.periodic_A02_t01.mjs:177:50
pkg/dart2wasm/bin/run_wasm.js:297: [object WebAssembly.Exception]
  }
  ^

1 pending unhandled Promise rejection(s) detected.

stderr:
V8 is running with experimental features enabled. Stability and security will suffer.

--- Re-run this test:
python3 tools/test.py -n dart2wasm-linux-d8 co19/LibTest/async/Timer/Timer.periodic_A02_t01


/====================================================================================\
| co19/LibTest/async/Timer/Timer_A02_t01 broke (Pass -> RuntimeError, expected Pass) |
\====================================================================================/

--- Command "dart2wasm" (took 01.000591s):
DART_CONFIGURATION=ReleaseX64 sdk/bin/dart2wasm_developer -Dtest_runner.configuration=dart2wasm-linux-d8 /b/s/w/ir/tests/co19/src/LibTest/async/Timer/Timer_A02_t01.dart /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2wasm-linux-d8/tests_co19_src_LibTest_async_Timer_Timer_A02_t01/Timer_A02_t01.wasm

exit code:
0

--- Command "d8" (took 66ms):
DART_CONFIGURATION=ReleaseX64 TEST_COMPILATION_DIR=/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2wasm-linux-d8/tests_co19_src_LibTest_async_Timer_Timer_A02_t01 /b/s/w/ir/third_party/d8/linux/x64/d8 --turboshaft-wasm --experimental-wasm-imported-strings pkg/dart2wasm/bin/run_wasm.js -- /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2wasm-linux-d8/tests_co19_src_LibTest_async_Timer_Timer_A02_t01/Timer_A02_t01.mjs /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2wasm-linux-d8/tests_co19_src_LibTest_async_Timer_Timer_A02_t01/Timer_A02_t01.wasm

exit code:
1

stdout:
unittest-suite-wait-for-done
Expect.isTrue(false) fails.
    at _fail (wasm://wasm/0008e9be:wasm-function[711]:0x1ae9a)
    at Expect.isTrue (wasm://wasm/0008e9be:wasm-function[701]:0x1ad67)
    at check closure at file:///b/s/w/ir/tests/co19/src/LibTest/async/Timer/Timer_A02_t01.dart:28:47 (wasm://wasm/0008e9be:wasm-function[687]:0x1a7d2)
    at closure wrapper at file:///b/s/w/ir/tests/co19/src/LibTest/async/Timer/Timer_A02_t01.dart:28:47 trampoline (wasm://wasm/0008e9be:wasm-function[698]:0x1ad1f)
    at _OneShotTimer._schedule closure at org-dartlang-sdk:///lib/_internal/wasm/lib/timer_patch.dart:89:66 (wasm://wasm/0008e9be:wasm-function[752]:0x1b57d)
    at closure wrapper at org-dartlang-sdk:///lib/_internal/wasm/lib/timer_patch.dart:89:66 trampoline (wasm://wasm/0008e9be:wasm-function[754]:0x1b598)
    at _invokeCallback (wasm://wasm/0008e9be:wasm-function[82]:0xcdbd)
    at /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2wasm-linux-d8/tests_co19_src_LibTest_async_Timer_Timer_A02_t01/Timer_A02_t01.mjs:177:53
pkg/dart2wasm/bin/run_wasm.js:297: [object WebAssembly.Exception]
  }
  ^

1 pending unhandled Promise rejection(s) detected.

stderr:
V8 is running with experimental features enabled. Stability and security will suffer.

--- Re-run this test:
python3 tools/test.py -n dart2wasm-linux-d8 co19/LibTest/async/Timer/Timer_A02_t01
```

**Comment by osa1** [comment]
Fix in https://dart-review.googlesource.com/c/sdk/+/362260.
