### ISSUE TITLE
Failures on [VM/Runtime] - Do not try to resolve exec path for default namespace...Revert "AnalysisDriver. Produce results for all files of a library."

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#54592]
There are new test failures on [[VM/Runtime] - Do not try to resolve exec path for default namespace...Revert "AnalysisDriver. Produce results for all files of a library."](https://github.com/dart-lang/sdk/compare/0b26a96696ccb504e3ed90dabfff04eb17342705~...e518b8c3be4040e5ec1165619eb62e9a1ac90a37).

The tests
```
standalone/io/regress_54516_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-aot-android-release-arm64c
vm-aot-android-release-arm_x64
```

The newly added test fails on android:

```
--- Command "vm_compile_to_kernel" (took 01.000778s):
DART_CONFIGURATION=ReleaseAndroidARM64C /b/swarming/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseAndroidARM64C/vm_platform_strong.dill -o /b/swarming/w/ir/out/ReleaseAndroidARM64C/generated_compilations/vm-aot-android-release-arm64c/tests_standalone_io_regress_54516_test/out.dill /b/swarming/w/ir/tests/standalone/io/regress_54516_test.dart -Dtest_runner.configuration=vm-aot-android-release-arm64c --packages=/b/swarming/w/ir/.dart_tool/package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 02.000213s):
DART_CONFIGURATION=ReleaseAndroidARM64C out/ReleaseAndroidARM64C/clang_x64/gen_snapshot --snapshot-kind=app-aot-elf --elf=/b/swarming/w/ir/out/ReleaseAndroidARM64C/generated_compilations/vm-aot-android-release-arm64c/tests_standalone_io_regress_54516_test/out.aotsnapshot --loading-unit-manifest=/b/swarming/w/ir/out/ReleaseAndroidARM64C/generated_compilations/vm-aot-android-release-arm64c/tests_standalone_io_regress_54516_test/ignored.json --sound-null-safety -Dtest_runner.configuration=vm-aot-android-release-arm64c --ignore-unrecognized-flags --packages=/b/swarming/w/ir/.dart_tool/package_config.json /b/swarming/w/ir/out/ReleaseAndroidARM64C/generated_compilations/vm-aot-android-release-arm64c/tests_standalone_io_regress_54516_test/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 10ms):
DART_CONFIGURATION=ReleaseAndroidARM64C rm /b/swarming/w/ir/out/ReleaseAndroidARM64C/generated_compilations/vm-aot-android-release-arm64c/tests_standalone_io_regress_54516_test/out.dill

exit code:
0

--- Command "strip" (took 31ms):
DART_CONFIGURATION=ReleaseAndroidARM64C third_party/android_tools/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip --strip-unneeded /b/swarming/w/ir/out/ReleaseAndroidARM64C/generated_compilations/vm-aot-android-release-arm64c/tests_standalone_io_regress_54516_test/out.aotsnapshot

exit code:
0

--- Command "adb_precompilation" (took 543ms):
Steps to push precompiled runner and precompiled code to an attached device. Uses (and requires) adb.

exit code:
255

stdout:
Executing adb -s HT7BG1A04039 shell rm -Rf /data/local/tmp/precompilation-testing/test ; echo AdbShellExitCode:  $?
Stdout:
AdbShellExitCode: 0
ExitCode: 0
Time: 0:00:00.067889

Executing adb -s HT7BG1A04039 shell mkdir -p /data/local/tmp/precompilation-testing/test ; echo AdbShellExitCode:  $?
Stdout:
AdbShellExitCode: 0
ExitCode: 0
Time: 0:00:00.089719

Executing Skipped cached push
ExitCode: 0
Time: 0:00:00.000041

Executing Skipped cached push
ExitCode: 0
Time: 0:00:00.000006

Executing Skipped cached push
ExitCode: 0
Time: 0:00:00.000002

Executing Skipped cached push
ExitCode: 0
Time: 0:00:00.000004

Executing adb -s HT7BG1A04039 shell chmod 777 /data/local/tmp/precompilation-testing/dart_precompiled_runtime /data/local/tmp/precompilation-testing/process_test /data/local/tmp/precompilation-testing/abstract_socket_test ; echo AdbShellExitCode:  $?
Stdout:
AdbShellExitCode: 0
ExitCode: 0
Time: 0:00:00.065840

Executing adb -s HT7BG1A04039 push /b/swarming/w/ir/out/ReleaseAndroidARM64C/generated_compilations/vm-aot-android-release-arm64c/tests_standalone_io_regress_54516_test/ignored.json /data/local/tmp/precompilation-testing/test/ignored.json
Stdout:
/b/swarming/w/ir/out/ReleaseAndroidARM64C/generated_compilations/vm-aot-android-release-arm64c/tests_standalone_io_regress_54516_test/ignored.json: 1 file pushed, 0 skipped. 5.9 MB/s (625 bytes in 0.000s)
ExitCode: 0
Time: 0:00:00.031807

Executing adb -s HT7BG1A04039 push /b/swarming/w/ir/out/ReleaseAndroidARM64C/generated_compilations/vm-aot-android-release-arm64c/tests_standalone_io_regress_54516_test/out.aotsnapshot /data/local/tmp/precompilation-testing/test/out.aotsnapshot
Stdout:
/b/swarming/w/ir/out/ReleaseAndroidARM64C/generated_compilations/vm-aot-android-release-arm64c/tests_standalone_io_regress_54516_test/out.aotsnapshot: 1 file pushed, 0 skipped. 1902.5 MB/s (1573808 bytes in 0.001s)
ExitCode: 0
Time: 0:00:00.089290

Executing adb -s HT7BG1A04039 shell export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/data/local/tmp/precompilation-testing/test;export TEST_COMPILATION_DIR=/data/local/tmp/precompilation-testing/test;/data/local/tmp/precompilation-testing/dart_precompiled_runtime --android-log-to-stderr --sound-null-safety -Dtest_runner.configuration=vm-aot-android-release-arm64c --ignore-unrecognized-flags --packages=/b/swarming/w/ir/.dart_tool/package_config.json /data/local/tmp/precompilation-testing/test/out.aotsnapshot ; echo AdbShellExitCode:  $?
Stdout:
AdbShellExitCode: 255
Stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:721)
#1      Expect.isTrue (package:expect/expect.dart:152)
#2      main (file:///b/swarming/w/ir/tests/standalone/io/regress_54516_test.dart:18)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
ExitCode: 255
Time: 0:00:00.103937

--- Re-run this test:
python3 tools/test.py -n vm-aot-android-release-arm64c standalone/io/regress_54516_test
```

Maybe the test should use `// OtherResources=` to make sure extra file is copied.

/cc @a-siva

**Comment by a-siva** [comment]
Missed adding OtherResources in the test, this CL should take care of it https://dart-review.googlesource.com/c/sdk/+/345861

**Comment by a-siva** [comment]
Above CL has landed closing issue.
