### ISSUE TITLE
NativeCallable binding dart callback function cannot be invoked in JavaScriptCore

### ISSUE THREAD

**Issue by ShuttleSpace** [dart-lang/sdk#54599]
This tracker is for issues related to:
* Dart native and web compilers

### environment

xcode Version 15.1 (15C65)
- Dart 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_x64"
- on macos / Version 14.1.2 (Build 23B92)
- locale is zh-Hans-CN

### problem

I want binding a dart function to JavaScriptCore as a JSFunction, it can be invoked with js or dart. it cannot be invoked when i use NativeCallable wrapper a dart function. but using dart function address with Pointer.fromFunction directly, that's ok.

here is repoducible code.
https://github.com/ShuttleSpace/nc/blob/main/test/nc_test.dart

```dart
typedef JSObjectCallAsFunctionCallback_ = JSValueRef Function(
    JSContextRef ctx,
    JSObjectRef function,
    JSObjectRef thisObject,
    Size argumentCount,
    Pointer<JSValueRef> arguments,
    Pointer<JSValueRef> exception);
typedef JSObjectCallAsFunctionCallback = JSValue Function(
    JSContext ctx,
    JSObject function,
    JSObject thisObject,
    int argumentCount,
    List<JSValue> arguments,
    JSException exception);

class JSObject {
	  JSObject.makeFunctionWithCallback(this.context,
	      {String? name, JSObjectCallAsFunctionCallback? callAsFunction}) {
	    _callAsFunctionCallbackNC = NativeCallable.isolateLocal((JSContextRef ctx1,
	        JSObjectRef function,
	        JSObjectRef thiz,
	        int argc,
	        Pointer<JSValueRef> argv,
	        Pointer<JSValueRef> exception) {
	      final ctxw = JSContext(ctx1);
	      final jsfunc = JSObject(ctxw, function);
	      final jsthiz = JSObject(ctxw, thiz);
	      final argvlist = <JSValue>[];
	
	      for (int i = 0; i < argc; i++) {
	        argvlist[i] = JSValue(ctxw, argv[i]);
	      }
	      final jsexc = JSException(ctxw, exception);
	      try {
	        print(
	            '[JSObject.makeFunctionWithCallback] NativeCallable.isolateLocal.');
	        return callAsFunction
	                ?.call(ctxw, jsfunc, jsthiz, argc, argvlist, jsexc)
	                .ref ??
	            nullptr;
	      } finally {
	        jsfunc.value.unprotect();
	        jsthiz.value.unprotect();
	        for (var e in argvlist) {
	          e.unprotect();
	        }
	        jsexc.free();
	      }
	    });
	    final JSString? jsname = name != null ? JSString.fromString(name) : null;
	    try {
	      _ref = JSObjectMakeFunctionWithCallback(context.ref,
	          jsname?.ref ?? nullptr, _callAsFunctionCallbackNC!.nativeFunction);
	    } finally {
	      jsname?.free();
	    }
	  }

}

```

btw, is there a way or tool to debug dart ffi. thanks!!!

**Comment by mraleph** [comment]
> I want binding a dart function to JavaScriptCore as a JSFunction, it can be invoked with js or dart. it cannot be invoked when i use NativeCallable wrapper a dart function.

What does "it cannot be invoked"? What happens? 

When asking questions (or filing issues) please provide as much information as possible. Saying "it cannot be invoked" is non-informative. Is it crashing? Is it printing an error? Is nothing happening? etc. Providing information when asking is the key to getting good answers. See [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

/cc @dcharkes

**Comment by navaronbracke** [comment]
The `NativeCallable` class is only available for foreign function interfaces through `dart:ffi`. The `dart:ffi` library is for native platforms, which excludes web. If you want a Dart function that is callable from JavaScript, consider doing interop with `JSFunction` from `dart:js_interop` instead.

**Comment by mkustermann** [comment]
@navaronbracke I think this library is actually running in Dart VM and loading JavaScriptCore from a shared library, see https://github.com/ShuttleSpace/nc/blob/main/lib/src/binding.dart#L50C75-L50C75

**Comment by navaronbracke** [comment]
Ah, pardon me. I wasn't aware that this was running in the VM. In retrospect I should have seen it from the use of the Pointer type.

**Comment by dcharkes** [comment]
> but with NativeCallable, it doesn't.
> 
> ```dart
>     test('invoke with NativeCallable wrapper', () {
>       final gctx = JSGlobalContext.create();
>       final consoleLogJSV = JSObject.makeFunctionWithCallback(gctx,
>           name: 'console.log', callAsFunction: _console_log);
>       final ret = consoleLogJSV.callAsFunction(arguments: [
>         JSValue.makeString(gctx, 'test...'),
>         JSValue.makeBoolean(gctx, false),
>         JSValue.makeNumber(gctx, 100),
>         JSValue.makeNull(gctx),
>         JSValue.makeUndefined(gctx)
>       ]);
>       expect(ret.string, '1');
>       consoleLogJSV.free();
>       gctx.free();
>     });
> ```

I don't see a `NativeCallable` in this code snippet. Could you please provide a complete minimal example?

**Comment by mkustermann** [comment]
> I don't see a NativeCallable in this code snippet. Could you please provide a complete minimal example?

@dcharkes It's in the `makeFunctionWithCallback`, see https://github.com/ShuttleSpace/nc/blob/main/lib/src/wrapper/JSObject.dart#L19

**Comment by ShuttleSpace** [comment]
> @ShuttleSpace Why are you using `makeFunctionWithCallback` in one place but `makeFunctionWithCallbackRaw` in the other? Using `makeFunctionWithCallbackRaw` with `NativeCallable` works.

I want to encapsulate the dart callback function into a JSObject object. Does this mean NativeCallable can only be used with global variables?

**Comment by dcharkes** [comment]
> Does this mean NativeCallable can only be used with global variables?

No, closures should be fine.

```dart
  test('invoke with NativeCallable', () {
    final gctx = JSGlobalContext.create();
    final consoleLogJSV = JSObject.makeFunctionWithCallbackNonRaw(gctx,
        name: 'console.log', callAsFunction: _console_log_raw);
    final ret = consoleLogJSV.callAsFunction(arguments: [
      JSValue.makeString(gctx, 'test...'),
      JSValue.makeBoolean(gctx, false),
      JSValue.makeNumber(gctx, 100),
      JSValue.makeNull(gctx),
      JSValue.makeUndefined(gctx)
    ]);
    expect(ret.string, '1');
    consoleLogJSV.free();
    gctx.free();
  });
```

```dart
  factory JSObject.makeFunctionWithCallbackNonRaw(
    JSContext ctx, {
    String? name,
    JSValueRef Function(JSContextRef ctx, JSObjectRef func, JSObjectRef thiz,
            int argc, Pointer<JSValueRef> argv, Pointer<JSValueRef> ex)?
        callAsFunction,
  }) {
    final JSString? jsname = name != null ? JSString.fromString(name) : null;
    final nativeCallable =
        NativeCallable<JSObjectCallAsFunctionCallback_>.isolateLocal((
      JSContextRef ctx,
      JSObjectRef func,
      JSObjectRef thiz,
      int argc,
      Pointer<JSValueRef> argv,
      Pointer<JSValueRef> ex,
    ) {
      print('Hello from closure in callback.');
      return callAsFunction!(
        ctx,
        func,
        thiz,
        argc,
        argv,
        ex,
      );
    });
    final cb = nativeCallable.nativeFunction;
    return JSObject(ctx,
        JSObjectMakeFunctionWithCallback(ctx.ref, jsname?.ref ?? nullptr, cb));
  }
```

The error is somewhere else in your code, you're swallowing an exception in your callback

```dart
  JSObject.makeFunctionWithCallback(this.context,
      {String? name, JSObjectCallAsFunctionCallback? callAsFunction}) {
    _callAsFunctionCallbackNC = NativeCallable.isolateLocal((JSContextRef ctx1,
        JSObjectRef function,
        JSObjectRef thiz,
        int argc,
        Pointer<JSValueRef> argv,
        Pointer<JSValueRef> exception) {
      try {
        final ctxw = JSContext(ctx1);
        final jsfunc = JSObject(ctxw, function);
        final jsthiz = JSObject(ctxw, thiz);
        final argvlist = <JSValue>[];

        for (int i = 0; i < argc; i++) {
          argvlist[i] = JSValue(ctxw, argv[i]);
        }
        final jsexc = JSException(ctxw, exception);
        try {
          print(
              '[JSObject.makeFunctionWithCallback] NativeCallable.isolateLocal.');
          return callAsFunction
                  ?.call(ctxw, jsfunc, jsthiz, argc, argvlist, jsexc)
                  .ref ??
              nullptr;
        } finally {
          jsfunc.value.unprotect();
          jsthiz.value.unprotect();
          for (var e in argvlist) {
            e.unprotect();
          }
          jsexc.free();
        }
      } catch (e, st) {
        print('Caught exception: $e\n$st}');
      }
    });
    final JSString? jsname = name != null ? JSString.fromString(name) : null;
    try {
      _ref = JSObjectMakeFunctionWithCallback(context.ref,
          jsname?.ref ?? nullptr, _callAsFunctionCallbackNC!.nativeFunction);
    } finally {
      jsname?.free();
    }
  }
```

```
Caught exception: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List._setIndexed (dart:core-patch/growable_array.dart:273:49)
#1      List.[]= (dart:core-patch/growable_array.dart:268:5)
#2      new JSObject.makeFunctionWithCallback.<anonymous closure> (package:nc/src/wrapper/JSObject.dart:32:19)
#3      _FfiIsolateLocalCallback (dart:ffi)
#4      JSObjectCallAsFunction.#ffiClosure3 (package:nc/src/binding.dart)
#5      JSObject.callAsFunction (package:nc/src/wrapper/JSObject.dart:116:57)
#6      main.<anonymous closure>.<anonymous closure> (file:///Users/dacoharkes/src/ShuttleSpace/nc/test/nc_test.dart:23:33)
#7      Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:19)
<asynchronous suspension>
#8      Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:213:7)
<asynchronous suspension>
#9      Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:258:9)
<asynchronous suspension>
```

This can be fixed by

```
          argvlist.add(JSValue(ctxw, argv[i]));
```

Which then leads to some more errors with your resource management:

```
dacoharkes-macbookpro2:nc dacoharkes$ dart test/nc_test.dart
00:00 +0: A group of tests invoke with NativeCallable wrapper

[JSObject.makeFunctionWithCallback] NativeCallable.isolateLocal.

【dart】_console_log: console.log, argc: 5

Instance of 'JSValue'

Instance of 'JSValue'

Instance of 'JSValue'

Instance of 'JSValue'

Instance of 'JSValue'

dart(5247,0x16e59f000) malloc: *** error for object 0x16e59d5d8: pointer being freed was not allocated
dart(5247,0x16e59f000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by dcharkes** [comment]
These are issues with your code, not the `dart:ffi` implementation. I'll go ahead and close the issue.

Happy coding!

**Comment by ShuttleSpace** [comment]
> These are issues with your code, not the `dart:ffi` implementation. I'll go ahead and close the issue.
> 
> Happy coding!

Thank you very much for your patient answer🥰
