### ISSUE TITLE
dart.io: File.openwrite does not throw when file cannot be written

### ISSUE THREAD

**Issue by jakobleck** [dart-lang/sdk#54707]
Similar to #53904. Execute the below code once, then do a `chmod 444 forbidden.txt` and run it again.
```
import 'dart:io';

void main() async {
  String fileName = "forbidden.txt";
  print("a");
  File file = File(fileName);
  print("b");
  final sink = file.openWrite();
  print("c");
  sink.write("object");
  print("d");
  await sink.flush();
  print("e");
  await sink.close();
  print("f");
}
```
Output:
```
a
b
c
d
Unhandled exception:
PathAccessException: Cannot open file, path = 'forbidden.txt' (OS Error: Permission denied, errno = 13)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
<asynchronous suspension>
```
I.e. the `openWrite` does not fail even though the file cannot be written, the exception is thrown on the `flush` (or on `close` if you don't `flush`).

Perhaps this should be documented, like in #53904. 

If you do the same in Java (code below), the `Exception` is thrown when instantiating the `FileWriter`. 
```
import java.io.File;
import java.io.FileWriter;

public class Main {

    public static void main(String[] args) {
        try {
            File file = new File("forbidden.txt");
            FileWriter fileWriter = new FileWriter(file);
            fileWriter.write("object");
            fileWriter.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by a-siva** [comment]
//cc @brianquinlan

**Comment by brianquinlan** [comment]
I can add a similar note to `openWrite`.

**Comment by a-siva** [comment]
The documentation change has been done, closing issue,
