### ISSUE TITLE
Memory leaks after "Roll boringssl to d24a38200fef19150eef00cad35b138936c08767"

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#54765]
There are new test failures on [Roll boringssl to d24a38200fef19150eef00cad35b138936c08767.](https://github.com/dart-lang/sdk/compare/362e5784b5e0912e30932014913c6db530ba0cea~...f76ec294ca90dd13867d56f668d7f29ab83f3878).

The tests
```
standalone/io/secure_server_client_certificate_test Crash (expected Pass)
standalone/io/secure_socket_error_test Crash (expected Pass)
standalone/io/secure_socket_test/0 Crash (expected Pass)
standalone/io/secure_socket_test/1 Crash (expected Pass)
standalone/io/secure_socket_test/2 Crash (expected Pass)
standalone/io/secure_socket_test/3 Crash (expected Pass)
```
are failing on configurations
```
vm-aot-asan-linux-release-x64
vm-asan-linux-release-x64
```

it reports memory leaks:
```
Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x564c84970e5f in malloc ../../../../../../llvm-llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:68:3
    #1 0x564c84b0454f in OPENSSL_malloc out/ReleaseASANX64/../../third_party/boringssl/src/crypto/mem.c:254:15
    #2 0x564c849ef91a in dart::bin::GetPrivateKeyPKCS12(bio_st*, char const*) out/ReleaseASANX64/../../runtime/bin/security_context.cc:400:16
    #3 0x564c849ef91a in dart::bin::GetPrivateKey(bio_st*, char const*) out/ReleaseASANX64/../../runtime/bin/security_context.cc:425:13
    #4 0x564c849ef91a in dart::bin::Builtin_SecurityContext_UsePrivateKeyBytes(_Dart_NativeArguments*) out/ReleaseASANX64/../../runtime/bin/security_context.cc:806:11
    #5 0x564c84d49659 in dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) out/ReleaseASANX64/../../runtime/vm/native_entry.cc:219:7
    #6 0x7f73eb841962  (<unknown module>)
```

**Comment by mkustermann** [comment]
@brianquinlan could you have a look?
