### ISSUE TITLE
Assertion failure in `_WhyNotPromotedVisitor` caused by rolling `package_config`

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#54777]
https://dart-review.googlesource.com/c/sdk/+/349401 (patchset 1) attempts to roll `third_party/pkg/package_config` to a new version.

The change causes an assertion failure when running test `pkg/front_end/test/compile_dart2js_with_no_sdk_test` on configuration `cfe-unittest-asserts-release-linux`. The stacktrace looks like this:

```
Crash when compiling file:///b/s/w/ir/third_party/pkg/package_config/lib/src/package_config_json.dart at character offset 8376:
'package:front_end/src/fasta/type_inference/inference_visitor_base.dart': Failed assertion: line 4515 pos 14: 'messages.isNotEmpty': is not true.

#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      _WhyNotPromotedVisitor.visitPropertyNotPromotedForNonInherentReason (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:4515:14)
#3      PropertyNotPromotedForNonInherentReason.accept (package:_fe_analyzer_shared/src/flow_analysis/flow_analysis.dart:3614:15)
#4      InferenceVisitorBase.getWhyNotPromotedContext (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:274:25)
#5      InferenceVisitorBase._inferInstanceMethodInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:2800:39)
#6      InferenceVisitorBase.inferMethodInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:3255:20)
#7      InferenceVisitorImpl.visitMethodInvocation (package:front_end/src/fasta/type_inference/inference_visitor.dart:4907:12)
#8      MethodInvocation.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:2880:20)
#9      InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:271:27)
#10     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:305:40)
#11     InferenceVisitorImpl.inferMapEntry (package:front_end/src/fasta/type_inference/inference_visitor.dart:4608:11)
#12     InferenceVisitorImpl._inferIfMapEntry (package:front_end/src/fasta/type_inference/inference_visitor.dart:4192:28)
#13     InferenceVisitorImpl.inferMapEntry (package:front_end/src/fasta/type_inference/inference_visitor.dart:4553:14)
#14     InferenceVisitorImpl.visitMapLiteral (package:front_end/src/fasta/type_inference/inference_visitor.dart:4763:31)
#15     MapLiteral.accept1 (package:kernel/ast.dart:8323:9)
#16     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:273:27)
#17     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:305:40)
#18     InferenceVisitorImpl.inferElement (package:front_end/src/fasta/type_inference/inference_visitor.dart:2639:11)
#19     InferenceVisitorImpl._inferForInElement (package:front_end/src/fasta/type_inference/inference_visitor.dart:2608:44)
#20     InferenceVisitorImpl.inferElement (package:front_end/src/fasta/type_inference/inference_visitor.dart:2635:14)
#21     InferenceVisitorImpl.visitListLiteral (package:front_end/src/fasta/type_inference/inference_visitor.dart:2735:42)
#22     ListLiteral.accept1 (package:kernel/ast.dart:8195:9)
#23     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:273:27)
#24     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:305:40)
#25     InferenceVisitorImpl.inferMapEntry (package:front_end/src/fasta/type_inference/inference_visitor.dart:4608:11)
#26     InferenceVisitorImpl.visitMapLiteral (package:front_end/src/fasta/type_inference/inference_visitor.dart:4763:31)
#27     MapLiteral.accept1 (package:kernel/ast.dart:8323:9)
#28     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:273:27)
#29     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:305:40)
#30     InferenceVisitorImpl.visitReturnStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:8013:11)
#31     ReturnStatement.accept (package:kernel/ast.dart:10190:43)
#32     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:256:26)
#33     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:199:17)
#34     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1301:43)
#35     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1244:19)
#36     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:364:5)
#37     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3855:14)
#38     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3595:14)
#39     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:615:14)
#40     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:410:15)
#41     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1252:12)
<asynchronous suspension>
#42     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:673:7)
<asynchronous suspension>
#43     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:616:7)
<asynchronous suspension>
#44     withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#45     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:596:12)
<asynchronous suspension>
#46     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:371:23)
<asynchronous suspension>
#47     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139:3)
<asynchronous suspension>
#48     TestIncrementalCompiler.computeDelta (file:///b/s/w/ir/pkg/front_end/test/incremental_suite.dart:2710:40)
<asynchronous suspension>
#49     main (file:///b/s/w/ir/pkg/front_end/test/compile_dart2js_with_no_sdk_test.dart:21:3)
<asynchronous suspension>
```

Thanks to @devoncarew for bringing this problem to my attention. I've found the problem and I'm working on a fix.

**Comment by stereotype441** [comment]
The problem is that the front end's implementation of `FlowAnalysisOperations.whyPropertyIsNotPromotable` assumes that it will passed a property that is defined in the current library. If it's passed a property that's defined in some other library (which might happen if the user is trying to promote a public field), it will return `null`. But that's incorrect; it should only return `null` if the reason for non-promotability is because of a conflict with some other declaration in the same library. This triggers `_WhyNotPromotedVisitor.visitPropertyNotPromotedForNonInherentReason` to get called, and it tries to find the conflicting declaration(s) to report them to the user. But there are no conflicting declarations, because the sole reason for non-promotabilityis because the field is public! An assertion in `_WhyNotPromotedVisitor.visitPropertyNotPromotedForNonInherentReason` notices that no conflicting declarations were found.

Front end assertions are only enabled during certain SDK tests. So the assertion failure is not a problem for the user; the behavior the user sees is that there is simply no "why not promoted" message.

I should have a fix out for review shortly.
