### ISSUE TITLE
Dart on web does not throw if casting `null` to `Never` when using generics

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#54793]
Consider the following code:

```dart
void main() {
  print(fn<Never>());
}

T fn<T>() {
  return null as T;
}
```

When running in a terminal, the code throw:

```
Unhandled exception:
type 'Null' is not a subtype of type 'Never' in type cast
#0      fn (file:///Users/remirousselet/dev/rrousselGit/riverpod/packages/riverpod/foo.dart:6:15)
#1      main (file:///Users/remirousselet/dev/rrousselGit/riverpod/packages/riverpod/foo.dart:2:9)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

But surprisingly, when running the same code on Dartpad, the code runs

<img width="482" alt="Screenshot 2024-02-01 at 10 53 20" src="https://github.com/dart-lang/sdk/assets/20165741/fec8750c-79ab-4b72-9498-dfde7cfae6ab">

**Comment by eernstg** [comment]
Thanks for the heads-up! However, the missing run-time error can only be observed using the 'stable' channel, both the 'beta' channel and the 'master' channel are throwing an exception as expected.

> Uncaught Error: TypeError: null: type 'JSNull' is not a subtype of type 'Never'

So, apparently, the bug has been resolved already, and we are just waiting for the fix to come through the pipeline.

**Comment by rrousselGit** [comment]
No worries! I guess this can be closed then :)
