### ISSUE TITLE
app crashes once staps on breakpoints

### ISSUE THREAD

**Issue by mnts** [dart-lang/sdk#54838]
Dart SDK version: 3.3.0-279.3.beta (beta) (Wed Jan 31 15:24:56 2024 +0000) on "linux_x64"
and same happens on stable on - dart 3.26
using VS Code

Unhandled exception:
RangeError (offset): Invalid value: Not in inclusive range 0..4813: 5611
#0      RangeError.checkValueInInterval (dart:core/errors.dart:312)
errors.dart:312
#1      Source.getLocation (package:kernel/ast.dart:14964)
#2      getLocation (package:front_end/src/fasta/messages.dart:17)
#3      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:212)
#4      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:237)
#5      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67)
#6      DillLoader._addMessage (package:front_end/src/fasta/dill/dill_loader.dart:250)
#7      DillLoader.addProblem (package:front_end/src/fasta/dill/dill_loader.dart:208)
#8      LibraryBuilderImpl.addProblem (package:front_end/src/fasta/builder/library_builder.dart:288)
#9      DeclarationBuilderImpl.addProblem (package:front_end/src/fasta/builder/declaration_builder.dart:100)
#10     MembersNodeBuilder.reportInheritanceConflict (package:front_end/src/fasta/kernel/hierarchy/members_node.dart:89)
#11     _Tuple.sanitize (package:front_end/src/fasta/kernel/hierarchy/members_node.dart:1700)
#12     ClassMembersNodeBuilder.build.computeClassInterfaceMember (package:front_end/src/fasta/kernel/hierarchy/members_node.dart:953)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
compact_hash.dart:633
#14     ClassMembersNodeBuilder.build (package:front_end/src/fasta/kernel/hierarchy/members_node.dart:1034)
#15     ClassMembersBuilder.getNodeFromClassBuilder (package:front_end/src/fasta/kernel/hierarchy/members_builder.dart:125)
#16     ClassMembersNodeBuilder.build (package:front_end/src/fasta/kernel/hierarchy/members_node.dart:709)
#17     ClassMembersBuilder.getNodeFromClassBuilder (package:front_end/src/fasta/kernel/hierarchy/members_builder.dart:125)
#18     ClassMembersBuilder.getNodeFromClass (package:front_end/src/fasta/kernel/hierarchy/members_builder.dart:145)
#19     ClassMembersBuilder.getInterfaceMember (package:front_end/src/fasta/kernel/hierarchy/members_builder.dart:159)
#20     InferenceVisitorBase._getInterfaceMember (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:3796)
#21     _ObjectAccessDescriptor._findNonExtensionTargetInternal (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:4790)
#22     _ObjectAccessDescriptor.findNonExtensionTarget (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:4703)
#23     InferenceVisitorBase.findInterfaceMember (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1292)
#24     InferenceVisitorImpl._computePropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:6678)
#25     InferenceVisitorImpl.visitPropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:7686)
#26     PropertyGet.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:2917)
#27     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:271)
#28     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:305)
#29     InferenceVisitorImpl.visitReturnStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:7913)
#30     ReturnStatement.accept (package:kernel/ast.dart:10159)
#31     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:256)
#32     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:199)
#33     BodyBuilder.parseSingleExpression (package:front_end/src/fasta/kernel/body_builder.dart:1824)
#34     SourceLoader.buildExpression (package:front_end/src/fasta/source/source_loader.dart:1332)
<asynchronous suspension>
#35     IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:2045)
#36     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#37     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:1818)
<asynchronous suspension>
<asynchronous suspension>
#38     FrontendCompiler.compileExpression (package:frontend_server/frontend_server.dart:990)
<asynchronous suspension>
#39     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1441)
<asynchronous suspension>
the Dart compiler exited unexpectedly.

**Comment by devoncarew** [comment]
I'm not sure where best to triage this but starting with the front-end given the stack trace. cc @johnniwinther
