### ISSUE TITLE
UnimplementedError while applying class level macro to sealed extension.

### ISSUE THREAD

**Issue by Solido** [dart-lang/sdk#55036]
Applying a Class level macro to a sealed extension lead to an `UnimplementedError: (SuperFormalParameterImpl)`

```dart
macro class BaseAppliedMacro implements ClassDefinitionMacro, ClassDeclarationsMacro {...}

sealed class Base {...}

@BaseAppliedMacro
final class BaseImpl1 extends Base {...}

```

```
UnimplementedError: (SuperFormalParameterImpl) super.description #0      DeclarationBuilderFromNode._formalParameterDeclaration (package:analyzer/src/summary2/macro_declarations.dart:1721:9)
dart-lang/language#1      DeclarationBuilderFromNode._executableFormalParameters (package:analyzer/src/summary2/macro_declarations.dart:1663:31)
dart-lang/language#2      DeclarationBuilderFromNode.constructorDeclaration (package:analyzer/src/summary2/macro_declarations.dart:1235:9)
dart-lang/language#3      DeclarationBuilderFromNode.declarationOf (package:analyzer/src/summary2/macro_declarations.dart:1263:16)
dart-lang/language#4      DeclarationBuilder.declarationOfElement (package:analyzer/src/summary2/macro_declarations.dart:165:23)
dart-lang/language#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
dart-lang/language#6      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
dart-lang/language#7      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:882:20)
dart-lang/language#8      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
dart-lang/language#9      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
dart-lang/language#10     new List.of (dart:core-patch/array_patch.dart:39:18)
dart-lang/language#11     Iterable.toList (dart:core/iterable.dart:497:7)
dart-lang/language#12     _DeclarationPhaseIntrospector.constructorsOf (package:analyzer/src/summary2/macro_application.dart:1019:12)
<asynchronous suspension>
dart-lang/language#13     new ExternalMacroExecutorBase.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:_fe_analyzer_shared/src/macros/executor/executor_base.dart:159:47)
<asynchronous suspension>

```

**Comment by jakemac53** [comment]
Thanks for filing an issue!

It is expected at this time that macros will throw some unimplemented errors. I am going to close this, but cc @scheglov who owns the analyzer implementation here. As more language tests etc get written we will get to all of these.

**Comment by Solido** [comment]
I understand that the painting is still fresh, this report is a mark of interest for the macros features. Thanks.
