### ISSUE TITLE
Failures on [vm/service]: VM plumbing for Throw.forErrorHandling

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#55059]
There are new test failures on [[vm/service]: VM plumbing for Throw.forErrorHandling](https://github.com/dart-lang/sdk/commit/44094abe2f5111e3cbf674855da82c4899d10660).

The tests
```
standalone/regress_53519_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-aot-android-release-arm64c
vm-aot-android-release-arm_x64
vm-aot-dwarf-linux-product-x64
vm-aot-linux-debug-simarm_x64
vm-aot-linux-release-simarm_x64
vm-aot-linux-release-x64
vm-aot-mac-release-arm64
vm-aot-mac-release-x64
vm-aot-obfuscate-linux-release-x64
vm-aot-win-release-arm64
vm-aot-win-release-x64
```

```
--- Command "vm_compile_to_kernel" (took 03.000250s):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_standalone_regress_53519_test/out.dill /b/s/w/ir/tests/standalone/regress_53519_test.dart -Dtest_runner.configuration=vm-aot-linux-release-x64 --packages=/b/s/w/ir/.dart_tool/package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 03.000799s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_standalone_regress_53519_test/out.S --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_standalone_regress_53519_test/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 18ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_standalone_regress_53519_test/out.dill

exit code:
0

--- Command "assemble" (took 01.000013s):
DART_CONFIGURATION=ReleaseX64 gcc -Wl,--no-undefined -shared -o /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_standalone_regress_53519_test/out.aotsnapshot /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_standalone_regress_53519_test/out.S

exit code:
0

--- Command "remove_assembly" (took 19ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_standalone_regress_53519_test/out.S

exit code:
0

--- Command "vm" (took 59ms):
DART_CONFIGURATION=ReleaseX64 TEST_COMPILATION_DIR=/b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_standalone_regress_53519_test out/ReleaseX64/dart_precompiled_runtime --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_standalone_regress_53519_test/out.aotsnapshot

exit code:
255

stdout:
#0      destructure (file:///b/s/w/ir/tests/standalone/regress_53519_test.dart:11)
#1      main (file:///b/s/w/ir/tests/standalone/regress_53519_test.dart:17)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:722)
#1      Expect.isTrue (package:expect/expect.dart:132)
#2      main (file:///b/s/w/ir/tests/standalone/regress_53519_test.dart:25)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

--- Re-run this test:
python3 tools/test.py -n vm-aot-linux-release-x64 standalone/regress_53519_test
```

**Comment by liamappelbe** [comment]
Should be fixed by https://dart-review.googlesource.com/c/sdk/+/354820

**Comment by liamappelbe** [comment]
Looks like the `isVmObfuscateConfiguration` and `isVmDwarfConfiguration` flags aren't working at all.

**Comment by liamappelbe** [comment]
Fixed: https://dart-review.googlesource.com/c/sdk/+/355960
