### ISSUE TITLE
extension type not compiling for flutter web

### ISSUE THREAD

**Issue by ABausG** [dart-lang/sdk#55079]
I have an extension type that defines a custom constructor that calls a redirect constructor. It does not compile for flutter web (compiles for macos)

This is My Button Definition with the redirect constructors
```dart
sealed class MyButton extends StatefulWidget {

  const MyButton._({
    super.key,
    required this.label,
    required VoidCallback? onPressed,
    this.icon,
  });
 
  const factory MyButton.secondary({
    Key? key,
    required String label,
    required VoidCallback? onPressed,
    IconData? icon,
  }) = _MyButtonSecondary;

  const factory MyButton.secondaryIcon({
    Key? key,
    required IconData icon,
    required VoidCallback? onPressed,
  }) = _MyButtonSecondary.icon;

  final String? label;
  final VoidCallback? onPressed;
  final IconData? icon;

  // Usual State methods and state for MyButton
}

class _MyButtonSecondary extends MyButton {
  const _MyButtonSecondary({
    super.key,
    required String label,
    required super.onPressed,
    super.icon,
  }) : super._(label: label);

  const _MyButtonSecondary.icon({
    super.key,
    required super.icon,
    required super.onPressed,
  }) : super._(label: null);
}

```

This is my extension type

```dart
extension type MyHeadingAction._(Widget _w) implements Widget {
  MyHeadingAction.iconButton({
    Key? key,
    required IconData icon,
    required VoidCallback? onPressed,
  }) : _w = MyButton.secondaryIcon(
          key: key,
          icon: icon,
          onPressed: onPressed,
        );

  MyHeadingAction.textButton({
    Key? key,
    required String label,
    required VoidCallback? onPressed,
  }) : _w = MyButton.secondary(
          key: key,
          label: label,
          onPressed: onPressed,
        );
}
```

I have also tried to add an `icon: null` to the `MyButton.secondary` constructor but this did not help.

This is the output from `flutter build web`

```
Target dart2js failed: ProcessException: Process exited abnormally with exit code 253:
../../packages/app_ui_commons/lib/src/my/molecules/my_button.dart:39:17:
Internal Error: The compiler crashed when compiling this element.
  const factory MyButton.secondary({
                ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.3.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Null check operator used on a null value
#0      ClosureDataBuilder.createClosureEntities.processModel (package:compiler/src/js_model/closure.dart:376:59)
#1      ClosureDataBuilder.createClosureEntities.<anonymous closure>.<anonymous closure> (package:compiler/src/js_model/closure.dart:437:9)
#2      DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:154:15)
#3      ClosureDataBuilder.createClosureEntities.<anonymous closure> (package:compiler/src/js_model/closure.dart:436:17)
#4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#5      ClosureDataBuilder.createClosureEntities (package:compiler/src/js_model/closure.dart:435:19)
#6      JClosedWorldBuilder.convertClosedWorld (package:compiler/src/js_model/js_world_builder.dart:172:41)
#7      JsBackendStrategy.createJClosedWorld (package:compiler/src/js_model/js_strategy.dart:184:52)
#8      Compiler.closeResolution (package:compiler/src/compiler.dart:737:25)
#9      Compiler.computeClosedWorld (package:compiler/src/compiler.dart:383:9)
#10     Compiler.produceClosedWorld (package:compiler/src/compiler.dart:532:21)
#11     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:637:39)
<asynchronous suspension>
#12     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:315:7)
<asynchronous suspension>
#13     Compiler.runInternal (package:compiler/src/compiler.dart:314:5)
<asynchronous suspension>
#14     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:235:11)
<asynchronous suspension>
#15     compile.<anonymous closure> (package:compiler/compiler_api.dart:256:30)
<asynchronous suspension>
#16     compile.compilationDone (package:compiler/src/dart2js.dart:729:3)
<asynchronous suspension>
#17     main (package:compiler/src/dart2js.dart:1233:3)
<asynchronous suspension>
  Command: /Users/antonborries/fvm/versions/3.19.1/bin/cache/dart-sdk/bin/dart --disable-dart-dev
  /Users/antonborries/fvm/versions/3.19.1/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
  --platform-binaries=/Users/antonborries/fvm/versions/3.19.1/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/04817c99c9fd4956f27505204f7e344335810aed/ --native-null-assertions --no-source-maps -O4 -o
  /Users/antonborries/projects/app/apps/widgetbook/.dart_tool/flutter_build/846120b4c5c0513ff1e25f1352e8304a/main.dart.js
  /Users/antonborries/projects/app/apps/widgetbook/.dart_tool/flutter_build/846120b4c5c0513ff1e25f1352e8304a/app.dill
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:326:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:192:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:861:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:628:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:93:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:200:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             11.1s
Error: Failed to compile application for the Web.
```

`Flutter Doctor`
```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.1 23B2073 darwin-arm64, locale en-DE)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
[✓] IntelliJ IDEA Community Edition (version 2023.3.2)
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)            
[✓] Network resources

! Doctor found issues in 1 category.
```

`dart --version`
```
Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"
```

**Comment by fishythefish** [comment]
Closing this in favor of #55135. If that issue is fixed and this one persists, please feel free to reopen and let us know.
