### ISSUE TITLE
Target dart2js failed: ProcessException: Process exited abnormally with exit code 253: .dart_tool/flutter_build/c517bab813172500a4c587e785642942/app.dill: Internal Error: The compiler crashed when compiling this element. The compiler is broken.

### ISSUE THREAD

**Issue by bvversoz** [dart-lang/sdk#55096]
OS: Maco OS Sonoma version: 14.2.1
Dart SDK Version:  3.0.0-75.0.dev (dev) (Thu Dec 29 16:50:26 2022 -0800) on "macos_x64"
 the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Error reading '.dart_tool/flutter_build/c517bab813172500a4c587e785642942/app.dill'  (No such file or directory)
  Command: /Users/benversoza/Development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/benversoza/Development/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
  --platform-binaries=/Users/benversoza/Development/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/c52b3033eca6a65f504753356fb3ff49f110bde6/ -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false --native-null-assertions --no-source-maps -O4 -o
  /Users/benversoza/Documents/Fresh_Start/FireBaseGettingStarted/lib/.dart_tool/flutter_build/c517bab813172500a4c587e785642942/main.dart.js
  /Users/benversoza/Documents/Fresh_Start/FireBaseGettingStarted/lib/.dart_tool/flutter_build/c517bab813172500a4c587e785642942/app.dill
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:326:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:195:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:91:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:237:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:360:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:300:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             26.0s
Error: Failed to compile application for the Web.

**Comment by sigmundch** [comment]
Thanks for filing the issue!

We need a bit more info to investigate. I believe the stack trace above is an error from the flutter tool when it gets in a bad state after the compilation failed. Could you share with us the stack trace from the dart2js compiler (what comes after "The compiler is broken" which you shared in the title)? Or do you have a small example code that reproduces the crash that we can use to debug?

Thanks!

**Comment by bvversoz** [comment]
This is what I get when trying to build to web.

 flutter build web --web-renderer html

Target dart2js failed: ProcessException: Process exited abnormally with exit code 253:
.dart_tool/flutter_build/c517bab813172500a4c587e785642942/app.dill:
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.4.0-190.0.dev), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Error reading '.dart_tool/flutter_build/c517bab813172500a4c587e785642942/app.dill'  (No such file or directory)
  Command: /Users/benversoza/Development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/benversoza/Development/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
  --platform-binaries=/Users/benversoza/Development/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/c52b3033eca6a65f504753356fb3ff49f110bde6/ -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false --native-null-assertions --no-source-maps -O4 -o
  /Users/benversoza/Documents/Fresh_Start/FireBaseGettingStarted/lib/.dart_tool/flutter_build/c517bab813172500a4c587e785642942/main.dart.js
  /Users/benversoza/Documents/Fresh_Start/FireBaseGettingStarted/lib/.dart_tool/flutter_build/c517bab813172500a4c587e785642942/app.dill
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:326:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:195:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:91:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:237:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:360:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:300:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             26.0s
Error: Failed to compile application for the Web.

**Comment by sigmundch** [comment]
Thanks @bvversoz, unfortunately I think something else in the tooling is hiding the original error.

Is the input you are using by chance something you can reduce to a repro you could share with us so we can try it locally?

@christopherfujino - I'm wondering if flutter tool may be invoking dart2js after a failure on a previous step when generating the app.dill, and that previous error is being shadowed accidentally, is that possible? Are there by chance other issues reported on the flutter issue tracker related to this?

**Comment by ChrisSonamove** [comment]
I am having the exact same issue, is this something that was resolved? 

Target dart2js failed: ProcessException: Process exited abnormally with exit code 253:
.dart_tool/flutter_build/8b9f3dac2e5f4951a43c9cb22d496247/app.dill:
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

**Comment by kaumudpa** [comment]
Same issue here - This is Breaking all our builds with GitHub Actions which uses ubuntu based runners but on our local mac machines we are able to build without issues.

**Comment by christopherfujino** [comment]
>I'm wondering if flutter tool may be invoking dart2js after a failure on a previous step when generating the app.dill, and that previous error is being shadowed accidentally, is that possible? Are there by chance other issues reported on the flutter issue tracker related to this?
 
 Assigning to myself to investigate this

**Comment by higaski** [comment]
I'm getting this error regardless whether I'm building for html or canvaskit.

```sh
 ╰─λ flutter --version
Flutter 3.19.6 • channel  • https://github.com/flutter/flutter.git
Framework • revision archlinuxaur (unknown (arch linux aur package)) • 2038-01-19 03:14:08
Engine • revision c4cd48e18646
Tools • Dart 3.3.3 • DevTools 2.31.1
```

```sh
 ╰─λ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel , 3.19.6, on Garuda Linux 6.8.9-zen1-2-zen, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] Connected device (1 available)
[✓] Network resources
```

And here is the entire log in all its glory
```sh
 ╰─λ flutter build web

Target dart2js failed: ProcessException: Process exited abnormally with exit code 253:
.dart_tool/flutter_build/4c3456ca319847fe509dce5b0b173b19/main.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.3.4), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Crash when compiling file:///home/vinci/Develop/VSCode/OpenRemise/Frontend/.dart_tool/flutter_build/4c3456ca319847fe509dce5b0b173b19/main.dart:
Unexpected Kernel Format Version 117 (expected 114) when reading file:///usr/lib/flutter/bin/cache/flutter_web_sdk/kernel/dart2js_platform.dill.

#0      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:692:9)
#1      Timeline.timeSync (dart:developer/timeline.dart:173:22)
#2      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:679:21)
#3      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:463:10)
#4      ProcessedOptions.loadAdditionalDills (package:front_end/src/base/processed_options.dart:438:20)
<asynchronous suspension>
#5      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:89:14)
<asynchronous suspension>
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#7      compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:197:37)
<asynchronous suspension>
#8      CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139:3)
<asynchronous suspension>
#9      compile (package:front_end/src/api_unstable/dart2js.dart:195:36)
<asynchronous suspension>
#10     _loadFromSource (package:compiler/src/phase/load_kernel.dart:317:29)
<asynchronous suspension>
#11     run (package:compiler/src/phase/load_kernel.dart:411:36)
<asynchronous suspension>
#12     Compiler.loadKernel (package:compiler/src/compiler.dart:391:9)
<asynchronous suspension>
#13     Compiler.produceKernel (package:compiler/src/compiler.dart:398:36)
<asynchronous suspension>
#14     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:631:20)
<asynchronous suspension>
#15     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:315:7)
<asynchronous suspension>
#16     Compiler.runInternal (package:compiler/src/compiler.dart:314:5)
<asynchronous suspension>
#17     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:235:11)
<asynchronous suspension>
#18     compile.<anonymous closure> (package:compiler/compiler_api.dart:256:30)
<asynchronous suspension>
#19     compile.compilationDone (package:compiler/src/dart2js.dart:729:3)
<asynchronous suspension>
#20     main (package:compiler/src/dart2js.dart:1233:3)
<asynchronous suspension>
  Command: /opt/dart-sdk/bin/dart --disable-dart-dev /opt/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/usr/lib/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/c4cd48e186460b32d44585ce3c103271ab676355/ --native-null-assertions --no-source-maps -o /home/vinci/Develop/VSCode/OpenRemise/Frontend/.dart_tool/flutter_build/4c3456ca319847fe509dce5b0b173b19/app.dill --packages=.dart_tool/package_config.json --cfe-only
  /home/vinci/Develop/VSCode/OpenRemise/Frontend/.dart_tool/flutter_build/4c3456ca319847fe509dce5b0b173b19/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:326:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:188:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:861:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:628:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:93:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:200:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             244ms
Error: Failed to compile application for the Web.
```

**Comment by gxlj** [comment]
any progress ? 
similar error 
using flutter3.22.1 to 
1. flutter create myapp
2. flutter build web
3. build throw error: 
Target dart2js failed: ProcessException: Process exited abnormally with exit code 253:
The compiler crashed: WebSocketException: Connection to 'http://127.0.0.1:51282/6yx_aXND-qI=/ws#' was not upgraded to websocket

**Comment by lz5577** [comment]
Limiting the version of cached_network_image_web in the pubspec.yaml file can avoid this problem

dependency_overrides:
  cached_network_image_web: 1.1.1

**Comment by sigmundch** [comment]
A new incident of this issue was reported over the weekend (see #60233)

@bkonyi - I was thinking maybe we should move this issue under the flutter tool instead? Unfortunately I don't think we have much available to help us investigate.
