### ISSUE TITLE
Dart CLI app crashes on hot-reload

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#55126]
This is reproducible on the `main` branch of the Dart SDK, but not on the `beta` branch:
* `3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e` - reproducible
* ` 3.4.0-99.1.beta` - not reproducible

How to reproduce:
* Run a Dart CLI app with the `--observe` flag: `dart run  --observe bin/my_cli_app.dart`
* Open the Dart DevTools URI printed in the terminal: `The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/3qZo4o3znDg=/devtools?uri=ws://127.0.0.1:8181/3qZo4o3znDg=/ws`
* From Dart DevTools, hit the hot-reload button

Expected behavior: hot-reload reloads the app
Actual behavior: hot-reload crashes the app

Stack trace:

```
../../runtime/vm/isolate_reload.cc: 671: error: An error occurred while rejecting the most recent compilation results: Bad state: Incremental compiler created for expression compilation only; cannot reject
#0      IncrementalCompiler.reject (package:vm/incremental_compiler.dart:171:7)
#1      IncrementalCompilerWrapper.reject (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:353:45)
#2      _processLoadRequest (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:849:25)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

version=3.4.0-edge.3786c5e5eecf158abac61c9f8481c7eadd0f2240 (main) (Wed Mar 6 21:15:36 2024 +0000) on "macos_x64"
pid=56415, thread=13571, isolate_group=main(0x7fc7e0009000), isolate=main(0x7fc7a3008200)
os=macos, arch=x64, comp=no, sim=no
isolate_instructions=10f8e0a00, vm_instructions=10f8e0a00
fp=700001facda0, sp=700001facd70, pc=10fb01994
  pc 0x000000010fb01994 fp 0x0000700001facda0 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x26f994
  pc 0x000000010f8e0c14 fp 0x0000700001face80 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x4ec14
  pc 0x000000010fa4b413 fp 0x0000700001fad120 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x1b9413
  pc 0x000000010fa44825 fp 0x0000700001fad1d0 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x1b2825
  pc 0x000000010fb5fb49 fp 0x0000700001fad210 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x2cdb49
  pc 0x000000010fb56875 fp 0x0000700001fad820 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x2c4875
  pc 0x000000010fb56e01 fp 0x0000700001fad840 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x2c4e01
  pc 0x000000010fa4291d fp 0x0000700001fadde0 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x1b091d
  pc 0x000000010fa67d06 fp 0x0000700001fade50 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x1d5d06
  pc 0x000000010fa68118 fp 0x0000700001fadea0 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x1d6118
  pc 0x000000010fb7fb37 fp 0x0000700001fadf20 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x2edb37
  pc 0x000000010fb7fdc3 fp 0x0000700001fadf50 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x2eddc3
  pc 0x000000010fafe3be fp 0x0000700001fadfb0 /Users/elliottbrooks/.dart-sdks/3.4.0-edge.37753571167da8e5ff397a04e424a0b5c2c81a3e/bin/dart+0x26c3be
  pc 0x00007ff80a12e202 fp 0x0000700001fadfd0 _pthread_start+0x63
  pc 0x00007ff80a129bab fp 0x0000700001fadff0 thread_start+0xf
-- End of DumpStackTrace
```

FYI @bkonyi

**Comment by a-siva** [comment]
//cc @jensjoha

**Comment by bkonyi** [comment]
This is the [project](https://github.com/elliette/cli_web_test) @elliette shared with me. However, I'm not able to reproduce at `37753571167da8e5ff397a04e424a0b5c2c81a3e` with a debug build on my x64 Mac.

**Comment by jensjoha** [comment]
I have this file:
```
$ cat t.dart
Future<void> main() async {
  for(int i = 0; i < 1000000; i++) {
    print("Hello $i");
    await Future.delayed(const Duration(seconds: 1));
  }
}
```

If I try to run `out/ReleaseX64/dart run  --observe  t.dart` I get this:

```
Could not find file ``
vm-service: Error: Unhandled exception:
FormatException: Unexpected character (at character 1)
Unhandled exception:
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1376:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1243:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:908:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      _DebuggingSession.start.<anonymous closure> (dart:vmservice_io:144:27)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#12     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#13     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#14     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#15     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#16     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#17     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#21     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#22     _StreamController._add (dart:async/stream_controller.dart:658:7)
#23     _StreamController.add (dart:async/stream_controller.dart:606:5)
#24     _Socket._onData (dart:io-patch/socket_patch.dart:2449:41)
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#28     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#29     _StreamController._add (dart:async/stream_controller.dart:658:7)
#30     _StreamController.add (dart:async/stream_controller.dart:606:5)
#31     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
#32     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#36     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

Unhandled exception:
FormatException: Unexpected character (at character 1)
Unhandled exception:
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1376:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1243:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:908:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      _DebuggingSession.start.<anonymous closure> (dart:vmservice_io:144:27)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#12     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#13     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#14     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#15     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#16     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#17     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#21     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#22     _StreamController._add (dart:async/stream_controller.dart:658:7)
#23     _StreamController.add (dart:async/stream_controller.dart:606:5)
#24     _Socket._onData (dart:io-patch/socket_patch.dart:2449:41)
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#28     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#29     _StreamController._add (dart:async/stream_controller.dart:658:7)
#30     _StreamController.add (dart:async/stream_controller.dart:606:5)
#31     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
#32     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#36     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

If I instead run with `out/ReleaseX64/dart --observe t.dart`  everything works fine --- the kernel service is asked to start in incremental mode, the incremental compiler is fired up as normal and we can reload.

If I instead run with `out/ReleaseX64/dart t.dart` and send signal 3 to the process to enable the observatory protocol and either enable observatory (e.g. `http://127.0.0.1:whatnot/bla/_serveObservatory`), then go to http://127.0.0.1:whatnot/bla/, execute an expression compilation, then click the reload button; OR load up devtools (which apparently fires an expression compilation when loaded), then clicks the reload button things blow up because on the expression compilation an incremental compiler "only for expression compilation" is created which can't reload:

```
../../runtime/vm/isolate_reload.cc: 671: error: An error occurred while rejecting the most recent compilation results: Bad state: Incremental compiler created for expression compilation only; cannot reject
#0      IncrementalCompiler.reject (package:vm/incremental_compiler.dart:174:7)
#1      IncrementalCompilerWrapper.reject (file:///path/to/sdk/pkg/vm/bin/kernel_service.dart:353:45)
#2      _processLoadRequest (file:///path/to/sdk/pkg/vm/bin/kernel_service.dart:850:25)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

version=3.4.0-edge (main) (Unknown timestamp) on "linux_x64"
pid=2260867, thread=2260876, isolate_group=main(0x5568db0c54d0), isolate=main(0x5568db0c7e90)
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=5568d9521ca0, vm_instructions=5568d9521ca0
fp=7f85430fdc80, sp=7f85430fdb50, pc=5568d971e7dc
  pc 0x00005568d971e7dc fp 0x00007f85430fdc80 dart::Profiler::DumpStackTrace+0x7c
  pc 0x00005568d9521e94 fp 0x00007f85430fdd60 dart::Assert::Fail+0x84
  pc 0x00005568d967ac7d fp 0x00007f85430fdff0 dart::IsolateGroupReloadContext::Reload+0x125d
  pc 0x00005568d96747a3 fp 0x00007f85430fe0a0 dart::IsolateGroup::ReloadSources+0x1c3
  pc 0x00005568d9774896 fp 0x00007f85430fe0e0 dart::ReloadSources+0x116
  pc 0x00005568d976b49d fp 0x00007f85430fe6f0 dart::Service::InvokeMethod+0x30d
  pc 0x00005568d976b9e1 fp 0x00007f85430fe710 dart::Service::HandleIsolateMessage+0x11
  pc 0x00005568d96729a2 fp 0x00007f85430feca0 dart::IsolateMessageHandler::HandleMessage+0x1f2
  pc 0x00005568d9694da6 fp 0x00007f85430fed10 dart::MessageHandler::HandleMessages+0x116
  pc 0x00005568d96951a8 fp 0x00007f85430fed60 dart::MessageHandler::TaskCallback+0x1e8
  pc 0x00005568d9792d97 fp 0x00007f85430fede0 dart::ThreadPool::WorkerLoop+0x137
  pc 0x00005568d9793022 fp 0x00007f85430fee10 dart::ThreadPool::Worker::Main+0x72
  pc 0x00005568d971b656 fp 0x00007f85430feed0 dart::ThreadStart+0xd6
-- End of DumpStackTrace
Aborted
```

If instead, after sending the signal I enable observatory, then reload *before* executing an expression compilation, a "normal" incremental compiler is created and everything works fine (although I think it compiles from scratch which might not be optimal for bigger apps).

Further details on this: When trying to hot reload with a for expression compilation only compiler, it tries to compile, the compiler crashes (throws that it was created for expression compilation only) and the kernel service sends back a `CompilationResult.crash`. Then does the VM send the `reject` message, on which the kernel_service throws without catching anything, causing the whole vm to come down. This might not be optimal.

With not being able to run `out/ReleaseX64/dart run  --observe  t.dart` I don't know what that does, but from the above it seems that it might enable the service protocol after the fact. Maybe it shouldn't do that? We might also consider if a) We should just give an error message instead of throwing when trying something like this; and/or b) to what degree we want to support not having an incremental compiler and then being able to reload too.

For a little history the "only for expression compilation" incremental compiler was - from what I remember - created so that dills - including hot reload dills - could be created by an external system (from inside google3), but for the expression compilation via the normal dart debugger to still work. In that scenario, as any new hot reload dill would still come from the external system we don't really want to support anything other than expression compilation, we certainly don't want to compile everything from scratch and we don't want the external build system, what the vm has actually loaded and the "internal one" (the incremental compiler) to get out-of-sync.

**Comment by bkonyi** [comment]
> If I try to run out/ReleaseX64/dart run  --observe  t.dart I get this

Filed https://github.com/dart-lang/sdk/issues/55185 for that issue. I have a fix ready [here](https://dart-review.googlesource.com/c/sdk/+/357360).

**Comment by a-siva** [comment]
I tried reproducing on the main branch and am unable to do so.
@elliette can you try reproducing it again and let us know if this is still an issue.

**Comment by elliette** [comment]
Sorry for missing the earlier comment! Just confirmed this is no longer reproducible for me on the `main` branch of the Dart SDK.
