### ISSUE TITLE
bug using redirecting constructor in initializer of extension type

### ISSUE THREAD

**Issue by curt-weber** [dart-lang/sdk#55135]
Extension types don't seem to support typed data, for instance `Float64x2`.
There is a restriction that typed_data isn't extended, but that applies to other types like `int`, `double`, which extension types can use.

```
import 'dart:math';
import 'dart:typed_data';

extension type const Point._(Float64x2 point) implements Float64x2 {
  Point(double x, double y) : point = Float64x2(x, y);
  double get distance => sqrt(point.x * point.x + point.y * point.y);
}

void main() => print(Point(0, 0)); // prints null
```
I was checking to see if extension types would be more performant in the case of `Offset`, but using `List<double>` is actually slower from my tests.

**Comment by sigmundch** [comment]
It appears this is triggering issues on both web compilers, coincidentally. Likely these are different bugs.

Both trigger when the initializer of the extension type representation field uses a redirecting factory constructor (which `Float64x2` happens to have). Here is an standalone repro of this:

```dart
class B implements A {
  final int x = 1;
}
abstract class A {
  int get x;
  factory A() = B;
}

extension type C._(A point) implements A {
  C() : point = A(); // << initializer is redirecting factory
}

void main() {
  print(A().x);
  print(C().x);
}
```

This program compiles in DDC, but like above gets `null` instead of an instance of `B` when calling `C()`. Changing the initializer to use `B()` instead of `A()` works as expected.

Dart2js surprisingly crashes! Here is the crash error for the same program:
```
Internal Error: The compiler crashed when compiling this element.
  factory A() = B;
          ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.4.0-179.0.dev), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Null check operator used on a null value
#0      ClosureDataBuilder.createClosureEntities.processModel (package:compiler/src/js_model/closure.dart:375:59)
#1      ClosureDataBuilder.createClosureEntities.<anonymous closure>.<anonymous closure> (package:compiler/src/js_model/closure.dart:436:9)
#2      DiagnosticReporter.withCurrentElement (package:compiler/src/diagnostics/diagnostic_listener.dart:159:15)
#3      ClosureDataBuilder.createClosureEntities.<anonymous closure> (package:compiler/src/js_model/closure.dart:435:17)
#4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#5      ClosureDataBuilder.createClosureEntities (package:compiler/src/js_model/closure.dart:434:19)
#6      JClosedWorldBuilder.convertClosedWorld (package:compiler/src/js_model/js_world_builder.dart:172:41)
#7      JsBackendStrategy.createJClosedWorld (package:compiler/src/js_model/js_strategy.dart:184:52)
#8      Compiler.closeResolution (package:compiler/src/compiler.dart:743:25)
#9      Compiler.computeClosedWorld (package:compiler/src/compiler.dart:385:9)
#10     Compiler.produceClosedWorld (package:compiler/src/compiler.dart:534:21)
#11     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:643:39)
<asynchronous suspension>
#12     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:317:7)
<asynchronous suspension>
#13     Compiler.runInternal (package:compiler/src/compiler.dart:316:5)
<asynchronous suspension>
#14     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:237:11)
<asynchronous suspension>
#15     compile.<anonymous closure> (package:compiler/compiler_api.dart:255:30)
<asynchronous suspension>
#16     compile.compilationDone (package:compiler/src/dart2js.dart:730:3)
<asynchronous suspension>
#17     main (package:compiler/src/dart2js.dart:1240:3)
<asynchronous suspension>
```

**Comment by nshahan** [comment]
cc @johnniwinther

This looks like an issue with the lowering of redirecting factory constructors for both js compilers. @sigmundch example above looks like a good reproduction of the problem.

**Comment by fishythefish** [comment]
#55079 is likely the same bug in dart2js.

**Comment by sigmundch** [comment]
Moving temporarily to area-frontend, we can move it back if in fact it's an issue on the web compilers.

**Comment by chloestefantsova** [comment]
I might have a solution. I'm working on it in https://dart-review.googlesource.com/c/sdk/+/357161.

**Comment by sigmundch** [comment]
Thanks so much for the fix  @chloestefantsova!

@chloestefantsova @johnniwinther - since the fix is fairly contained, it seems it may be worth considering filing a cherry-pick request for it. What do you think?

**Comment by chloestefantsova** [comment]
> @chloestefantsova @johnniwinther - since the fix is fairly contained, it seems it may be worth considering filing a cherry-pick request for it. What do you think?

That's a good idea. I've just filed https://github.com/dart-lang/sdk/issues/55194.
