### ISSUE TITLE
Parse failure for broken augmentation library

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#55145]
https://dart-review.googlesource.com/c/sdk/+/356401 adds a test case with a broken augmentation library, it trips an assert in the parse test

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8754039752317012545/+/u/test_results/new_test_failures__logs_

```
'package:_fe_analyzer_shared/src/parser/parser_impl.dart': Failed assertion: line 846 pos 12: 'optional('augment', augmentKeyword)': is not true.

#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      Parser.parseLibraryAugmentation (package:_fe_analyzer_shared/src/parser/parser_impl.dart:846:12)
#3      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:777:20)
#4      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:530:14)
#5      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:410:15)
```

I'll mark it approved since the failure is unimportant for the PR which adds test_runner support for expectations in augmentation libraries.

**Comment by johnniwinther** [comment]
@davidmorgan I think this issue is obsolete and that we might want to clean up some tests/test infrastructure in preparation for the augmentations feature. Do you agree?

**Comment by davidmorgan** [comment]
Thanks Johnni.

I'll revert the change to the test infra as augmentation libraries are not a thing any more 

https://dart-review.googlesource.com/c/sdk/+/490100

In the language tests I only see one test using augmentations under augmentation_libraries, I guess we can just remove it, I'll send a CL.

@Darkildo please see item 1.22 in the changelog of the augmentations feature https://github.com/dart-lang/language/blob/main/working/augmentations/feature-specification.md -- augmentation libraries are no longer part of the spec. So, I'm not sure your PR makes sense as is.

**Comment by davidmorgan** [comment]
The CL is reverted so I think this can be closed.
