### ISSUE TITLE
`$HOME/.dart-tool` issue

### ISSUE THREAD

**Issue by busslina** [dart-lang/sdk#55146]
Today I had the first problem of a kind. I have a systemd service run under `www-data` user. I did this multiple in the past and never failed.

Today's fail was caused due to `www-data` has no permission to write on his own home directory (/var/www). I suppose that the latest Dart version creates this directory even if I have Analytics disabled.

I patched this by giving it permissions, execute Dart and then revoking the permissions.

Is there a way to prevent Dart creating this directory? Would be very helpful.

**Comment by busslina** [comment]
If it is mandatory to have a config directory I propose you an alternative solution that is to specify a config directory via a flag command like `dart --config-dir <configuration_dir>`

**Comment by busslina** [comment]
Complementary, would be great `dart --create-config-dir`

**Comment by bkonyi** [comment]
I think you might be able to prevent the Dart CLI from creating this folder if you provide `--suppress-analytics` to each run, but @eliasyishak should be able to confirm.

**Comment by bkonyi** [comment]
> When I executed `dart --disable-analytics` that folder is created to store the info that hold that I disabled analytics.

Yeah, I don't think `--disable-analytics` would work since it stores its state in `$HOME/.dart-tool`, but `--suppress-analytics` might take us down a code path that doesn't even try to create the folder. That's my working theory, anyway :)

**Comment by eliasyishak** [comment]
Hmm there should be some handling happening already to check for permissions here

https://github.com/dart-lang/tools/blob/main/pkgs/unified_analytics/lib/src/analytics.dart#L64

Which is running the utility function defined here

https://github.com/dart-lang/tools/blob/24087e1316bab779ae9fcb0166027e95b4716188/pkgs/unified_analytics/lib/src/utils.dart#L115

@busslina what does your home variable resolve to?

**Comment by busslina** [comment]
@eliasyishak 

`www-data` has `/usr/sbin/nologin` as shell, but patching it to `/bin/bash` it gives you `/var/www`
![imagen](https://github.com/dart-lang/sdk/assets/73592852/10695597-c4e1-4123-a551-274f64c59605)

**Comment by eliasyishak** [comment]
@busslina im curious to see what would happen if you set that $HOME env variable when you execute your dart command?

**Comment by busslina** [comment]
@eliasyishak 
I patched the Systemd with `Environment="HOME=/home/admin"` and know it is worst I think hehe:
![imagen](https://github.com/dart-lang/sdk/assets/73592852/4cbf5421-a042-4644-a5af-25b7f03795d0)

**Comment by eliasyishak** [comment]
Yeah I figured it would probably cause errors elsewhere, can you paste the full stack trace?

**Comment by busslina** [comment]
> Yeah I figured it would probably cause errors elsewhere, can you paste the full stack trace?

Thanks to your ask I discovered how to see the log (with no pager) ;)

Seems I was not right, still same problem. So, ChatGPT said me that `Environment="HOME=/home/admin"` is the way. Either this is falling or something else:

```
Mar 09 11:31:14 server3.busslina.com dart[35981]: Exception: 'PathAccessException: Creation failed, path = '/var/www/.dart-tool' (OS Error: Permission denied, errno = 13)'
Mar 09 11:31:14 server3.busslina.com dart[35981]: Stack Trace:
Mar 09 11:31:14 server3.busslina.com dart[35981]: #0      _Directory.createSync (dart:io/directory_impl.dart:124:7)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #1      _File.createSync (dart:io/file_impl.dart:303:14)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:26:16)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #3      Initializer.createConfigFile (package:unified_analytics/src/initializer.dart:53:16)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #4      Initializer.run (package:unified_analytics/src/initializer.dart:107:7)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #5      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:390:17)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #6      new Analytics (package:unified_analytics/src/analytics.dart:83:12)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #7      createUnifiedAnalytics (package:dartdev/src/unified_analytics.dart:23:10)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:182:27)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #10     new Future.sync (dart:async/future.dart:305:31)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #11     CommandRunner.run (package:args/command_runner.dart:122:14)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #12     runDartdev (package:dartdev/dartdev.dart:57:29)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #13     main (file:///b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:33)
Mar 09 11:31:14 server3.busslina.com dart[35981]: #15     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by busslina** [comment]
Any update?

**Comment by gkreitz** [comment]
If anyone else runs into this, a workaround that worked for us is to set one of the environment variables from https://github.com/dart-lang/sdk/blob/fae7752e9e5087aa51d8eaaf19aa949a0337ca8b/pkg/dartdev/lib/src/unified_analytics.dart#L121 , e.g., `BOT=true` to trick `dart` into thinking it's running in a CI environment.

This is still a bug that very much should be fixed though - `unified_analytics` really should catch the permission error when it fails to create `$HOME/.dart-tool` and gracefully deal with it (e.g,. by disabling analytics).

Demo:
```console
kattisd@961579699e92:/$ dart --version
Dart SDK version: 3.8.1 (stable) (None) on "linux_x64"
kattisd@961579699e92:/$ dart
An unexpected error was encountered by the Dart CLI.
Please file an issue at https://github.com/dart-lang/sdk/issues/new with the following details:

Invocation: 'dart help'
Exception: 'PathAccessException: Creation failed, path = '/var/lib/kattis/.dart-tool' (OS Error: Permission denied, errno = 13)'
Stack Trace:
#0      _Directory.createSync (dart:io/directory_impl.dart:146:7)
#1      _File.createSync (dart:io/file_impl.dart:340:14)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:27:16)
#3      createConfigFile (package:unified_analytics/src/initializer.dart:25:14)
#4      runInitialization (package:unified_analytics/src/initializer.dart:86:5)
#5      new Analytics (package:unified_analytics/src/analytics.dart:80:22)
#6      createUnifiedAnalytics (package:dartdev/src/unified_analytics.dart:22:10)
#7      DartdevRunner.runCommand (package:dartdev/dartdev.dart:173:27)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#9      new Future.sync (dart:async/future.dart:315:27)
#10     CommandRunner.run (package:args/command_runner.dart:122:14)
#11     runDartdev (package:dartdev/dartdev.dart:47:29)
#12     main (file:///tmp/tmp7r13n3b_/dart-3.8.1/dart/pkg/dartdev/bin/dartdev.dart:13:11)
#13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:310:33)
#14     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:12)

kattisd@961579699e92:/$ BOT=true dart
A command-line utility for Dart development.

Usage: dart <command|dart-file> [arguments]
[....]
```
