### ISSUE TITLE
Failures on [analyzer,frontend_server] Support nested macro compilation in binary protocol

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#55142]
There are new test failures on [[analyzer,frontend_server] Support nested macro compilation in binary protocol](https://dart-review.googlesource.com/c/sdk/+/355782).

The tests
```
language/macros/error/declare_and_use_same_library_cycle_test Crash (expected Pass)
language/macros/error/declare_and_use_same_library_test Crash (expected Pass)
```
are failing on configurations
```
analyzer-linux
```

**Comment by johnniwinther** [comment]
@scheglov I'm not sure what goes wrong here. I cannot reproduce the trybots failures locally. The crash stack trace indicates that the CFE doesn't detect the library cycles but this was added in https://dart-review.googlesource.com/c/sdk/+/356060

**Comment by scheglov** [comment]
Hm... Where do you see a stack trace in https://dart-review.googlesource.com/c/sdk/+/355782 ?
It looks that the bot timed out.

When I open "stdout" here
<img width="701" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/a663d807-8a3d-48d4-b6f2-5bdad1837cb7">


https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8754295110298806113/+/u/deflaking/collect_shards/unit_tests_shard_1/stdout, I get "ERROR: rpc error: code = NotFound desc = stream path not found".

When I check out the CL, build Dart SDK, it looks that `dart analyze` now works on this test.
So, yes, looks fixed to me locally.
```
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (change-355782)$ /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseARM64/dart-sdk/bin/dart analyze --enable-experiment=macros /Users/scheglov/Source/Dart/sdk.git/sdk/tests/language/macros/nesting/macro_impl_uses_macro1_test.dart
Analyzing macro_impl_uses_macro1_test.dart... 2.7s
No issues found!
```

**Comment by johnniwinther** [comment]
The timeout was new to me. The error that I saw was this:
```
/====================================================================================================\
| language/macros/error/declare_and_use_same_library_cycle_test broke (Pass -> Crash, expected Pass) |
\====================================================================================================/

--- Command "dart2analyzer" (took 05.000970s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/gen/dartanalyzer.dart.snapshot -Dtest_runner.configuration=analyzer-linux --enable-experiment=macros --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json --format=json /b/s/w/ir/cache/builder/sdk/tests/language/macros/error/declare_and_use_same_library_cycle_test.dart

analyzer json parse result:
- parse failed

exit code:
253

stderr:
Unhandled exception:
RequestChannelException: Crash when compiling:
Error loading macro class 'AnyMacro' from 'file:///b/s/w/ir/cache/builder/sdk/tests/language/macros/error/impl/macro_in_library_cycle.dart': Error instantiating macro `AnyMacro.new()`: Invalid argument(s): No executor registered to run macros from file:///b/s/w/ir/cache/builder/sdk/tests/language/macros/error/impl/macro_in_library_cycle.dart
#0      MultiMacroExecutor.instantiateMacro (package:_fe_analyzer_shared/src/macros/executor/multi_executor.dart:130)
#1      MacroApplications.loadMacroIds.ensureMacroClassIds (package:front_end/src/fasta/kernel/macro/macro.dart:531)
#2      MacroApplications.loadMacroIds (package:front_end/src/fasta/kernel/macro/macro.dart:581)
<asynchronous suspension>
#3      SourceLoader.computeMacroApplications (package:front_end/src/fasta/source/source_loader.dart:1708)
<asynchronous suspension>
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:436)
<asynchronous suspension>
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#6      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:415)
<asynchronous suspension>
#7      _buildInternal (package:front_end/src/kernel_generator_impl.dart:151)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#9      kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#10     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#11     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#12     _compileMacros (package:front_end/src/kernel_generator_impl.dart:365)
<asynchronous suspension>
#13     precompileMacros (package:front_end/src/kernel_generator_impl.dart:314)
<asynchronous suspension>
#14     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:111)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#16     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#17     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#18     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#19     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50)
<asynchronous suspension>
#20     compileToKernel (package:vm/kernel_front_end.dart:471)
<asynchronous suspension>
#21     _Client._kernelForProgram (package:frontend_server/src/binary_protocol.dart:134)
<asynchronous suspension>
#22     RequestChannel._processMessage.<anonymous closure> (package:_fe_analyzer_shared/src/macros/compiler/request_channel.dart:68)
<asynchronous suspension>

#0      MacroApplications.loadMacroIds.ensureMacroClassIds (package:front_end/src/fasta/kernel/macro/macro.dart:565)
#1      MacroApplications.loadMacroIds (package:front_end/src/fasta/kernel/macro/macro.dart:581)
<asynchronous suspension>
#2      SourceLoader.computeMacroApplications (package:front_end/src/fasta/source/source_loader.dart:1708)
<asynchronous suspension>
#3      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:436)
<asynchronous suspension>
#4      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#5      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:415)
<asynchronous suspension>
#6      _buildInternal (package:front_end/src/kernel_generator_impl.dart:151)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#8      kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#9      CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#10     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#11     _compileMacros (package:front_end/src/kernel_generator_impl.dart:365)
<asynchronous suspension>
#12     precompileMacros (package:front_end/src/kernel_generator_impl.dart:314)
<asynchronous suspension>
#13     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:111)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#15     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#16     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#17     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#18     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50)
<asynchronous suspension>
#19     compileToKernel (package:vm/kernel_front_end.dart:471)
<asynchronous suspension>
#20     _Client._kernelForProgram (package:frontend_server/src/binary_protocol.dart:134)
<asynchronous suspension>
#21     RequestChannel._processMessage.<anonymous closure> (package:_fe_analyzer_shared/src/macros/compiler/request_channel.dart:68)
<asynchronous suspension>


#0      MacroApplications.loadMacroIds.ensureMacroClassIds (package:front_end/src/fasta/kernel/macro/macro.dart:569)
#1      MacroApplications.loadMacroIds (package:front_end/src/fasta/kernel/macro/macro.dart:581)
<asynchronous suspension>
#2      SourceLoader.computeMacroApplications (package:front_end/src/fasta/source/source_loader.dart:1708)
<asynchronous suspension>
#3      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:436)
<asynchronous suspension>
#4      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#5      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:415)
<asynchronous suspension>
#6      _buildInternal (package:front_end/src/kernel_generator_impl.dart:151)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#8      kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#9      CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#10     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#11     _compileMacros (package:front_end/src/kernel_generator_impl.dart:365)
<asynchronous suspension>
#12     precompileMacros (package:front_end/src/kernel_generator_impl.dart:314)
<asynchronous suspension>
#13     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:111)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#15     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#16     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#17     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#18     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50)
<asynchronous suspension>
#19     compileToKernel (package:vm/kernel_front_end.dart:471)
<asynchronous suspension>
#20     _Client._kernelForProgram (package:frontend_server/src/binary_protocol.dart:134)
<asynchronous suspension>
#21     RequestChannel._processMessage.<anonymous closure> (package:_fe_analyzer_shared/src/macros/compiler/request_channel.dart:68)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n analyzer-linux language/macros/error/declare_and_use_same_library_cycle_test


/==============================================================================================\
| language/macros/error/declare_and_use_same_library_test broke (Pass -> Crash, expected Pass) |
\==============================================================================================/

--- Command "dart2analyzer" (took 05.000652s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/gen/dartanalyzer.dart.snapshot -Dtest_runner.configuration=analyzer-linux --enable-experiment=macros --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json --format=json /b/s/w/ir/cache/builder/sdk/tests/language/macros/error/declare_and_use_same_library_test.dart

analyzer json parse result:
- parse failed

exit code:
253

stderr:
Unhandled exception:
RequestChannelException: Crash when compiling:
Error loading macro class 'AnyMacro' from 'file:///b/s/w/ir/cache/builder/sdk/tests/language/macros/error/declare_and_use_same_library_test.dart': Error instantiating macro `AnyMacro.new()`: Invalid argument(s): No executor registered to run macros from file:///b/s/w/ir/cache/builder/sdk/tests/language/macros/error/declare_and_use_same_library_test.dart
#0      MultiMacroExecutor.instantiateMacro (package:_fe_analyzer_shared/src/macros/executor/multi_executor.dart:130)
#1      MacroApplications.loadMacroIds.ensureMacroClassIds (package:front_end/src/fasta/kernel/macro/macro.dart:531)
#2      MacroApplications.loadMacroIds (package:front_end/src/fasta/kernel/macro/macro.dart:581)
<asynchronous suspension>
#3      SourceLoader.computeMacroApplications (package:front_end/src/fasta/source/source_loader.dart:1708)
<asynchronous suspension>
#4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:436)
<asynchronous suspension>
#5      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#6      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:415)
<asynchronous suspension>
#7      _buildInternal (package:front_end/src/kernel_generator_impl.dart:151)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#9      kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#10     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#11     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#12     _compileMacros (package:front_end/src/kernel_generator_impl.dart:365)
<asynchronous suspension>
#13     precompileMacros (package:front_end/src/kernel_generator_impl.dart:314)
<asynchronous suspension>
#14     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:111)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#16     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#17     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#18     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#19     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50)
<asynchronous suspension>
#20     compileToKernel (package:vm/kernel_front_end.dart:471)
<asynchronous suspension>
#21     _Client._kernelForProgram (package:frontend_server/src/binary_protocol.dart:134)
<asynchronous suspension>
#22     RequestChannel._processMessage.<anonymous closure> (package:_fe_analyzer_shared/src/macros/compiler/request_channel.dart:68)
<asynchronous suspension>

#0      MacroApplications.loadMacroIds.ensureMacroClassIds (package:front_end/src/fasta/kernel/macro/macro.dart:565)
#1      MacroApplications.loadMacroIds (package:front_end/src/fasta/kernel/macro/macro.dart:581)
<asynchronous suspension>
#2      SourceLoader.computeMacroApplications (package:front_end/src/fasta/source/source_loader.dart:1708)
<asynchronous suspension>
#3      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:436)
<asynchronous suspension>
#4      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#5      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:415)
<asynchronous suspension>
#6      _buildInternal (package:front_end/src/kernel_generator_impl.dart:151)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#8      kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#9      CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#10     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#11     _compileMacros (package:front_end/src/kernel_generator_impl.dart:365)
<asynchronous suspension>
#12     precompileMacros (package:front_end/src/kernel_generator_impl.dart:314)
<asynchronous suspension>
#13     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:111)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#15     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#16     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#17     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#18     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50)
<asynchronous suspension>
#19     compileToKernel (package:vm/kernel_front_end.dart:471)
<asynchronous suspension>
#20     _Client._kernelForProgram (package:frontend_server/src/binary_protocol.dart:134)
<asynchronous suspension>
#21     RequestChannel._processMessage.<anonymous closure> (package:_fe_analyzer_shared/src/macros/compiler/request_channel.dart:68)
<asynchronous suspension>


#0      MacroApplications.loadMacroIds.ensureMacroClassIds (package:front_end/src/fasta/kernel/macro/macro.dart:569)
#1      MacroApplications.loadMacroIds (package:front_end/src/fasta/kernel/macro/macro.dart:581)
<asynchronous suspension>
#2      SourceLoader.computeMacroApplications (package:front_end/src/fasta/source/source_loader.dart:1708)
<asynchronous suspension>
#3      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:436)
<asynchronous suspension>
#4      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#5      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:415)
<asynchronous suspension>
#6      _buildInternal (package:front_end/src/kernel_generator_impl.dart:151)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#8      kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#9      CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#10     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#11     _compileMacros (package:front_end/src/kernel_generator_impl.dart:365)
<asynchronous suspension>
#12     precompileMacros (package:front_end/src/kernel_generator_impl.dart:314)
<asynchronous suspension>
#13     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:111)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#15     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#16     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#17     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#18     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50)
<asynchronous suspension>
#19     compileToKernel (package:vm/kernel_front_end.dart:471)
<asynchronous suspension>
#20     _Client._kernelForProgram (package:frontend_server/src/binary_protocol.dart:134)
<asynchronous suspension>
#21     RequestChannel._processMessage.<anonymous closure> (package:_fe_analyzer_shared/src/macros/compiler/request_channel.dart:68)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n analyzer-linux language/macros/error/declare_and_use_same_library_test

```

**Comment by scheglov** [comment]
Weird. I also cannot reproduce it locally.
```console
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk ((ea8551fe711...))$ ./tools/test.py --mode release --arch arm64 --compiler dart2analyzer --progress color --report language/macros/
No build targets found.
Test configuration:
    custom-configuration-1(architecture: arm64, compiler: dart2analyzer, mode: release, runtime: none, system: mac)
Suites tested: language
Total: 15 tests
 * 0 tests will be skipped (0 skipped by design)
 * 0 tests are expected to be flaky but not crash
 * 0 tests are expected to flaky crash
 * 15 tests are expected to pass
 * 0 tests are expected to fail that we won't fix
 * 0 tests are expected to fail that we should fix
 * 0 tests are expected to crash that we should fix
 * 0 tests are allowed to timeout
 * 0 could not be categorized or are in multiple categories

[00:32 | 100% | +   15 | -    0]

=== All 15 tests passed ===
```

Even if I build `xcodebuild/ReleaseARM64/gen/dartanalyzer.dart.snapshot` manually (as kernel), and run it with the same command as on bots.
```console
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk ((ea8551fe711...))$ DART_CONFIGURATION=ReleaseARM64 xcodebuild/ReleaseARM64/dart-sdk/bin/dart xcodebuild/ReleaseARM64/gen/dartanalyzer.dart.snapshot -Dtest_runner.configuration=analyzer-mac --enable-experiment=macros --ignore-unrecognized-flags --packages=.dart_tool/package_config.json --format=json tests/language/macros/error/declare_and_use_same_library_cycle_test.dart
{"version":1,"diagnostics":[{"code":"macro_definition_application_same_library_cycle","severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file":"/Users/scheglov/Source/Dart/sdk.git/sdk/tests/language/macros/error/declare_and_use_same_library_cycle_test.dart","range":{"start":{"offset":305,"line":7,"column":2},"end":{"offset":313,"line":7,"column":10}}},"problemMessage":"The macro 'AnyMacro' can't be applied in the same library cycle where it is defined.","correctionMessage":"Try moving it to a different library that does not import the one where it is applied."}]}
```

**Comment by pq** [comment]
_Friendly triage ping_: any updates on this one?

**Comment by srawlins** [comment]
_Friendly triage ping_: any updates on this one?

**Comment by johnniwinther** [comment]
The test doesn't fail anymore. Closing the issue.
