### ISSUE TITLE
[gardening] corelib/date_time7_test summer time

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#55159]
```
/=====================================================================\
| corelib/date_time7_test broke (Pass -> RuntimeError, expected Pass) |
\=====================================================================/

--- Command "vm" (took 01.000221s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & out\ReleaseX64\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-release-x64 --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\tests\corelib\date_time7_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <-7>, actual: <-8>) fails.
#0      Expect._fail (package:expect/expect.dart:722:5)
#1      Expect.equals (package:expect/expect.dart:125:5)
#2      testLocal.checkOffset (file:///C:/b/s/w/ir/tests/corelib/date_time7_test.dart:36:16)
#3      testLocal (file:///C:/b/s/w/ir/tests/corelib/date_time7_test.dart:46:3)
#4      main (file:///C:/b/s/w/ir/tests/corelib/date_time7_test.dart:55:3)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n vm-win-release-x64 corelib/date_time7_test
```

```dart
      case "PDT" || "Pacific Daylight Time":
        Expect.equals(-7, offset.inHours);
```

[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8753760245775437921/+/u/test_results/new_test_failures__logs_)

cc @parlough Your test might not be working correctly with daylight savings.

Different parts of the world change to summer time on different dates.

* US:          Sunday, 10 March 2024
* Europe:    Sunday, 31 March 2024

**Comment by parlough** [comment]
I'm not at a computer right now, but I faintly remember my change only affecting the WASM backend.

However, I think Pacific Daylight Time should still be `-7` no matter what. So this is potentially an existing VM issue that the additional test cases ended up catching.

Perhaps https://dart-review.googlesource.com/c/sdk/+/356681 will fix it?
