### ISSUE TITLE
[gardening] vm/dart/gc/splay_c_finalizer_test crashing

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#55179]
There are new test failures on [Completion. Don't update @FailingTest expectations....[gardening] Fix test](https://github.com/dart-lang/sdk/compare/e7daade2913335534ea2cdcf9fbee1f74ec83d49~...e2e6ee8b0264ef1809462033100b60fbeff148c0).

The tests
```
vm/dart/gc/splay_c_finalizer_test/0 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/1 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/10 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/11 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/12 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/13 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/14 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/15 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/16 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/17 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/18 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/19 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/2 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/20 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/21 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/3 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/4 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/5 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/6 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/7 Crash (expected Pass)
vm/dart/gc/splay_c_finalizer_test/9 Crash (expected Pass)
```
are failing on configurations
```
vm-aot-msan-linux-release-x64
```

```
stderr:
==72521==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55d398ac3dca in dart::ObjectPtr::GetClassIdMayBeSmi() const out/ReleaseMSANX64/../../runtime/vm/tagged_pointer.h:152:12
    #1 0x55d398ac3dca in dart::Object::setPtr(dart::ObjectPtr, long) out/ReleaseMSANX64/../../runtime/vm/object.h:13407:25
    #2 0x55d398ac3dca in dart::Object::HandleImpl(dart::Zone*, dart::ObjectPtr, long) out/ReleaseMSANX64/../../runtime/vm/object.h:676:10
    #3 0x55d398afec2b in dart::Object::Handle(dart::Zone*, dart::ObjectPtr) out/ReleaseMSANX64/../../runtime/vm/object.h:415:12
    #4 0x55d398afec2b in dart::BootstrapNatives::FN_FinalizerEntry_SetExternalSize(_Dart_Handle*, long) out/ReleaseMSANX64/../../runtime/lib/ffi.cc:107:7
    #5 0x7fedc7a7b857 in FinalizerEntry._setExternalSize$Method$FfiNative dart:_internal-patch/internal_patch.dart
    #6 0x7fedc7a7b7fa in FinalizerEntry._setExternalSize$Method$FfiNative dart:_internal-patch/internal_patch.dart
    #7 0x7fedc7a7af24 in FinalizerEntry.setExternalSize dart:_internal-patch/internal_patch.dart:426
    #8 0x7fedc7a7af24 in _NativeFinalizer.attach dart:ffi-patch/ffi_native_finalizer_patch.dart:59
    #9 0x7fedc7a7adee in new Leaf file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_c_finalizer_test.dart:69
    #10 0x7fedc7a7acb3 in Payload.generate file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_c_finalizer_test.dart:78
    #11 0x7fedc7a7acd2 in Payload.generate file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_c_finalizer_test.dart:79
    #12 0x7fedc7a7acd2 in Payload.generate file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_c_finalizer_test.dart:79
    #13 0x7fedc7a7acd2 in Payload.generate file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_c_finalizer_test.dart:79
    #14 0x7fedc7a7acd2 in Payload.generate file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_c_finalizer_test.dart:79
    #15 0x7fedc7a7acd2 in Payload.generate file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_c_finalizer_test.dart:79
    #16 0x7fedc7a7abe8 in FinalizerSplay.newPayload file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_c_finalizer_test.dart:50
    #17 0x7fedc7a7abe8 in Splay.insertNewNode file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_common.dart:57
    #18 0x7fedc7a7abe8 in Splay.setup file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_common.dart:62
    #19 0x7fedc7a7a96d in Splay.mainAsync file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_common.dart:104
    #20 0x7fedc7a7f2f8 in main file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_c_finalizer_test.dart:46
    #21 0x7fedc7a7f32a in main (#2) file:///b/s/w/ir/runtime/tests/vm/dart/gc/splay_c_finalizer_test.dart:39
    #22 0x7fedc7b2108c in _Closure.call (#2) dart:core-patch/function.dart
    #23 0x7fedc7a2b10a in _delayEntrypointInvocation.<anonymous closure> dart:isolate-patch/isolate_patch.dart:297
    #24 0x7fedc7b2139e in _Closure.call (#3) dart:core-patch/function.dart
    #25 0x7fedc7a823e9 in _RawReceivePort._handleMessage dart:isolate-patch/isolate_patch.dart:184
    #26 0x7fedc79d47f8 in stub InvokeDartCode /b/s/w/it8tl6m3fa/ccaQwAaF.o
    #27 0x55d398b4685e in dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&) out/ReleaseMSANX64/../../runtime/vm/dart_entry.cc:125:33
    #28 0x55d398b4a82b in dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&) out/ReleaseMSANX64/../../runtime/vm/dart_entry.cc:37:10
    #29 0x55d398b4a82b in dart::DartLibraryCalls::HandleMessage(long, dart::Instance const&) out/ReleaseMSANX64/../../runtime/vm/dart_entry.cc:718:28
    #30 0x55d398b823fa in dart::IsolateMessageHandler::HandleMessage(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::Message, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::Message>>) out/ReleaseMSANX64/../../runtime/vm/isolate.cc:1400:15
    #31 0x55d398b9d86a in dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) out/ReleaseMSANX64/../../runtime/vm/message_handler.cc:238:16
    #32 0x55d398b9e52b in dart::MessageHandler::TaskCallback() out/ReleaseMSANX64/../../runtime/vm/message_handler.cc:457:18
    #33 0x55d398de2175 in dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseMSANX64/../../runtime/vm/thread_pool.cc:158:15
    #34 0x55d398de2cc1 in dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseMSANX64/../../runtime/vm/thread_pool.cc:330:9
    #35 0x55d398cea591 in dart::ThreadStart(void*) out/ReleaseMSANX64/../../runtime/vm/os_thread_linux.cc:154:5
    #36 0x7fedc97cf608 in start_thread /build/glibc-wuryBv/glibc-2.31/nptl/pthread_create.c:477:8
    #37 0x7fedc957f352 in __clone /build/glibc-wuryBv/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

https://dart-ci.appspot.com/log/vm-aot-msan-linux-release-x64/vm-aot-msan-linux-release-x64/362/vm/dart/gc/splay_c_finalizer_test/12

Will start a bisection locally:

```
dart tools/bisect.dart \
-Dend=e7daade2913335534ea2cdcf9fbee1f74ec83d49 \
-Dstart=e2e6ee8b0264ef1809462033100b60fbeff148c0 \
-Dtest_command="python3 tools/build.py --sanitizer=msan -ax64 -mrelease runtime runtime_precompiled" \
-Dtest_command="python3 tools/test.py -n vm-aot-msan-linux-release-x64 vm/dart/gc/splay_c_finalizer_test/12" \
-Dfailure_string="use-of-uninitialized-value"
```

**Comment by dcharkes** [comment]
Commit range dfe0457f843...e2e6ee8b0264ef1809462033100b60fbeff148c0.
Ensuring SDK repo in /usr/local/google/home/dacoharkes/dart-sdk/sdk/.
Ensuring failure reproduces on e2e6ee8b0264ef1809462033100b60fbeff148c0.
Commit e2e6ee8b0264ef1809462033100b60fbeff148c0, reproduces failure.
Ensuring failure does not reproduce on dfe0457f843.
Commit dfe0457f843, does not reproduce failure.
Bisecting dfe0457f843...e2e6ee8b026 (23 commits). Trying af700baa49b.
Commit af700baa49b, does not reproduce failure.
Bisecting af700baa49b...e2e6ee8b026 (11 commits). Trying 1ab083ae487.
Commit 1ab083ae487, reproduces failure.
Bisecting af700baa49b...1ab083ae487 (6 commits). Trying a7831723fc8.
Commit a7831723fc8, does not reproduce failure.
Bisecting a7831723fc8...1ab083ae487 (3 commits). Trying 9becf403788.
Commit 9becf403788, does not reproduce failure.
Bisected to 1ab083ae487.

**Comment by mraleph** [comment]
I think the code used to work by chance rather than design - we don't actually unpoison handles we "create" on the stack for FFI calls, so unsurprisingly trying to read from those handles causes MSAN issues.

**Comment by mraleph** [comment]
Will be fixed by https://dart-review.googlesource.com/c/sdk/+/357340
