### ISSUE TITLE
[gardening] iso-stress failing on list length/index

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#55180]
It looks like we have errors with list lengths.

```
Spawning tests in isolates resulted in the following errors:
------------------------------------------------------------
[/b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/../../../tests/corelib/iterable_return_type_int64_test.dart] error: [Instance of 'RangeError', #0      RangeError.checkValidRange (dart:core/errors.dart:365)
#1      _IntListMixin.getRange (dart:typed_data-patch/typed_data_patch.dart:286)
#2      testList (file:///b/s/w/ir/cache/builder/sdk/tests/corelib/iterable_return_type_helper.dart:29)
#3      main (file:///b/s/w/ir/cache/builder/sdk/tests/corelib/iterable_return_type_int64_test.dart:14)
#4      wrapper343.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/generated_stress_test.dart:13356)
#5      _rootRun (dart:async/zone.dart:1399)
#6      _CustomZone.run (dart:async/zone.dart:1301)
#7      _runZoned (dart:async/zone.dart:1826)
#8      runZoned (dart:async/zone.dart:1763)
#9      wrapper343 (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/generated_stress_test.dart:13355)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
]
[/b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/../../../tests/corelib/iterable_return_type_test.dart] error: [Instance of 'RangeError', #0      RangeError.checkValidRange (dart:core/errors.dart:365)
#1      _IntListMixin.getRange (dart:typed_data-patch/typed_data_patch.dart:286)
#2      testList (file:///b/s/w/ir/cache/builder/sdk/tests/corelib/iterable_return_type_helper.dart:29)
#3      main (file:///b/s/w/ir/cache/builder/sdk/tests/corelib/iterable_return_type_test.dart:26)
#4      wrapper344.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/generated_stress_test.dart:13372)
#5      _rootRun (dart:async/zone.dart:1399)
#6      _CustomZone.run (dart:async/zone.dart:1301)
#7      _runZoned (dart:async/zone.dart:1826)
#8      runZoned (dart:async/zone.dart:1763)
#9      wrapper344 (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/generated_stress_test.dart:13371)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
]
[/b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/../../../tests/lib/typed_data/typed_data_list_test.dart] error: [Expect.listEquals(list length, expected: <3>, actual: <2>) fails: Next element <9.5>, #0      Expect._fail (package:expect/expect.dart:722)
#1      Expect.listEquals (package:expect/expect.dart:327)
#2      testListFunctions (file:///b/s/w/ir/cache/builder/sdk/tests/lib/typed_data/typed_data_list_test.dart:49)
#3      main (file:///b/s/w/ir/cache/builder/sdk/tests/lib/typed_data/typed_data_list_test.dart:174)
#4      wrapper3697.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/generated_stress_test.dart:67020)
#5      _rootRun (dart:async/zone.dart:1399)
#6      _CustomZone.run (dart:async/zone.dart:1301)
#7      _runZoned (dart:async/zone.dart:1826)
#8      runZoned (dart:async/zone.dart:1763)
#9      wrapper3697 (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/generated_stress_test.dart:67019)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8753634563104402417/+/u/collect_shards/Run_Isolate_Stress_Tests_shard_3/task_stdout_stderr:_Run_Isolate_Stress_Tests_shard_3

Test iterable_return_type_test hasn't been touched in years.

The tests in isolation have not started failing:

* https://dart-current-results.web.app/#/filter=corelib/iterable_return_type_test,lib/typed_data/typed_data_list_test,corelib/iterable_return_type_int64_test&showAll

This started failing tue on wed night. So probably a commit in https://github.com/dart-lang/sdk/compare/6ac3ba647bb8534fa94b79a33ba5d9535a7f9244~...6d12146e75d453051adace0c9d58dd2469f2f73e.

I don't see anything obvious, other than possible deep dart VM changes causing this such as https://github.com/dart-lang/sdk/commit/1ab083ae487af531d1e28fb8fd6d50fb71aaadf9 (fyi @mraleph).

@mkustermann is there a way to repro the iso stress tests locally?

**Comment by dcharkes** [comment]
I'll let @mraleph investigate the failures on https://github.com/dart-lang/sdk/commit/1ab083ae487af531d1e28fb8fd6d50fb71aaadf9 first. If the failure doesn't disappear after fixes or a revert on the next runs, I'll dive in to this one on the next gardening shift.

**Comment by mraleph** [comment]
This is caused by my change: there is a mismatch in the calling convention when invoking `_IntListMixin.getRange`: caller thinks the callee has 3 direct parameters - so it passes 3 arguments in registers, but callee has 2 direct parameters and 1 optional, so it can't deal with 3 direct parameters (it expects optional one on the stack).

I am reverting my change - to prevent this propagating through rolls and will look at fixing it next week.

**Comment by mraleph** [comment]
Note to self: this is a valid Dart code, so we need to traverse all overrides and take `min(direct_parameter_count)`. _sigh_

```dart
class A {
  void foo(int x) {
    
  }
}

class B extends A {
  void foo([int x = 10]) {
    
  }
}
```

**Comment by mraleph** [comment]
I have relaned the change with fixes.
