### ISSUE TITLE
The analysis server shut down unexpectedly

### ISSUE THREAD

**Issue by adityasaxen** [dart-lang/sdk#55193]
```
Computing fixes in adity (dry run)...
Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: The pipe is being closed.

, errno = 232)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:905:7)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:316:15)
#2      _rootRunUnary (dart:async/zone.dart:1415:13)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#8      _StreamController._add (dart:async/stream_controller.dart:658:7)
#9      _StreamController.add (dart:async/stream_controller.dart:606:5)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:154:17)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:287:5)
#12     _StdSink._write (dart:io/stdio.dart:401:13)
#13     _StdSink.writeln (dart:io/stdio.dart:419:5)
#14     ByteStreamServerChannel._outputLine.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:166:15)
#15     _rootRun (dart:async/zone.dart:1399:13)
#16     _CustomZone.run (dart:async/zone.dart:1301:19)
#17     _runZoned (dart:async/zone.dart:1804:10)
#18     runZonedGuarded (dart:async/zone.dart:1792:12)
#19     ByteStreamServerChannel._outputLine (package:analysis_server/src/channel/byte_stream_channel.dart:165:5)
#20     ByteStreamServerChannel.sendNotification (package:analysis_server/src/channel/byte_stream_channel.dart:131:5)
#21     LegacyAnalysisServer.sendStatusNotificationNew (package:analysis_server/src/legacy_analysis_server.dart:766:13)
#22     LegacyAnalysisServer.handleAnalysisStatusChange (package:analysis_server/src/legacy_analysis_server.dart:547:5)
#23     AnalysisServer.handleAnalysisEvent (package:analysis_server/src/analysis_server.dart:699:9)
#24     _rootRunUnary (dart:async/zone.dart:1415:13)
#25     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#28     _DelayedData.perform (dart:async/stream_impl.dart:541:14)
#29     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
#30     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
#31     _rootRun (dart:async/zone.dart:1391:47)
#32     _CustomZone.run (dart:async/zone.dart:1301:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#35     _rootRun (dart:async/zone.dart:1399:13)
#36     _CustomZone.run (dart:async/zone.dart:1301:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#41     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#42     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#43     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#44     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Bad state: The analysis server crashed unexpectedly
```

**Comment by adityasaxen** [comment]
what to do

**Comment by pq** [comment]
Hi! Sorry for the hassle. What version of Dart are you using?

Does the issue reproduce on the latest `dev` build?
