### ISSUE TITLE
co19/LanguageFeatures/Augmentation-libraries/applying_augmentation_library_A03_t02 crash in analyzer

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#55204]
Test [co19/LanguageFeatures/Augmentation-libraries/applying_augmentation_library_A03_t02](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Augmentation-libraries/applying_augmentation_library_A03_t02.dart) crashes the analyzer
``` 
/=============================================================================================================================\
| co19/LanguageFeatures/Augmentation-libraries/applying_augmentation_library_A03_t02 is new and failed (Crash, expected Pass) |
\=============================================================================================================================/

--- Command "dart2analyzer" (took 66ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/gen/dartanalyzer.dart.snapshot -Dtest_runner.configuration=analyzer-asserts-linux --enable-experiment=macros --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json --format=json /b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/Augmentation-libraries/applying_augmentation_library_A03_t02.dart

analyzer json parse result:
- parse failed

exit code:
253

stderr:
type 'LibraryAugmentationElementImpl' is not a subtype of type 'LibraryElementImpl' in type cast
#0      ErrorVerifier.visitLibraryDirective (package:analyzer/src/generated/error_verifier.dart:1033:32)
#1      LibraryDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:11229:50)
#2      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:13024:20)
#3      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3648:19)
#4      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:942:10)
#5      ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:549:11)
#6      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:3642:50)
#7      LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:422:10)
#8      LibraryAnalyzer._computeDiagnostics (package:analyzer/src/dart/analysis/library_analyzer.dart:286:7)
#9      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:104:5)
#10     AnalysisDriver._analyzeFile.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1366:11)
<asynchronous suspension>
#11     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#12     AnalysisDriver._getErrors (package:analyzer/src/dart/analysis/driver.dart:1712:5)
<asynchronous suspension>
#13     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1198:7)
<asynchronous suspension>
#14     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2373:7)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n analyzer-asserts-linux co19/LanguageFeatures/Augmentation-libraries/applying_augmentation_library_A03_t02
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/362663
