### ISSUE TITLE
Null check exceptions during json serialization during dry run

### ISSUE THREAD

**Issue by knopp** [dart-lang/sdk#55287]
CBuilder does not set architecture during dry run but it seems to be required during serialization:
```
Null check operator used on a null value
#0      NativeCodeAssetImpl.toJson (package:native_assets_cli/src/model/native_code_asset.dart:342:62)
#1      BuildOutputImpl.toJson (package:native_assets_cli/src/model/build_output.dart:96:46)
#2      BuildOutputImpl.toJsonString (package:native_assets_cli/src/model/build_output.dart:105:50)
#3      BuildOutputImpl.writeToFile (package:native_assets_cli/src/model/build_output.dart:155:24)
#4      build (package:native_assets_cli/src/api/build.dart:95:16)
<asynchronous suspension>
```

`DynamicLoadingBundledImpl` has permitted to have no file URI during dry run (which is good, as on Rust the location depends on architecture for example), but it fails during serialization:
```
Null check operator used on a null value
#0      DynamicLoadingBundledImpl.toJsonV1_0_0 (package:native_assets_cli/src/model/native_code_asset.dart:93:43)
#1      NativeCodeAssetImpl.toJson (package:native_assets_cli/src/model/native_code_asset.dart:341:21)
#2      BuildOutputImpl.toJson (package:native_assets_cli/src/model/build_output.dart:96:46)
#3      BuildOutputImpl.toJsonString (package:native_assets_cli/src/model/build_output.dart:105:50)
#4      BuildOutputImpl.writeToFile (package:native_assets_cli/src/model/build_output.dart:155:24)
#5      build (package:native_assets_cli/src/api/build.dart:95:16)
```

**Comment by knopp** [comment]
Closing in favor of https://github.com/dart-lang/native/issues/1053
