### ISSUE TITLE
Import recovery fails for "import augment" without a semicolon

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#55324]
I get an analysis server crash if I miss the semicolon off an `import augment` directive:

```dart
import augment 'main_augmentation.dart'
```

```
type 'AugmentationImportDirectiveImpl' is not a subtype of type 'ImportDirectiveImpl' in type cast
#0      AstBuilder.handleRecoverImport (package:analyzer/src/fasta/ast_builder.dart:5254:39)
#1      ForwardingListener.handleRecoverImport (package:_fe_analyzer_shared/src/parser/forwarding_listener.dart:1935:15)
#2      Parser.parseImportRecovery (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1025:16)
#3      Parser.parseImport (package:_fe_analyzer_shared/src/…
```

**Comment by DanTup** [comment]
Working on this at https://dart-review.googlesource.com/c/sdk/+/360044

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/360504 will add some more detailed tests, and the fix.

**Comment by DanTup** [comment]
Thanks!
