### ISSUE TITLE
Finalizer is called twice for the same object.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#55330]
It can be reproduced in flutter tests:

1. Enable leak tracking by replacing `if (_isLeakTrackingEnabled())` with `if (true)`.
2. Run test `SemanticsDebugger will schedule a frame`

See failure:
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown running a test (but after the test had completed):
Exception: The object 616336549 GCed twice

When the exception was thrown, this was the stack:
#0      ObjectRecord.setGCed (package:leak_tracker/src/leak_tracking/_object_record.dart:66:31)
#1      ObjectTracker._onObjectGarbageCollected (package:leak_tracker/src/leak_tracking/_object_tracker.dart:84:12)
#9      _FinalizerImpl._runFinalizers (dart:core-patch/finalizer_patch.dart:66:18)
#10     _FinalizerImpl._handleFinalizerMessage (dart:core-patch/finalizer_patch.dart:79:15)
(elided 7 frames from dart:async and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Flutter commit: c6f9cdf1564d4748388ce2eb21dabe5fbe8b2dd5

```
Flutter 3.21.0-16.0.pre.9 • channel master • git@github.com:flutter/flutter.git
Framework • revision c6f9cdf156 (29 hours ago) • 2024-03-27 14:08:21 -0400
Engine • revision b7dddee939
Tools • Dart 3.4.0 (build 3.4.0-275.0.dev) • DevTools 2.34.0-dev.12
```

See https://github.com/dart-lang/leak_tracker/pull/224

**Comment by polina-c** [comment]
Feel free to ping me directly to get help to repro this.

**Comment by a-siva** [comment]
//cc @rmacnak-google

**Comment by rmacnak-google** [comment]
It looks like the leak tracker is creating multiple attachments of the same object.

```
ATTACH finalizer=521096088 object=257107213 token=91537671
...
ATTACH finalizer=521096088 object=257107213 token=91537671
...
FINALIZE token=91537671
...
FINALIZE token=91537671
...
Exception: The object 257107213 GCed twice
```

This is working as intended. For example,

```
class ObjectRecord {
  int count = 0;
  onFinalization() {
    count++;
    if (count > 1) {
      print("Finalized twice!");
    }
  }
}

onFinalization(ObjectRecord record) {
  record.onFinalization();
}

var finalizer;
main() {
  finalizer = new Finalizer<ObjectRecord>(onFinalization);

  (){
     var object = Object();
     var token = ObjectRecord();
     finalizer.attach(object, token);
     finalizer.attach(object, token);
  }();
  
  gc();
}
```
prints "Finalized twice!". The second call to [attach](https://api.dart.dev/stable/3.3.3/dart-core/Finalizer/attach.html) does not remove the first attachment.

**Comment by polina-c** [comment]
Thank you!
