### ISSUE TITLE
Analyzer and compiler disagree about Future<T>? type parameter inference

### ISSUE THREAD

**Issue by dgreensp** [dart-lang/sdk#55344]
It seems if you pass a nullable type like `String?` to a generic function that takes a `FutureOr<T>?`, the analyzer will infer T to be `String`, but the compiler infers T to be `String?`.  This is the case even if `T extends Object`.  The analyzer's behavior is much preferable to the compiler's.

Here is an example:

```
import "dart:async";

Future<int?> maybeMap<T extends Object>(FutureOr<T>? input, int Function(T) function) async {
  if (input == null) {
    return null;
  } else if (input is Future<T>) {
    return function(await input);
  } else {
    return function(input);
  }
}

void main() async {
  final String? x = "foo";
  print(await maybeMap(x, (String s) => s.length));
}
```

In this code, what we want is for maybeMap to take a T, a `Future<T>` or null.  If you pass a `String?` as the first argument, and a function that takes a `String` as the second argument, once would hope T would be inferred to be String.  And indeed, the analyzer does so, and there are no errors.  The compiler, however, infers this to be a call to `maybeMap<String?>`, even though that doesn't conform to the bound (which it complains about), and even if we annotate the closure argument as `String s`.  If we don't annotate `s`, it complains that `s.length` is bad because `s` might be null.

**Comment by lrhn** [comment]
@stereotype441 Another nice discrepancy! (Unless it's already known.)

**Comment by johnniwinther** [comment]
cc @chloestefantsova

**Comment by eernstg** [comment]
It seems likely to me that the CFE is following the rules specified in [this section](https://github.com/dart-lang/language/blob/main/resources/type-system/inference.md#rules):

We're considering `String? <# FutureOr<T>? [T] -> C` (match `String?` against `FutureOr<T>?`, solving for `T`, which yields the constraints `C`). This matches the `Q0?` rule and yields `String <# FutureOr<T> [T] -> C`. This again yields `String <# T [T] -> C`, which shows that `C` is a singleton set containing the constraint `String <: T <: _`.

So the behavior of the analyzer may be preferable in practice in this case, but it doesn't seem to fit the algorithm in the feature specification.

Returning to @stereotype441, WDYT? ;-)

**Comment by chloestefantsova** [comment]
The issue is a bit more complicated than it seemed at first. The obvious fix for the CFE brings it in accordance with the specification, but reveals some breakage in the tests.

Consider the following program.

```dart
import "dart:async";

check(value) {
  new Future.value(value).then((x) {});
}

main() {
  check(null);
}
```

Neither of the tools, the Analyzer or the CFE, report a compile-time error for the program. Yet, due to the bug in the CFE, `dynamic` was inferred as the type argument for `Future.value` previously, allowing the `null` value. With the fix, `Object` is inferred, making the project crash at runtime.

```
Unhandled exception:
type 'Null' is not a subtype of type 'Object' in type cast
#0      new Future.value (dart:async/future.dart:348:59)
#1      check (file:///tmp/foo.dart:4:7)
#2      main (file:///tmp/foo.dart:8:3)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

I'm currently investigating the scope of the potential breakage the fix might cause.

**Comment by bwilkerson** [comment]
I removed the `area-analyzer` label. Let us know if there's work that needs to be done on the analyzer side.
