### ISSUE TITLE
`arm` build failure on `x64` host

### ISSUE THREAD

**Issue by jwinarske** [dart-lang/sdk#55354]
SDK build fails when cross compiling for `arm` on a `x64` Linux host.

```
| DEBUG: Executing shell function do_compile
| NOTE: target_os = "linux"
| host_cpu = "x86"
| target_cpu = "arm"
| dart_target_arch = "arm"
| dart_use_compressed_pointers = false
| dart_use_crashpad = false
| dart_snapshot_kind = "kernel"
| dart_use_fallback_root_certificates = true
| bssl_use_clang_integrated_as = true
| arm_version = 7
| arm_float_abi = "hard"
| arm_use_neon = true
| is_debug = false
| is_release = false
| is_product = true
| dart_debug = false
| dart_runtime_mode = "release"
| exclude_kernel_service = false
| is_clang = true
| dart_vm_code_coverage = false
| is_asan = false
| is_lsan = false
| is_msan = false
| is_tsan = false
| is_ubsan = false
| is_qemu = false
| dart_stripped_binary = "exe.stripped/dart"
| dart_precompiled_runtime_stripped_binary =
|     "exe.stripped/dart_precompiled_runtime_product"
| gen_snapshot_stripped_binary = "exe.stripped/gen_snapshot_product"
| analyze_snapshot_binary = "exe.stripped/analyze_snapshot"
| wasm_opt_stripped_binary = "exe.stripped/wasm-opt"
| dart_sysroot = "debian"
| use_goma = false
| goma_dir = "None"
| use_rbe = false
| verify_sdk_hash = true
| dart_version_git_info = true
| ninja: Entering directory `/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM'
| [1/66] STAMP obj/runtime/bin/dart_kernel_platform_cc.stamp
| [2/66] ACTION //utils/gen_kernel:gen_kernel(//build/toolchain/linux:clang_arm)
| FAILED: gen/gen_kernel_aot.dart.snapshot
| python3 ../../build/gn_run_binary.py compiled_action clang_x86/gen_snapshot_product --deterministic --snapshot-kind=app-aot-elf --elf=/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/gen/gen_kernel_aot.dart.snapshot /mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/gen/utils/gen_kernel/gen_kernel.dart.dill
| Traceback (most recent call last):
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 24, in run_command
|     subprocess.check_output(command, stderr=subprocess.STDOUT)
|   File "/usr/lib64/python3.12/subprocess.py", line 466, in check_output
|     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/lib64/python3.12/subprocess.py", line 548, in run
|     with Popen(*popenargs, **kwargs) as process:
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
|     self._execute_child(args, executable, preexec_fn, close_fds,
|   File "/usr/lib64/python3.12/subprocess.py", line 1953, in _execute_child
|     raise child_exception_type(errno_num, err_msg, err_filename)
| FileNotFoundError: [Errno 2] No such file or directory: '/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/clang_x86/gen_snapshot_product'
| 
| During handling of the above exception, another exception occurred:
| 
| Traceback (most recent call last):
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 67, in <module>
|     sys.exit(main(sys.argv))
|              ^^^^^^^^^^^^^^
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 59, in main
|     result = run_command(args)
|              ^^^^^^^^^^^^^^^^^
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 31, in run_command
|     _decode(e.strerror))
|     ^^^^^^^^^^^^^^^^^^^
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 35, in _decode
|     return bytes.decode("utf-8")
|            ^^^^^^^^^^^^
| AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
| [3/66] ACTION //runtime/bin:generate_snapshot_bin(//build/toolchain/linux:clang_arm)
| FAILED: gen/runtime/bin/vm_snapshot_data.bin gen/runtime/bin/vm_snapshot_instructions.bin gen/runtime/bin/isolate_snapshot_data.bin gen/runtime/bin/isolate_snapshot_instructions.bin
| python3 ../../build/gn_run_binary.py compiled_action clang_x86/gen_snapshot --sound-null-safety --deterministic --snapshot_kind=core --vm_snapshot_data=gen/runtime/bin/vm_snapshot_data.bin --vm_snapshot_instructions=gen/runtime/bin/vm_snapshot_instructions.bin --isolate_snapshot_data=gen/runtime/bin/isolate_snapshot_data.bin --isolate_snapshot_instructions=gen/runtime/bin/isolate_snapshot_instructions.bin vm_platform_strong_stripped.dill
| Traceback (most recent call last):
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 24, in run_command
|     subprocess.check_output(command, stderr=subprocess.STDOUT)
|   File "/usr/lib64/python3.12/subprocess.py", line 466, in check_output
|     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/lib64/python3.12/subprocess.py", line 548, in run
|     with Popen(*popenargs, **kwargs) as process:
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
|     self._execute_child(args, executable, preexec_fn, close_fds,
|   File "/usr/lib64/python3.12/subprocess.py", line 1953, in _execute_child
|     raise child_exception_type(errno_num, err_msg, err_filename)
| FileNotFoundError: [Errno 2] No such file or directory: '/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/clang_x86/gen_snapshot'
| 
| During handling of the above exception, another exception occurred:
| 
| Traceback (most recent call last):
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 67, in <module>
|     sys.exit(main(sys.argv))
|              ^^^^^^^^^^^^^^
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 59, in main
|     result = run_command(args)
|              ^^^^^^^^^^^^^^^^^
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 31, in run_command
|     _decode(e.strerror))
|     ^^^^^^^^^^^^^^^^^^^
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 35, in _decode
|     return bytes.decode("utf-8")
|            ^^^^^^^^^^^^
| AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
| [4/66] ACTION //utils/kernel-service:frontend_server_aot(//build/toolchain/linux:clang_arm)
| FAILED: frontend_server_aot.dart.snapshot
| python3 ../../build/gn_run_binary.py compiled_action clang_x86/gen_snapshot_product --deterministic --snapshot-kind=app-aot-elf --elf=/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/frontend_server_aot.dart.snapshot /mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/gen/utils/kernel-service/frontend_server_aot.dart.dill
| Traceback (most recent call last):
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 24, in run_command
|     subprocess.check_output(command, stderr=subprocess.STDOUT)
|   File "/usr/lib64/python3.12/subprocess.py", line 466, in check_output
|     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/lib64/python3.12/subprocess.py", line 548, in run
|     with Popen(*popenargs, **kwargs) as process:
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
|     self._execute_child(args, executable, preexec_fn, close_fds,
|   File "/usr/lib64/python3.12/subprocess.py", line 1953, in _execute_child
|     raise child_exception_type(errno_num, err_msg, err_filename)
| FileNotFoundError: [Errno 2] No such file or directory: '/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/clang_x86/gen_snapshot_product'
| 
| During handling of the above exception, another exception occurred:
| 
| Traceback (most recent call last):
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 67, in <module>
|     sys.exit(main(sys.argv))
|              ^^^^^^^^^^^^^^
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 59, in main
|     result = run_command(args)
|              ^^^^^^^^^^^^^^^^^
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 31, in run_command
|     _decode(e.strerror))
|     ^^^^^^^^^^^^^^^^^^^
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 35, in _decode
|     return bytes.decode("utf-8")
|            ^^^^^^^^^^^^
| AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
| [5/66] ACTION //utils/dds:generate_dds_aot_snapshot(//build/toolchain/linux:clang_arm)
| FAILED: gen/dds_aot.dart.snapshot
| python3 ../../build/gn_run_binary.py compiled_action clang_x86/gen_snapshot_product --deterministic --snapshot-kind=app-aot-elf --elf=/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/gen/dds_aot.dart.snapshot /mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/gen/utils/dds/generate_dds_aot_snapshot.dart.dill
| Traceback (most recent call last):
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 24, in run_command
|     subprocess.check_output(command, stderr=subprocess.STDOUT)
|   File "/usr/lib64/python3.12/subprocess.py", line 466, in check_output
|     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/lib64/python3.12/subprocess.py", line 548, in run
|     with Popen(*popenargs, **kwargs) as process:
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
|     self._execute_child(args, executable, preexec_fn, close_fds,
|   File "/usr/lib64/python3.12/subprocess.py", line 1953, in _execute_child
|     raise child_exception_type(errno_num, err_msg, err_filename)
| FileNotFoundError: [Errno 2] No such file or directory: '/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/clang_x86/gen_snapshot_product'
| 
| During handling of the above exception, another exception occurred:
| 
| Traceback (most recent call last):
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 67, in <module>
|     sys.exit(main(sys.argv))
|              ^^^^^^^^^^^^^^
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 59, in main
|     result = run_command(args)
|              ^^^^^^^^^^^^^^^^^
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 31, in run_command
|     _decode(e.strerror))
|     ^^^^^^^^^^^^^^^^^^^
|   File "/mnt/raid10/yocto/master/bbb/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/dart-sdk/3.3.1/sdk/out/ProductXARM/../../build/gn_run_binary.py", line 35, in _decode
|     return bytes.decode("utf-8")
|            ^^^^^^^^^^^^
| AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
```

args.gn is populating host_cpu value to x86, instead of x64.  When manually set to x64 the build completes without error.

tools/pn.py HostCpuForArch is assigning the incorrect value.

**Comment by jwinarske** [comment]
Passing `--arch arm_x64` to ./tools/gn.py resolves the problem.
