### ISSUE TITLE
The result of the cascade operator is not expected

### ISSUE THREAD

**Issue by microtears** [dart-lang/sdk#55358]
Consider the following example：

```code
import 'package:vm_service_protos/vm_service_protos.dart';

void main() {
  var event = TrackEvent();
  var packet = TracePacket()
    ..trackEvent = event
    ..trackDescriptor = TrackDescriptor();

  assert(!event.isFrozen);
  assert(!packet.trackEvent.isFrozen);
}
```

The desired result is that the assertion succeeds.

But the current result is that:

```dart
dart --enable-asserts run example/issue.dart

Unhandled exception:
'file:///***/example/issue.dart': Failed assertion: line 10 pos 10: '!packet.trackEvent.isFrozen': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      main (file:///***/example/issue.dart:10:10)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

And when we remove the sixth line, the assertion succeeds again：

```dart
import 'package:vm_service_protos/vm_service_protos.dart';

void main() {
  var event = TrackEvent();
  var packet = TracePacket()
    ..trackEvent = event;

  assert(!event.isFrozen);
  assert(!packet.trackEvent.isFrozen);
}

```

<details>

<summary>dart info</summary>

```plain

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.0-7.0.dev (dev) (Mon Apr 1 13:03:18 2024 -0700) on "macos_arm64"
- on macos / Version 14.1 (Build 23B74)
- locale is zh-Hans-CN

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                               |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|  56 MB | 0.0% |        09:45 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/ZFkhxbMUwenWXcxb --port 9277 |
| 777 MB | 0.0% |        09:45 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.85.20240327     |
|  32 MB | 0.0% |        09:45 | dart tooling-daemon --machine                                                              |
|  78 MB | 0.0% |        09:45 | flutter_tools.snapshot daemon                                                              |
```
</details>

**Comment by lrhn** [comment]
I believe this is working as intended. It's unrelated to cascades, you'll get the same behavior from
```dart
var package = TracePacket();
package.trackEvent = event;
package.trackDescriptor = TrackDescriptor();
```
The reason the `packet.trackEvent` is frozen is that `trackEvent` and `trackDescriptor` are part of the same "one of" group, which means at most one of them can be set at any time. When you set `trackDescriptor`, it clears `trackEvent`.

When you then read `trackEvent`, it gives you a *default value* instead, since it can't return `null`, and that default value is a fresh frozen `TrackEvent`.

You can check this by adding:
```dart
 assert(!packet.hasTrackEvent());
```
and see that that assert succeeds. (Really should be a getter!)

**Comment by microtears** [comment]
@lrhn Thank you very much for your answer, and I have learned new knowledge about "one of" here.
