### ISSUE TITLE
dart2wasm fails with complex yield statements

### ISSUE THREAD

**Issue by IchordeDionysos** [dart-lang/sdk#55397]
## Error:

```
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
*NOTE*: Compilation to WasmGC is experimental.
The support may change, or be removed, with no advance notice.


Unhandled exception:
Yield statement in async function: YieldStatement(yield* combinedFolded;) (file:///Users/dennis/develop/wasm_test/lib/main.dart:123:7)
#0      AsyncCodeGenerator.visitYieldStatement (package:dart2wasm/async.dart:1240)
#1      YieldStatement.accept (package:kernel/ast.dart:10484)
#2      _YieldFinder.recurse (package:dart2wasm/async.dart:41)
#3      _YieldFinder.visitBlock (package:dart2wasm/async.dart:54)
#4      Block.accept (package:kernel/ast.dart:9247)
#5      _YieldFinder.recurse (package:dart2wasm/async.dart:41)
#6      _YieldFinder.visitIfStatement (package:dart2wasm/async.dart:76)
#7      IfStatement.accept (package:kernel/ast.dart:10141)
#8      _YieldFinder.recurse (package:dart2wasm/async.dart:41)
#9      _YieldFinder.visitBlock (package:dart2wasm/async.dart:54)
#10     Block.accept (package:kernel/ast.dart:9247)
#11     _YieldFinder.recurse (package:dart2wasm/async.dart:41)
#12     _YieldFinder.visitTryCatch (package:dart2wasm/async.dart:114)
#13     TryCatch.accept (package:kernel/ast.dart:10258)
#14     _YieldFinder.recurse (package:dart2wasm/async.dart:41)
#15     _YieldFinder.visitTryFinally (package:dart2wasm/async.dart:103)
#16     TryFinally.accept (package:kernel/ast.dart:10420)
#17     _YieldFinder.recurse (package:dart2wasm/async.dart:41)
#18     _YieldFinder.visitBlock (package:dart2wasm/async.dart:54)
#19     Block.accept (package:kernel/ast.dart:9247)
#20     _YieldFinder.recurse (package:dart2wasm/async.dart:41)
#21     _YieldFinder.visitBlock (package:dart2wasm/async.dart:54)
#22     Block.accept (package:kernel/ast.dart:9247)
#23     _YieldFinder.recurse (package:dart2wasm/async.dart:41)
#24     _YieldFinder.find (package:dart2wasm/async.dart:30)
#25     AsyncCodeGenerator._generateBodies (package:dart2wasm/async.dart:557)
#26     AsyncCodeGenerator.generateLambda (package:dart2wasm/async.dart:551)
#27     Translator.translate (package:dart2wasm/translator.dart:389)
#28     compileToModule (package:dart2wasm/compile.dart:186)
<asynchronous suspension>
#29     generateWasm (package:dart2wasm/generate_wasm.dart:24)
<asynchronous suspension>
#30     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/dart2wasm/bin/dart2wasm.dart:10)
<asynchronous suspension>
  Command: /Users/dennis/develop/bin/flutter/bin/cache/dart-sdk/bin/dart compile wasm --packages=.dart_tool/package_config.json
  --extra-compiler-option=--dart-sdk=/Users/dennis/develop/bin/flutter/bin/cache/dart-sdk
  --extra-compiler-option=--platform=/Users/dennis/develop/bin/flutter/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill --extra-compiler-option=--delete-tostring-package-uri=dart:ui
  --extra-compiler-option=--delete-tostring-package-uri=package:flutter --extra-compiler-option=--import-shared-memory --extra-compiler-option=--shared-memory-max-pages=32768 -Ddart.vm.product=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/605b3f35fa0a8e427935dc6ea4c99a4ddb1d33dd/ -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false
  -DFLUTTER_WEB_USE_SKWASM=true --extra-compiler-option=--depfile=/Users/dennis/develop/wasm_test/.dart_tool/flutter_build/45d80a6f171990f50d319b046a8c8833/dart2wasm.d -O4 --no-name-section -o
  /Users/dennis/develop/wasm_test/.dart_tool/flutter_build/45d80a6f171990f50d319b046a8c8833/main.dart.wasm
  /Users/dennis/develop/wasm_test/.dart_tool/flutter_build/45d80a6f171990f50d319b046a8c8833/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:321:19)
<asynchronous suspension>
#2      Dart2WasmTarget.build (package:flutter_tools/src/build_system/targets/web.dart:329:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             11.4s
Error: Failed to compile application for the Web.

```

## Steps to reproduce:

1. Create example Flutter app
2. Copy example main.dart from below
3. Install `stream_transform: 2.1.0`
4. Run `flutter build web --wasm`

<details><summary>Example App</summary>
<p>

```dart
import 'package:flutter/material.dart';
import 'package:stream_transform/stream_transform.dart';

void main() {
  runApp(const MyApp());
}

class GetUser {
  GetUser();

  Stream<String?> call() => Stream.value('user-a');
}

class Presentation {
  const Presentation({
    required this.id,
    required this.name,
    required this.components,
  });

  final String id;
  final String name;
  final List<String> components;
}

class ContentRepo {
  Stream<Presentation> getPresentation(
    String? user,
    String presentationId,
  ) async* {
    yield const Presentation(
      id: 'presentation-1',
      name: 'Example presentation',
      components: [
        'The content of the presentation',
        'some content',
        'End of content',
      ],
    );
  }
}

enum _State {
  loading,
  content,
}

class _LoadingValue {
  _LoadingValue(this.list, this.state);

  final List<String>? list;
  final _State state;
}

class GetPresentation {
  GetPresentation(this._repo, this._getUser);

  final ContentRepo _repo;
  final GetUser _getUser;

  Stream<Presentation> call({
    required String presentationId,
  }) async* {
    final user = await _getUser().first;
    yield* _repo.getPresentation(user, presentationId);
  }
}

class GetSummaryOfTopics {
  GetSummaryOfTopics(this._getUser, this._getTopicPresentation);

  final GetUser _getUser;
  final GetPresentation _getTopicPresentation;

  Stream<List<String>> call({
    required List<String> presentationIds,
  }) async* {
    final user = await _getUser().first;

    final topicsPresentationComponentsStreams = presentationIds
        .map((presentationId) {
          if (presentationId != null) {
            return _getTopicPresentation(
              presentationId: presentationId,
            )
                .map((presentation) {
                  return [
                    if (presentation.components.isNotEmpty) presentationId,
                    ...presentation.components,
                  ];
                })
                .map((list) => _LoadingValue(list, _State.content))
                .startWith(_LoadingValue(null, _State.loading));
          } else {
            return Stream.value(_LoadingValue([], _State.content));
          }
        })
        .map((stream) => stream.asBroadcastStream())
        .toList();

    // No content in content topics.
    if (topicsPresentationComponentsStreams.isEmpty) {
      yield <String>[];
    } else {
      final remainingStreams = topicsPresentationComponentsStreams.length > 1
          ? topicsPresentationComponentsStreams.sublist(1)
          : <Stream<_LoadingValue>>[];

      final combinedComponentsStream = topicsPresentationComponentsStreams.first
          .combineLatestAll(remainingStreams);

      final combinedFolded =
          combinedComponentsStream.asyncExpand((list) async* {
        if (list.any((element) => element.state == _State.content)) {
          final contentElements = list
              .map((e) => e.list ?? [])
              .fold<List<String>>([],
                  (previousValue, element) => [...previousValue, ...element]);
          yield contentElements;
        }
      });

      yield* combinedFolded;
    }
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    GetSummaryOfTopics(
      GetUser(),
      GetPresentation(ContentRepo(), GetUser()),
    )(
      presentationIds: ['presentation-a', 'presentation-b'],
    ).listen((data) {
      print(data);
    });
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const Placeholder(),
    );
  }
}
```

</p>
</details> 

## Environment

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel main, 3.22.0-5.0.pre.54, on macOS 14.3 23D56 darwin-arm64, locale en-DE)
    • Flutter version 3.22.0-5.0.pre.54 on channel main at /Users/dennis/develop/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 98d23f709f (15 hours ago), 2024-04-06 14:51:23 -0700
    • Engine revision 605b3f35fa
    • Dart version 3.5.0 (build 3.5.0-18.0.dev)
    • DevTools version 2.34.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/dennis/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Users/dennis/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
    • IntelliJ at /Users/dennis/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.3 23D56 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</p>
</details> 

<details><summary>dart info</summary>
<p>

```
If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.0-18.0.dev (dev) (Wed Apr 3 13:07:15 2024 -0700) on "macos_arm64"
- on macos / Version 14.3 (Build 23D56)
- locale is en-DE

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                               |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|  27 MB | 0.0% |        10:03 | dart language-server --client-id=IntelliJ-IDEA --client-version=IU-232.9559.62 --protocol=analyzer |
|  45 MB | 0.0% |        05:20 | dart language-server --client-id=IntelliJ-IDEA --client-version=IU-232.9559.62 --protocol=analyzer |
|  35 MB | 0.0% |        17:08 | flutter_tools.snapshot daemon                                                              |
|  39 MB | 0.0% |        05:21 | flutter_tools.snapshot daemon                                                              |
```

</p>
</details>

**Comment by osa1** [comment]
Smaller repro:

```dart
Stream<List<String>> stream() async* {
  yield ['a', 'b'];
}

Stream<List<String>> test() async* {
  final combinedFolded = stream().asyncExpand((list) async* {
    yield list;
  });

  yield* combinedFolded;
}

void main() async {
  print(await test().toList());
}
```

While trying to minimize the repro I also managed to come up with a version that crashes in runtime:

```dart
Stream<List<String>> stream() async* {
  yield ['a', 'b'];
}

Stream<List<String>> test() async* {
  yield* stream();
}

void main() async {
  print(await test().toList());
}
```

Output:

```
wasm-function[302]:0xe42e: RuntimeError: illegal cast
RuntimeError: illegal cast
    at StringBase._concatRangeFallback (wasm://wasm/00097e82:wasm-function[302]:0xe42e)
    at StringBase.concatRange (wasm://wasm/00097e82:wasm-function[299]:0xe372)
    at StringBuffer.toString (wasm://wasm/00097e82:wasm-function[287]:0xdf94)
    at Iterable.iterableToFullString (wasm://wasm/00097e82:wasm-function[323]:0xeb4d)
    at ListBase.listToString (wasm://wasm/00097e82:wasm-function[322]:0xea8a)
    at ListBase.toString (wasm://wasm/00097e82:wasm-function[308]:0xe6d8)
    at JSStringImpl._interpolate (wasm://wasm/00097e82:wasm-function[226]:0xd2d0)
    at StringBuffer.write (wasm://wasm/00097e82:wasm-function[290]:0xe003)
    at StringBuffer.writeAll (wasm://wasm/00097e82:wasm-function[327]:0xec99)
    at Iterable.iterableToFullString (wasm://wasm/00097e82:wasm-function[323]:0xeae8)
```

They're probably the same bug, just causing different kinds of crashes.

**Comment by osa1** [comment]
Fix in https://dart-review.googlesource.com/c/sdk/+/361600.
