### ISSUE TITLE
Cannot use factory constructor in augmented class

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#55432]
```dart
class Bar {
}

augment class Bar {
  const factory Bar() = Foo; // 🔥 warning: error: The name of a factory constructor must be the same as the name of the immediately enclosing class. (invalid_factory_name_not_a_class at [macros_playground] lib/main.dart:26)
}

class Foo implements Bar {
  const Foo();
}
```

The analyzer complains about the line marked with 🔥.

**Comment by goderbauer** [comment]
This also crashes during compilation:

```
org-dartlang-augmentation:/Users/goderbauer/dev/scratchpad/macros_playground/lib/main.dart-1:12:8: Error: Couldn't find constructor 'Foo'.
  }) = Foo;
       ^
org-dartlang-augmentation:/Users/goderbauer/dev/scratchpad/macros_playground/lib/main.dart-1:12:8: Error: Redirection constructor target not found: 'Foo'
  }) = Foo;
       ^
Unhandled exception:
Crash when compiling:
org-dartlang-augmentation:/Users/goderbauer/dev/scratchpad/macros_playground/lib/main.dart-1:8:17: Internal problem: Expected 'null', but got 'ReturnStatement'.
  const factory Bar({
                ^

#0      internalProblem (package:front_end/src/fasta/problems.dart:52)
#1      unexpected (package:front_end/src/fasta/problems.dart:78)
#2      RedirectingFactoryBuilder.setRedirectingFactoryBody (package:front_end/src/fasta/source/source_factory_builder.dart:384)
#3      ClassDeclarationMixin.resolveConstructors (package:front_end/src/fasta/source/class_declaration.dart:161)
#4      SourceLibraryBuilder.resolveConstructors (package:front_end/src/fasta/source/source_library_builder.dart:1652)
#5      SourceLibraryBuilder.resolveConstructors (package:front_end/src/fasta/source/source_library_builder.dart:1645)
#6      SourceLoader.resolveConstructors (package:front_end/src/fasta/source/source_loader.dart:1773)
#7      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:519)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:424)
<asynchronous suspension>
#10     _buildInternal (package:front_end/src/kernel_generator_impl.dart:150)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#12     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#13     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#14     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#15     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50)
<asynchronous suspension>
#16     compileToKernel (package:vm/kernel_front_end.dart:469)
<asynchronous suspension>
#17     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:639)
<asynchronous suspension>
#18     starter (package:frontend_server/starter.dart:101)
<asynchronous suspension>
#19     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/362603

**Comment by goderbauer** [comment]
As of Dart SDK version: 3.5.0-65.0.dev the analyzer warning is gone, but compilation still crashes:

```
Unhandled exception:
Crash when compiling:
org-dartlang-augmentation:/Users/goderbauer/dev/scratchpad/macros_playground/lib/main.dart-1:9:15: Internal problem: Expected 'null', but got 'ReturnStatement'.
const factory Counter({
              ^

#0      internalProblem (package:front_end/src/fasta/problems.dart:52)
#1      unexpected (package:front_end/src/fasta/problems.dart:78)
#2      RedirectingFactoryBuilder.setRedirectingFactoryBody (package:front_end/src/fasta/source/source_factory_builder.dart:384)
#3      ClassDeclarationMixin.resolveConstructors (package:front_end/src/fasta/source/class_declaration.dart:161)
#4      SourceLibraryBuilder.resolveConstructors (package:front_end/src/fasta/source/source_library_builder.dart:1652)
#5      SourceLibraryBuilder.resolveConstructors (package:front_end/src/fasta/source/source_library_builder.dart:1645)
#6      SourceLoader.resolveConstructors (package:front_end/src/fasta/source/source_loader.dart:1773)
#7      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:519)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:424)
<asynchronous suspension>
#10     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:367)
<asynchronous suspension>
#11     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:130)
<asynchronous suspension>
#12     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:77)
<asynchronous suspension>
#13     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:617)
<asynchronous suspension>
#14     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1311)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
```
