### ISSUE TITLE
Create an issue

### ISSUE THREAD

**Issue by nikeokoronkwo** [dart-lang/sdk#55435]
## Overview
This issue concerns the `ffi` package and library and is about the dynamic library lookup functionality.
Apparently, I was working on a project, and it failed to work on Linux because the ffi tools were not able to find the functions that `ffigen` had created ffi bindings for. 
Just to confirm the issue wasn't from the library, I ran `nm -gD <library-file>` and noticed that the function was indeed in the dynamic library file. 

This issue is currently being tracked in the project repository: nima-code/seagort#1

#### General info

- Dart 3.3.3 (stable) on "linux"
- locale is en_US

#### Project info

- sdk constraint: '^3.0.0'
- dependencies: ffi, path, test
- dev_dependencies: ffigen

## Steps to Reproduce
To build this project, you would need to have the rust set of tools, primarily `cargo`, to generate the shared library. You can as well run the **Seagort Test Run** on Github Actions [here](https://github.com/nima-code/seagort/actions).

With a fresh clone of the repository at https://github.com/nima-code/seagort,
1. Build the engine at `utils/engine` using `cargo`
```bash
cargo build --release
```
If you would want to regenerate the ffigen bindings for the header file, you can regenerate the header file using [`cbindgen`]() (to install: `cargo install --force cbindgen`)
```bash
cbindgen --config cbindgen.toml --lang c --output libseagort.h
```
2. Copy the generated library (at `target/release`) into the `bridge/linux` directory.
3. Run the example code.
```bash
dart example/main.dart
```

## Expected Outcome
The example code runs and the program exits successfully

## Observed Outcome
The code doesn't run and the following error message is provided.
```log
Unhandled exception:
Invalid argument(s): Couldn't resolve native function 'compile_js' in 'package:seagort/src/native/library.dart' : No asset with id 'package:seagort/src/native/library.dart' found. No available native assets. Attempted to fallback to process lookup. dart: undefined symbol: compile_js.

#0      Native._ffi_resolver.#ffiClosure0 (dart:ffi-patch/ffi_patch.dart)
#1      Native._ffi_resolver_function (dart:ffi-patch/ffi_patch.dart:1386:20)
#2      compile_js (package:seagort/src/native/library.dart)
#3      _compileJS (package:seagort/src/lib/compile.dart:9:18)
#4      compileJavaSript (package:seagort/src/lib/compile.dart:17:39)
#5      compileJS (package:seagort/src/js.dart:4:32)
#6      main (file:///home/runner/work/seagort/seagort/example/main.dart:4:3)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
Hence, the given bug.

If this issue isn't fixed or addressed, the project won't be able to be used or run for Linux users.

**Comment by mraleph** [comment]
You are already getting help on https://github.com/dart-lang/native/issues/1087

So I am going to close this one.
