### ISSUE TITLE
VM DateTime fails to support 1 microsecond before epoch

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#55438]
Example:
```dart
void main() {
  print(DateTime.utc(1969, 12, 31, 23, 59, 59, 999, 999));
}
```
fails with:
```
Unhandled exception:
Invalid argument(s)
#0      new DateTime._internal (dart:core-patch/date_patch.dart:54:23)
#1      new DateTime.utc (dart:core/date_time.dart:217:14)
#2      main (file:///usr/local/google/home/lrn/dart/sdk/sdk/dev/dtb.dart:2:18)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Likely caused by the code:
```dart
  @patch
  DateTime._internal(int year, int month, int day, int hour, int minute,
      int second, int millisecond, int microsecond, bool isUtc)
      : this.isUtc = checkNotNullable(isUtc, "isUtc"),
        this._value = _brokenDownDateToValue(year, month, day, hour, minute,
                second, millisecond, microsecond, isUtc) ??
            -1 {
    if (_value == -1) throw new ArgumentError();
  }
```
Nice hack, but the sentinel value is within the valid range.
Consider using `-_maxMillisecondsSinceEpoch - 1` as sentinel instead.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/362301 with the suggested fix. Thanks @lrhn!
