### ISSUE TITLE
Using not Code for DeclarationCode.fromParts()

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#55441]
From https://docs.google.com/document/d/1x13R1AsPtbF06oq-iE91EUrygqUDsnfRI8X3jdTkmjI
```
Passing MethodDeclaration.returnType to MemberDeclarationBuilder.declareInType(DeclarationCode.fromParts( ... ))
causes the analyzer server to hang. Generated code stops updating until the analyzer server is restarted.

It's hard to discover that you in fact need to pass MethodDeclaration.returnType.code here. The generic typing 
of List<Object> for the argument of  DeclarationCode.fromParts is not helpful.
```

**Comment by scheglov** [comment]
Interesting, I don't see a hard hang in unit tests for the element model and resolution.
But when I do it in IntelliJ, DAS sends server error.
```
## Dart analysis issue

Bad state: Unrecognized code part Instance of 'NamedTypeAnnotationImpl'

## Version information

- Dart SDK 3.5.0-edge.9315ae565160afea5ae049bde6aacd0cc077b07d
- Dart IntelliJ 241.15845
- IntelliJ IDEA 2024.1
- Mac OS X 14.4.1

## Details

Bad state: Unrecognized code part Instance of 'NamedTypeAnnotationImpl'

```
#0      SerializeCode.serialize (package:_macros/src/executor/serialization_extensions.dart:609:13)
#1      MacroExecutionResultImpl.serialize (package:_macros/src/executor/response_impls.dart:479:22)
#2      SerializeNullable.serializeNullable (package:_macros/src/executor/serialization_extensions.dart:495:12)
#3      SerializableResponse.serialize (package:_macros/src/executor/protocol.dart:136:18)
#4      MacroExpansionClient._handleMessage.<anonymous closure> (package:_macros/src/executor/client.dart:136:16)
<asynchronous suspension>
#5      MacroExpansionClient._handleMessage (package:_macros/src/executor/client.dart:118:5)
<asynchronous suspension>
```

## Debug log

```
1712867529318 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1712867529344 <= {"event":"analysis.errors","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file":"/Users/scheglov/da...
1712867529345 <= {"event":"analysis.highlights","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":11},{"type":"BUILT_IN","offset":0,"length...
1712867529345 <= {"event":"analysis.navigation","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","regions":[{"offset":30,"length":1,"targets":[0]},{"offset":41,"length":3,"targets":[1]}],"t...
1712867529345 <= {"event":"analysis.outline","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","location":{"f...
1712867529345 <= {"event":"analysis.overrides","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","overrides":[]}}
1712867529378 <= {"id":"19590","result":{"replacementOffset":8,"replacementLength":1,"suggestions":[{"kind":"IMPORT","relevance":900,"completion":"append.dart","selectionOffset":11,"selectionLength":0...
1712867529382 <= {"event":"analysis.errors","params":{"file":"/Users/scheglov/dart/test/bin/test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file":"/Users/scheglov/dar...
1712867529413 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1712867529414 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1712867529414 <= {"event":"analysis.implemented","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","classes":[],"members":[]}}
1712867529443 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1712867530127 => {"id":"19591","method":"analysis.updateContent","params":{"files":{"/Users/scheglov/dart/test/bin/test3.dart":{"type":"add","content":"import 'appen';\n\n@CrashMe()\nclass A {\n  void...
1712867530130 <= {"id":"19591","result":{}}
1712867530130 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1712867530169 <= {"event":"analysis.errors","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file":"/Users/scheglov/da...
1712867530169 <= {"event":"analysis.highlights","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":15},{"type":"BUILT_IN","offset":0,"length...
1712867530169 <= {"event":"analysis.navigation","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","regions":[{"offset":34,"length":1,"targets":[0]},{"offset":45,"length":3,"targets":[1]}],"t...
1712867530169 <= {"event":"analysis.outline","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","location":{"f...
1712867530169 <= {"event":"analysis.overrides","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","overrides":[]}}
1712867530173 <= {"event":"analysis.errors","params":{"file":"/Users/scheglov/dart/test/bin/test.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file":"/Users/scheglov/dar...
1712867530206 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1712867530206 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1712867530206 <= {"event":"analysis.implemented","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","classes":[],"members":[]}}
1712867530231 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1712867530474 => {"id":"19592","method":"analysis.updateContent","params":{"files":{"/Users/scheglov/dart/test/bin/test3.dart":{"type":"add","content":"import 'append.dart';\n\n@CrashMe()\nclass A {\n...
1712867530479 => {"id":"19593","method":"edit.getFixes","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","offset":2},"clientRequestTime":1712867530479}
1712867530479 <= {"id":"19592","result":{}}
1712867530479 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1712867530485 => {"id":"19594","method":"edit.getAssists","params":{"file":"/Users/scheglov/dart/test/bin/test3.dart","offset":19,"length":0},"clientRequestTime":1712867530485}
```
```

**Comment by scheglov** [comment]
Ah, I run unit tests with asserts enabled, so the mistake does not allow you to create such invalid `Code.fromParts()` at all. But if you don't have asserts enabled, e.g. when you run DAS from IntelliJ, you can. But then it hard crash later, at the point where it is not an assert. Which means that the first point also should be not just an assert, but full check. Or better typing.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/362440
