### ISSUE TITLE
tests/modular/macro fails on ddc-win-chrome

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#55460]
<details><summary>Example log:</summary>

```
uncaught exception: ProcessException: The system cannot find the file specified.

  Command: chmod rwxrwxrwx C:\b\s\w\ir\x\t\modular_test_res-64ad525c\2add_function.macro.exe
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:579:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      IOPipeline.runStep (package:modular_test/src/io_pipeline.dart:178:23)
<asynchronous suspension>
#5      Pipeline._recursiveRun (package:modular_test/src/pipeline.dart:181:5)
<asynchronous suspension>
#6      Pipeline._recursiveRun (package:modular_test/src/pipeline.dart:153:7)
<asynchronous suspension>
#7      Pipeline.run (package:modular_test/src/pipeline.dart:140:7)
<asynchronous suspension>
#8      IOPipeline.run (package:modular_test/src/io_pipeline.dart:82:5)
<asynchronous suspension>
#9      _PipelineTest.run (package:modular_test/src/runner.dart:59:5)
<asynchronous suspension>
#10     runSuite (package:modular_test/src/generic_runner.dart:115:7)
<asynchronous suspension>
#11     runSuite (package:modular_test/src/runner.dart:29:3)
<asynchronous suspension>
#12     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/test/modular_suite.dart:20:3)
<asynchronous suspension>

To repro run:
  C:\b\s\w\ir\cache\builder\sdk\out\ReleaseX64\dart-sdk\bin\dart.exe /C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/test/modular_suite.dart --verbose --filter macro
  ```
</details>

**Comment by jakemac53** [comment]
@sigmundch had mentioned this operation might not even be necessary so I can try just removing it.

**Comment by sigmundch** [comment]
For context: https://dart-review.googlesource.com/c/sdk/+/361261/ has more details.

**Comment by jakemac53** [comment]
@fishythefish I think this is probably resolved but tbh have absolutely no clue how to confirm or deny that assumption lol. Is it possible to browse the test database at all per platform or something to see if it is passing?

**Comment by fishythefish** [comment]
Looks like it's passing, per https://dart-current-results.web.app/#/filter=tests/modular/macro&showAll, so I think we can close this issue.
