### ISSUE TITLE
asserts on app-jit doesn't preserve assertion text app, asserts_test fails

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#55461]
[logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8750834444200844785/+/u/test_results/new_test_failures__logs_)

```
--- Command "app_jit" (took 01.000305s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --snapshot=/b/s/w/ir/out/ReleaseX64/generated_compilations/vm-appjit-linux-release-x64/runtime_tests_vm_dart_asserts_test/out.jitsnapshot --snapshot-kind=app-jit --enable-asserts --sound-null-safety -Dtest_runner.configuration=vm-appjit-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/runtime/tests/vm/dart/asserts_test.dart

exit code:
255

stdout:
Exception: 'file:///b/s/w/ir/runtime/tests/vm/dart/asserts_test.dart': Failed assertion: line 11 pos 23: '<optimized out>': is not true.

stderr:
Unhandled exception:
Expect.throws: Unexpected 'Instance of '_AssertionError''
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      main.<anonymous closure> (file:///b/s/w/ir/runtime/tests/vm/dart/asserts_test.dart:11:23)
#3      Expect.throws (package:expect/expect.dart:596:18)
#4      main (file:///b/s/w/ir/runtime/tests/vm/dart/asserts_test.dart:10:10)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

#0      Expect._fail (package:expect/expect.dart:722:5)
#1      Expect.throws (package:expect/expect.dart:606:7)
#2      main (file:///b/s/w/ir/runtime/tests/vm/dart/asserts_test.dart:10:10)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n vm-appjit-linux-release-x64 vm/dart/asserts_test
```

**Comment by aam** [comment]
Root cause for this is that we don't request kernel with sources when building appjit snapshot https://github.com/dart-lang/sdk/blob/aa4aa6975d6fa8bde800b3a9ad930c6d28b0e1ea/runtime/bin/main_impl.cc#L306  and we don't include sources into serialized script that goes into appjit snapshot https://github.com/dart-lang/sdk/blob/aa4aa6975d6fa8bde800b3a9ad930c6d28b0e1ea/runtime/vm/raw_object.h#L1612
