### ISSUE TITLE
Invalid `super._` in extension type constructors cause crashes

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#55484]
Simple reproduction case in `Dart SDK version: 3.3.1 (stable)`:

```dart
import 'package:meta/meta.dart';

void main() {
  const red = Color(0xFFFF0000);
  const tooSmall = Color(-1);
  const tooBig = Color(0xFFFFFFFF + 1);
}

extension type const Color._(int _argb) {
  const Color(
    int argb,
        // This is invalid code, but the analyzer says nothing and crashes.
  )   : super._(argb),
        assert(argb >= 0 && argb <= 0xFFFFFFFF);
}
```

This was a mistake in my code, `super._` isn't right, but I think it combined with `assert` puts analyzer in a bad state:
```txt
{"jsonrpc":"2.0","method":"dart/textDocument/publishOutline","params":{"outline":{"codeRange":{"end":{"character":0,"line":1},"start":{"character":0,"line":0}},"element":{"kind":"COMPILATION_UNIT","name":"<unit>","range":{"end":{"character":0,"line":1},"start":{"character":0,"line":0}}},"range":{"end":{"character":0,"line":1},"start":{"character":0,"line":0}}},"uri":"file:///Users/matan/Developer/binary.dart/lib/…
[7:43:44 PM] [Analyzer] [Info] <== Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8
[7:43:44 PM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}}}
[7:43:44 PM] [Analyzer] [Error] Unhandled exception:
Null check operator used on a null value
#0      ErrorVerifier._checkForConflictingInitializerErrorCodes (package:analyzer/src/generated/error_verifier.dart:2355:52)
#1      ErrorVerifier.visitConstructorDeclaration.<anonymous closure> (package:analyzer/src/generated/error_verifier.dart:559:7)
#2      ErrorVerifier._withEnclosingExecutable (package:analyzer/src/generated/error_verifier.dart:5951:16)
#3      ErrorVerifier.visitConstructorDeclaration (package:analyzer/src/gene…
```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/363621
