### ISSUE TITLE
lib/typed_data/typed_data_load2_test broke (Pass -> RuntimeError, expected Pass)

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#55493]
The likely culprit is https://github.com/dart-lang/sdk/commit/ad95bb6f89eb3aa36b129320fba47c29574b7084

@alexmarkov could you take a look and determine if this commit is the issue and whether we should revert, forward fix or turn this into a gardening bug.

```
/==================================================================================\
| lib/typed_data/typed_data_load2_test broke (Pass -> RuntimeError, expected Pass) |
\==================================================================================/

--- Command "vm_compile_to_kernel" (took 08.000238s):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-optimization-level-linux-release-x64/tests_lib_typed_data_typed_data_load2_test/out.dill /b/s/w/ir/tests/lib/typed_data/typed_data_load2_test.dart -Dtest_runner.configuration=vm-aot-optimization-level-linux-release-x64 --packages=/b/s/w/ir/.dart_tool/package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 15.000460s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-optimization-level-linux-release-x64/tests_lib_typed_data_typed_data_load2_test/out.S --sound-null-safety --optimization_level=3 --random_seed=__RANDOM__ -Dtest_runner.configuration=vm-aot-optimization-level-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-optimization-level-linux-release-x64/tests_lib_typed_data_typed_data_load2_test/out.dill

exit code:
0

stderr:
Ignoring flag: __RANDOM__ is an invalid value for flag random_seed

--- Command "remove_kernel_file" (took 58ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-optimization-level-linux-release-x64/tests_lib_typed_data_typed_data_load2_test/out.dill

exit code:
0

--- Command "assemble" (took 02.000152s):
DART_CONFIGURATION=ReleaseX64 gcc -Wl,--no-undefined -shared -o /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-optimization-level-linux-release-x64/tests_lib_typed_data_typed_data_load2_test/out.aotsnapshot /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-optimization-level-linux-release-x64/tests_lib_typed_data_typed_data_load2_test/out.S

exit code:
0

--- Command "remove_assembly" (took 38ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-optimization-level-linux-release-x64/tests_lib_typed_data_typed_data_load2_test/out.S

exit code:
0

--- Command "vm" (took 72ms):
DART_CONFIGURATION=ReleaseX64 TEST_COMPILATION_DIR=/b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-optimization-level-linux-release-x64/tests_lib_typed_data_typed_data_load2_test out/ReleaseX64/dart_precompiled_runtime --optimization_level=3 --random_seed=400193729 --sound-null-safety -Dtest_runner.configuration=vm-aot-optimization-level-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-optimization-level-linux-release-x64/tests_lib_typed_data_typed_data_load2_test/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <1>, actual: <9>) fails.
#0      Expect._fail (package:expect/expect.dart:722)
#1      Expect.equals (package:expect/expect.dart:125)
#2      aliasWithByteData2 (file:///b/s/w/ir/tests/lib/typed_data/typed_data_load2_test.dart:34)
#3      main (file:///b/s/w/ir/tests/lib/typed_data/typed_data_load2_test.dart:104)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

--- Re-run this test:
python3 tools/test.py -n vm-aot-optimization-level-linux-release-x64 lib/typed_data/typed_data_load2_test
```

**Comment by alexmarkov** [comment]
Fix: https://dart-review.googlesource.com/c/sdk/+/363401.
