### ISSUE TITLE
[dart2wasm] crashing dart2wasm with a flame demo

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#55529]
```
Flutter 3.22.0-14.0.pre.55 • channel master • git@github.com:flutter/flutter.git
Framework • revision a5fa351c89 (20 hours ago) • 2024-04-20 01:33:06 +0200
Engine • revision 55670b71eb
Tools • Dart 3.5.0 (build 3.5.0-80.0.dev) • DevTools 2.35.0-dev.8

https://github.com/kevmoo/flame/tree/crashing_wasm
cd examples

flutter build web --wasm

┌─ New feature ────────────────────────────────────────────────────────────────────────────┐
│   WebAssembly compilation is new. Understand the details before deploying to production. │
│   See https://flutter.dev/wasm for more information.                                     │
└──────────────────────────────────────────────────────────────────────────────────────────┘

Warning: In index.html:28: Manual service worker registration deprecated. Use flutter.js service worker bootstrapping instead.
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
*NOTE*: Compilation to WasmGC is experimental.
The support may change, or be removed, with no advance notice.


Unhandled exception:
Null check operator used on a null value
#0      _ClosureTrampolineGenerator.generate (package:dart2wasm/translator.dart:1128)
#1      Translator.translate (package:dart2wasm/translator.dart:397)
#2      compileToModule (package:dart2wasm/compile.dart:186)
<asynchronous suspension>
#3      generateWasm (package:dart2wasm/generate_wasm.dart:24)
<asynchronous suspension>
#4      main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/dart2wasm/bin/dart2wasm.dart:10)
<asynchronous suspension>
  Command: /Users/kevmoo/github/flutter/bin/cache/dart-sdk/bin/dart compile wasm --packages=.dart_tool/package_config.json --extra-compiler-option=--dart-sdk=/Users/kevmoo/github/flutter/bin/cache/dart-sdk
  --extra-compiler-option=--platform=/Users/kevmoo/github/flutter/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill --extra-compiler-option=--delete-tostring-package-uri=dart:ui
  --extra-compiler-option=--delete-tostring-package-uri=package:flutter --extra-compiler-option=--import-shared-memory --extra-compiler-option=--shared-memory-max-pages=32768 -Ddart.vm.product=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/55670b71eb00fbe80601b7227f68c1df4cae827b/ -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_USE_SKWASM=true
  --extra-compiler-option=--depfile=/Users/kevmoo/github/flame/examples/.dart_tool/flutter_build/d82f58e382ac372528cd5826f4daf5a6/dart2wasm.d -O4 --no-name-section -o
  /Users/kevmoo/github/flame/examples/.dart_tool/flutter_build/d82f58e382ac372528cd5826f4daf5a6/main.dart.wasm /Users/kevmoo/github/flame/examples/.dart_tool/flutter_build/d82f58e382ac372528cd5826f4daf5a6/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:321:19)
<asynchronous suspension>
#2      Dart2WasmTarget.build (package:flutter_tools/src/build_system/targets/web.dart:329:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             15.5s
Error: Failed to compile application for the Web.
```

**Comment by kevmoo** [comment]
See https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md

```
flutter pub global activate melos
melos bootstrap
```

**Comment by osa1** [comment]
Smaller repro:

```dart
class Base {
  final Object? a;
  Object? b;

  Base({this.a, this.b});

  @override
  String toString() {
    return 'a: $a, b: $b';
  }
}

abstract class A extends Base {
  A({required super.a, super.b});
}

class B extends A {
  B({super.a, super.b}) {}
}

void main() {
  var f1 = Base.new;
  var f2 = B.new;

  print(f1());
  print(f2());
}
```

Output:

```
Unhandled exception:
Null check operator used on a null value
#0      _ClosureTrampolineGenerator.generate (package:dart2wasm/translator.dart:1131:37)
#1      Translator.translate (package:dart2wasm/translator.dart:397:30)
#2      compileToModule (package:dart2wasm/compile.dart:186:33)
<asynchronous suspension>
#3      generateWasm (package:dart2wasm/generate_wasm.dart:24:28)
<asynchronous suspension>
#4      main (file:///usr/local/google/home/omersa/dart/sdk/sdk/pkg/dart2wasm/bin/dart2wasm.dart:10:14)
<asynchronous suspension>
```

**Comment by osa1** [comment]
I think this is a CFE bug. The named parameter of `B.new` tear-off isn't required but also doesn't have a default value:

```dart
  class A extends core::Object {
    final field core::Object? a;
    constructor •({required core::Object? a}) → test::A
      : test::A::a = a, super core::Object::•()
      ;
    static method _#new#tearOff({required core::Object? a}) → test::A
      return new test::A::•(a: a);
  }

  class B extends test::A {
    constructor •({core::Object? a = #C1}) → test::B
      : super test::A::•(a: a) {}
    static method _#new#tearOff({core::Object? a}) → test::B // <-------------- HERE
      return new test::B::•(a: a);
  }

  static method main() → void {
    ({a: core::Object?}) → test::B f2 = #C2;
    core::print(f2(){({a: core::Object?}) → test::B});
  }
```

@johnniwinther @chloestefantsova is my diagnosis of the issue correct?

I remember debugging similar issues before. Would it make sense to update the kernel verification pass to check for this? If a `VariableDeclaration` is not required then it should have a non-null `initializer`.

**Comment by osa1** [comment]
Here's another example of a similar issue we've debugging before: https://github.com/dart-lang/sdk/issues/53239#issuecomment-1850062260

**Comment by kevmoo** [comment]
Interesting that this code builds fine with the VM and dart2js. 🤷
