### ISSUE TITLE
"Bad state: WebSocket is closed" on iso-stress-linux bot

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#55538]
From the log:
```
[/b/s/w/ir/cache/builder/sdk/runtime/tests/concurrency/../vm/dart/isolates/reload_many_isolates_test.dart] error: [Bad state: WebSocket is closed, #0      IOWebSocket.close (package:web_socket/src/io_web_socket.dart:105:7)
#1      new AdapterWebSocketChannel.<anonymous closure>.<anonymous closure> (package:web_socket_channel/adapter_web_socket_channel.dart:114:21)
#2      _rootRun (dart:async/zone.dart:1391:47)
#3      _CustomZone.run (dart:async/zone.dart:1301:19)
#4      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#8      _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#9      _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
#10     _StreamController.close (dart:async/stream_controller.dart:640:5)
#11     new GuaranteeChannel.<anonymous closure>.<anonymous closure> (package:stream_channel/src/guarantee_channel.dart:55:31)
#12     _rootRun (dart:async/zone.dart:1391:47)
#13     _CustomZone.run (dart:async/zone.dart:1301:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#15     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#16     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#17     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#18     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#19     _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
#20     _StreamController.close (dart:async/stream_controller.dart:640:5)
#21     _StreamSinkWrapper.close (dart:async/stream_controller.dart:884:29)
#22     _GuaranteeSink.close (package:stream_channel/src/guarantee_channel.dart:188:38)
#23     DelegatingStreamSink.close (package:async/src/delegate/stream_sink.dart:47:27)
#24     _WebSocketSink.close (package:web_socket_channel/adapter_web_socket_channel.dart:147:18)
#25     Stream.pipe.<anonymous closure> (dart:async/stream.dart:979:70)
#26     _rootRunUnary (dart:async/zone.dart:1407:47)
#27     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:876:13)
#30     Future._complete (dart:async/future_impl.dart:643:7)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:59:12)
#32     _rootRun (dart:async/zone.dart:1391:47)
#33     _CustomZone.run (dart:async/zone.dart:1301:19)
#34     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#35     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#36     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#37     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#38     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#39     _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
#40     _StreamController.close (dart:async/stream_controller.dart:640:5)
#41     _HandlerSink.close (package:async/src/stream_sink_transformer/handler_transformer.dart:88:43)
#42     DelegatingStreamSink.close (package:async/src/delegate/stream_sink.dart:47:27)
#43     _CloseGuaranteeSink.close (package:stream_channel/src/close_guarantee_channel.dart:81:22)
#44     DelegatingStreamSink.close (package:async/src/delegate/stream_sink.dart:47:27)
#45     _CloseGuaranteeSink.close (package:stream_channel/src/close_guarantee_channel.dart:81:22)
#46     Client.close (package:json_rpc_2/src/client.dart:98:19)
#47     Peer.close (package:json_rpc_2/src/peer.dart:152:13)
#48     RemoteVm.disconnect (file:///b/s/w/ir/cache/builder/sdk/pkg/front_end/test/tool/reload.dart:134:26)
#49     Reloader.close (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart/isolates/reload_utils.dart:240:10)
#50     main.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart/isolates/reload_many_isolates_test.dart:31:41)
<asynchronous suspension>
#51     withTempDir (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart/snapshot_test_helper.dart:118:12)
<asynchronous suspension>
#52     main (file:///b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart/isolates/reload_many_isolates_test.dart:15:3)
<asynchronous suspension>
]
```
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8749954748890372801/+/u/collect_shards/Run_Isolate_Stress_Tests_shard_1/task_stdout_stderr:_Run_Isolate_Stress_Tests_shard_1

Started happening soon after the new version of `web_socket_channel` package was rolled in 1998c87bff783f39ebc7db4e037280e8da488c8c.

/cc @brianquinlan

**Comment by brianquinlan** [comment]
The relevant part of the stack trace is:

```
io_web_socket.dart:105:

  Future<void> close([int? code, String? reason]) async {
    if (_events.isClosed) {
      throw StateError('WebSocket is closed');  <-- 
    }

adapter_web_socket_channel.dart:114:

    webSocketFuture.then((webSocket) {
      var remoteClosed = false;
      webSocket.events.listen((event) {
        switch (event) {
          case TextDataReceived(text: final text):
            _controller.local.sink.add(text);
          case BinaryDataReceived(data: final data):
            _controller.local.sink.add(data);
          case CloseReceived(code: final code, reason: final reason):
            remoteClosed = true;
            _closeCode = code;
            _closeReason = reason;
            _controller.local.sink.close();
        }
      });
      _controller.local.stream.listen((obj) {
        try {
          switch (obj) {
            case final String s:
              webSocket.sendText(s);
            case final Uint8List b:
              webSocket.sendBytes(b);
            case final List<int> b:
              webSocket.sendBytes(Uint8List.fromList(b));
            default:
              throw UnsupportedError('Cannot send ${obj.runtimeType}');
          }
        } on WebSocketConnectionClosed catch (_) {
          // There is nowhere to surface this error; `_controller.local.sink`
          // has already been closed.
        }
      }, onDone: () {
        if (!remoteClosed) {
          webSocket.close(_localCloseCode, _localCloseReason); <--
        }
      });
```

**Comment by brianquinlan** [comment]
I can't see this in the logs anymore. I'm going to assume that this is fixed.

**Comment by alexmarkov** [comment]
The failure doesn't appear in the logs anymore because this test was removed from iso-stress-linux bot in 687a955ac3aac499141dfe49f52722fa9688b43e.
