### ISSUE TITLE
Simple fixedList.setAll is not working !! - this simple implementation is getting stuck

### ISSUE THREAD

**Issue by pk-szt** [dart-lang/sdk#55588]
```dart
final fixedLengthList = List<int>.filled(5, 0); // Creates fixed-length list.
print(fixedLengthList); // [0, 0, 0, 0, 0]
fixedLengthList[0] = 87;
fixedLengthList.setAll(1, [1, 2, 3]);
print(fixedLengthList); // [87, 1, 2, 3, 0]
```
***
It was working a few days ago. Now it says 

```
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'Iterable<int>' of 'iterable'
#0      List.setAll (dart:core-patch/array.dart:217:38)

dart-lang/language#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
dart-lang/language#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by lrhn** [comment]
I agree that it doesn't reproduce in DartPad.
How do you run the code, and with which version of the SDK?

**Comment by lrhn** [comment]
My best guess here is that the actual code getting the error started with:
```dart
final List fixedLengthList = List<int>.filled(5, 0); // Creates fixed-length list.
```
That would precisely introduce the error, since the argument list will then be inferred as `<dynamic>[...]`, which is not a valid argument to `List<int>.setAll`. It's a runtime error because of unsound generics and the initial up-cast.
