### ISSUE TITLE
Type check failure in _IOServicePorts._newServicePort

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#55606]
```
FAILED: dartkp-dart_precompiled release_x64 vm/dart/heapsnapshot_cli_test
Expected: Pass
Actual: Timeout

--- Command "vm_compile_to_kernel" (took 04.000587s):
DART_CONFIGURATION=ReleaseTSANX64 /usr/local/google/home/rmacnak/dart1/sdk/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseTSANX64/vm_platform_strong.dill -o /usr/local/google/home/rmacnak/dart1/sdk/out/ReleaseTSANX64/generated_compilations/vm-aot-tsan-linux-release-x64/runtime_tests_vm_dart_heapsnapshot_cli_test/out.dill /usr/local/google/home/rmacnak/dart1/sdk/runtime/tests/vm/dart/heapsnapshot_cli_test.dart -Dtest_runner.configuration=vm-aot-tsan-linux-release-x64 --packages=/usr/local/google/home/rmacnak/dart1/sdk/.dart_tool/package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 35.000546s):
DART_CONFIGURATION=ReleaseTSANX64 rr record --chaos --output-trace-dir=/tmp/rr-trace-481511681 out/ReleaseTSANX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/usr/local/google/home/rmacnak/dart1/sdk/out/ReleaseTSANX64/generated_compilations/vm-aot-tsan-linux-release-x64/runtime_tests_vm_dart_heapsnapshot_cli_test/out.S --sound-null-safety -Dtest_runner.configuration=vm-aot-tsan-linux-release-x64 --ignore-unrecognized-flags --packages=/usr/local/google/home/rmacnak/dart1/sdk/.dart_tool/package_config.json /usr/local/google/home/rmacnak/dart1/sdk/out/ReleaseTSANX64/generated_compilations/vm-aot-tsan-linux-release-x64/runtime_tests_vm_dart_heapsnapshot_cli_test/out.dill (rr replay out/rr-trace-481511681)

exit code:
0

--- Command "remove_kernel_file" (took 20ms):
DART_CONFIGURATION=ReleaseTSANX64 rm /usr/local/google/home/rmacnak/dart1/sdk/out/ReleaseTSANX64/generated_compilations/vm-aot-tsan-linux-release-x64/runtime_tests_vm_dart_heapsnapshot_cli_test/out.dill

exit code:
0

--- Command "assemble" (took 01.000084s):
DART_CONFIGURATION=ReleaseTSANX64 gcc -Wl,--no-undefined -shared -o /usr/local/google/home/rmacnak/dart1/sdk/out/ReleaseTSANX64/generated_compilations/vm-aot-tsan-linux-release-x64/runtime_tests_vm_dart_heapsnapshot_cli_test/out.aotsnapshot /usr/local/google/home/rmacnak/dart1/sdk/out/ReleaseTSANX64/generated_compilations/vm-aot-tsan-linux-release-x64/runtime_tests_vm_dart_heapsnapshot_cli_test/out.S

exit code:
0

--- Command "remove_assembly" (took 23ms):
DART_CONFIGURATION=ReleaseTSANX64 rm /usr/local/google/home/rmacnak/dart1/sdk/out/ReleaseTSANX64/generated_compilations/vm-aot-tsan-linux-release-x64/runtime_tests_vm_dart_heapsnapshot_cli_test/out.S

exit code:
0

--- Command "vm" (took 08:00.000314s):
DART_CONFIGURATION=ReleaseTSANX64 TEST_COMPILATION_DIR=/usr/local/google/home/rmacnak/dart1/sdk/out/ReleaseTSANX64/generated_compilations/vm-aot-tsan-linux-release-x64/runtime_tests_vm_dart_heapsnapshot_cli_test rr record --chaos --output-trace-dir=/tmp/rr-trace-329358989 out/ReleaseTSANX64/dart_precompiled_runtime --sound-null-safety -Dtest_runner.configuration=vm-aot-tsan-linux-release-x64 --ignore-unrecognized-flags --packages=/usr/local/google/home/rmacnak/dart1/sdk/.dart_tool/package_config.json /usr/local/google/home/rmacnak/dart1/sdk/out/ReleaseTSANX64/generated_compilations/vm-aot-tsan-linux-release-x64/runtime_tests_vm_dart_heapsnapshot_cli_test/out.aotsnapshot (rr replay out/rr-trace-329358989)

exit code:
1

stdout:
00:00 +0: cli (setUpAll)

child-stdout: Could not start Dart VM service HTTP server:

child-stdout: type 'Null' is not a subtype of type 'SendPort' of 'function result'

child-stdout: #0      _IOServicePorts._newServicePort (dart:io-patch/io_service_patch.dart)

child-stdout: #1      _IOServicePorts._getPort (dart:io-patch/io_service_patch.dart:21)

child-stdout: #2      _IOService._dispatch (dart:io-patch/io_service_patch.dart:60)

child-stdout: #3      _NativeSocket.lookup (dart:io-patch/socket_patch.dart:517)

child-stdout: #4      InternetAddress.lookup (dart:io-patch/socket_patch.dart:84)

child-stdout: #5      Server.startup.startServer (dart:vmservice_io/vmservice_server.dart:470)

child-stdout: #6      Server.startup (dart:vmservice_io/vmservice_server.dart:495)

child-stdout: #7      main (dart:vmservice_io:400)

child-stdout: 

child-stdout: [Foo(#sharedString, #nonSharedString#, #fooUniqueString, []), Foo(#sharedString, #nonSharedString#, #fooUniqueString, [])]|[Bar(#sharedString, #nonSharedString#, #barUniqueString, [null]), Bar(#sharedString, #nonSharedString#, #barUniqueString, [null])]|

child-stdout: Instance of 'Object'|[_WeakReference<Object>]|_FinalizerImpl<>

child-stdout: 1234567

child-stdout: Child ready

--- Re-run this test:
python3 tools/test.py -n vm-aot-tsan-linux-release-x64 --rr vm/dart/heapsnapshot_cli_test
```

The test timed out, so this might be a failure to handle shutdown properly.

**Comment by a-siva** [comment]
//cc @a-siva
