### ISSUE TITLE
Improve thrown `FormatException` from `int.parse` when there is an "invalid radix-n" number

### ISSUE THREAD

**Issue by Luckey-Elijah** [dart-lang/sdk#55665]
The following code throws a `FormatException`

```dart
void main() {
  final value = int.parse('1.0');
}
```

Full error:
```
Unhandled exception:
FormatException: Invalid radix-10 number (at character 1)
1.0
^

#0      int._handleFormatError (dart:core-patch/integers_patch.dart:126:5)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:137:16)
#2      int._parse (dart:core-patch/integers_patch.dart:98:12)
#3      int.parse (dart:core-patch/integers_patch.dart:60:12)
#4      main (package:dpad/intparse.dart:2:21)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

It seems like the  point to the incorrect character (1). Should it not be pointing to the `.` character (2) in this case?

Version
```
dart --version
Dart SDK version: 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "macos_x64"
```

**Comment by lrhn** [comment]
In some cases, the parser doesn't know the point of failure, because it's written to be optimized for parsing correct numbers, and recording extra positions would be overhead. I don't know if this is one of those cases. Probably not. 

Could probably have a second pass to look for invalid characters then.

Also just noticed that it does say "at index 1", so it should be pointing to index 1, not index 0. Is this an "off-by-one" error?
Or is it printed in a way that removes leading spaces?
