### ISSUE TITLE
pkg/dds/test/dap/integration/debug_exceptions_test went from flaky -> RuntimeError on unittest-asserts-release-win-arm64

### ISSUE THREAD

**Issue by derekxu16** [dart-lang/sdk#55685]
The tests
```
pkg/dds/test/dap/integration/debug_exceptions_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win-arm64
```
https://dart-ci.appspot.com/log/pkg-win-release-arm64/unittest-asserts-release-win-arm64/1503/pkg/dds/test/dap/integration/debug_exceptions_test

https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-win-release-arm64/1503/overview

I see two errors in the logs. The first is a `SocketException`:

```
00:02 [32m+0[0m[31m -1[0m: debug mode does not pause on exceptions if mode not set [1m[31m[E][0m[0m

  SocketException: Write failed (OS Error: The pipe is being closed.

  , errno = 232), port = 0

  dart:io-patch/socket_patch.dart 1246:34       _NativeSocket.write
  dart:io-patch/socket_patch.dart 2004:15       _RawSocket.write
  dart:io-patch/socket_patch.dart 2481:18       _Socket._write
  dart:io-patch/socket_patch.dart 2216:28       _SocketStreamConsumer.write
  dart:io-patch/socket_patch.dart 2168:11       _SocketStreamConsumer.addStream.<fn>
  dart:async/zone.dart 1407:47                  _rootRunUnary
  dart:async/zone.dart 1308:19                  _CustomZone.runUnary
  dart:async/zone.dart 1217:7                   _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 365:11            _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 541:14            _DelayedData.perform
  dart:async/stream_impl.dart 646:11            _PendingEvents.handleNext
  dart:async/stream_impl.dart 617:7             _PendingEvents.schedule.<fn>
  dart:async/zone.dart 1391:47                  _rootRun
  dart:async/zone.dart 1301:19                  _CustomZone.run
  dart:async/zone.dart 1209:7                   _CustomZone.runGuarded
  dart:async/zone.dart 1249:23                  _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1399:13                  _rootRun
  dart:async/zone.dart 1301:19                  _CustomZone.run
  dart:async/zone.dart 1209:7                   _CustomZone.runGuarded
  dart:async/zone.dart 1249:23                  _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 40:21      _microtaskLoop
  dart:async/schedule_microtask.dart 49:5       _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13  _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 185:5   _RawReceivePort._handleMessage
  ```

The second is a drive letter capitalization mismatch:

```
00:14 [32m+5[0m[31m -1[0m: debug mode pauses on uncaught exceptions when mode=Unhandled (supportUris: false, sendFileUris: false)[0m

Request "terminate" has taken longer than 10s

00:14 [32m+5[0m[31m -2[0m: debug mode parses line/column information from stack traces [1m[31m[E][0m[0m

  Expected: 'c:\\opt\\s\\w\\ir\\x\\t\\dart-sdk-dap-test5e2fb1cf\\app19a5c4a8\\test_file.dart'
    Actual: 'C:\\opt\\s\\w\\ir\\x\\t\\dart-sdk-dap-test5e2fb1cf\\app19a5c4a8\\test_file.dart'
     Which: is different.
            Expected: c:\\opt\\s ...
              Actual: C:\\opt\\s ...
                      ^
             Differ at offset 0
  

  package:matcher/src/expect/expect.dart 149:31                 fail
  package:matcher/src/expect/expect.dart 144:3                  _expect
  package:matcher/src/expect/expect.dart 56:3                   expect
  pkg\dds\test\dap\integration\debug_exceptions_test.dart 91:7  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9              Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7              Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9               Invoker._waitForOutstandingCallbacks.<fn>
```

**Comment by derekxu16** [comment]
cc @bkonyi and @DanTup

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/365804 should fix the drive letter mismatch (oddly that test hasn't changed in 2yrs.. not sure if the drive letter casing is somehow different on some bots for temp directory?).

Hard to tell what the other failure is - @derekxu16 is there a way to tell how frequently it's failing? We could enable verbose output on the bots temporarily to try to get a better idea of what's happening?

**Comment by derekxu16** [comment]
We have a flakiness dashboard. Unfortunately you have to log in with an @google.com account to access it, but here's a screenshot showing the run results of `pkg/dds/test/dap/integration/debug_exceptions_test` on Windows:

![Screenshot 2024-05-13 at 9 29 54 AM](https://github.com/dart-lang/sdk/assets/1782969/5fd9fdcc-df1f-40e9-8fce-2fbc337a6aa9)

I don't know how many of these failures were caused by `SocketException`s specifically, but the test is failing frequently.

**Comment by DanTup** [comment]
I guess many of those failures could be the drive letter issue. Let's land the fix above and then review the stats.. if there are still failures and that wasn't a one-off, I'll open a change to add verbose output and we can go from there.

(I'll ping back here a little after that fix lands)

**Comment by DanTup** [comment]
A fix for the second issue (drive casing) has landed. I believe the first issue is the same as https://github.com/dart-lang/sdk/issues/55313 - let me know if we should close this as a dupe, or it's better to keep this open until that's also fixed (I don't know how the flaky test approval works if it might be tied to this?).

**Comment by DanTup** [comment]
@derekxu16 are you able to review what this dashboard looks like now with some of the fixes above landed?

**Comment by derekxu16** [comment]
![](https://github.com/user-attachments/assets/5d1c55b6-4684-44d5-95f2-7cea0307ef37)

Clicking on the numbers in the RTE and TO columns shows me the last time a result in the specified category occurred. The test hasn't timed out on either win-x64 or win-arm64 since May 2, 2024 (https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-win-release/28313/overview and https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-win-release-arm64/1453/overview). There hasn't been an RTE on win-x64 since May 30, 2024 (https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-win-release/28645/overview), but there was an RTE on win-arm64 on August 16, 2024 (https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-win-release-arm64/2347/overview).

**Comment by DanTup** [comment]
Thanks - if I'm looking at the right failure, the recent failure is "The pipe is being closed" which I think is the same issue discussed in https://github.com/dart-lang/sdk/issues/55313 (this needs some further input, as I've not been able to come up with any way to handle that error without the VM hanging at the end - I've added example code in that issue).

**Comment by DanTup** [comment]
I think the original issue here may be resolved by the fix for https://github.com/dart-lang/sdk/issues/55313, however looking at https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=pkg/dds/test/dap/integration/debug_exceptions_test, there are some different recent failures:

https://dart-ci.appspot.com/log/pkg-linux-release/unittest-asserts-release-linux-x64/28665/pkg/dds/test/dap/integration/debug_exceptions_test

```
00:10 [32m+6[0m[31m -1[0m: debug mode parses line/column information from stack traces [1m[31m[E][0m[0m

  Expected: '/b/s/w/itrrr2vys3/dart-sdk-dap-testDGOUGT/appUWATOH/test_file.dart'
    Actual: <null>
     Which: not an <Instance of 'String'>
  

  package:matcher/src/expect/expect.dart 149:31                 fail
  package:matcher/src/expect/expect.dart 144:3                  _expect
  package:matcher/src/expect/expect.dart 56:3                   expect
  pkg/dds/test/dap/integration/debug_exceptions_test.dart 91:7  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 229:9              Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 227:7              Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9               Invoker._waitForOutstandingCallbacks.<fn>
  

00:10 [32m+6[0m[31m -1[0m: [31mSome tests failed.[0m
```

I'll try to repro this.

**Comment by Markzipan** [comment]
Confirming that this test is still flaky. The non-green runs report:
```
Unhandled exception:

  FileSystemException: writeFrom failed, path = '' (OS Error: The pipe is being closed.


  , errno = 232)

  #0      _checkForErrorResponse (dart:io/common.dart:58)

  #1      _RandomAccessFile.writeFrom.<anonymous closure> (dart:io/file_impl.dart:1001)

  #2      _rootRunUnary (dart:async/zone.dart:1538)

  #3      _CustomZone.runUnary (dart:async/zone.dart:1429)

  <asynchronous suspension>

  #4      _FileStreamConsumer.addStream.<anonymous closure>.<anonymous closure>.<anonymous closure> (dart:io/file_impl.dart:237)

  <asynchronous suspension>

 

  pkg\dds\test\dap\integration\test_server.dart 100:9  new OutOfProcessDapTestServer._.<fn>
  dart:async/zone.dart 1538:47                         _rootRunUnary
  dart:async/zone.dart 1429:19                         _CustomZone.runUnary
  dart:async/zone.dart 1329:7                          _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 381:11                   _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 312:7                    _BufferingStreamSubscription._add
  dart:async/stream_transformers.dart 67:11            _SinkTransformerStreamSubscription._add
  dart:async/stream_transformers.dart 13:11            _EventSinkWrapper.add
  dart:convert/string_conversion.dart 228:11           _StringAdapterSink.add
  dart:convert/string_conversion.dart 233:7            _StringAdapterSink.addSlice
  dart:convert/string_conversion.dart 313:20           _Utf8ConversionSink.addSlice
  dart:convert/string_conversion.dart 306:5            _Utf8ConversionSink.add
  dart:convert/chunked_conversion.dart 70:18           _ConverterStreamEventSink.add
  dart:async/stream_transformers.dart 115:24           _SinkTransformerStreamSubscription._handleData
  dart:async/zone.dart 1538:47                         _rootRunUnary
  dart:async/zone.dart 1429:19                         _CustomZone.runUnary
  dart:async/zone.dart 1329:7                          _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 381:11                   _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 312:7                    _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 798:19             _SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 663:7              _StreamController._add
  dart:async/stream_controller.dart 618:5              _StreamController.add
  dart:io-patch/socket_patch.dart 2912:41              _Socket._onData
  dart:async/zone.dart 1546:13                         _rootRunUnary
  dart:async/zone.dart 1429:19                         _CustomZone.runUnary
  dart:async/zone.dart 1329:7                          _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 381:11                   _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 312:7                    _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 798:19             _SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 663:7              _StreamController._add
  dart:async/stream_controller.dart 618:5              _StreamController.add
  dart:io-patch/socket_patch.dart 2331:31              new _RawSocket.<fn>
  dart:io-patch/socket_patch.dart 1655:14              _NativeSocket.issueReadEvent.issue
  dart:async/schedule_microtask.dart 40:35             _microtaskLoop
  dart:async/schedule_microtask.dart 49:5              _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 127:13         _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 194:5          _RawReceivePort._handleMessage
  
```

It's probably fragile and should be fixed when we have more bandwidth.

**Comment by DanTup** [comment]
@Markzipan do you have a link to the full output? That test is set to run with verbose logging (and prints all DAP protocol traffic) to try and aid debug this. The error you posted above is different to the previous one I posted, but it is one noted in some other flaky test reports (I think it's something trying to write to `stdout`/`stdin` as it's closing).

I'll try running it in a loop and see if I can repro this locally.

Edit:

I found a log for the x86 win bot, which seems to have failed in a similar way but a slightly different message:

https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win-x64/34508/pkg/dds/test/dap/integration/debug_exceptions_test

```
<== [DAP] {"seq":92,"type":"event","body":{"reason":"exited","threadId":1},"event":"thread"}

<== [DAP] {"seq":93,"type":"event","body":{"output":"\nExited.\n"},"event":"output"}

<== [DAP] {"seq":94,"type":"event","body":{},"event":"terminated"}

==> [DAP] {"seq":5,"type":"request","arguments":{},"command":"terminate"}

00:06 [32m+4[0m[31m -1[0m: debug mode does not pauses on caught exceptions when mode=Unhandled [1m[31m[E][0m[0m

  ../../runtime/bin/thread.cc: 20: error: Could not start thread dart:io ReadFile: 13 (The data is invalid.


  )

  

  pkg\dds\test\dap\integration\test_server.dart 100:9  new OutOfProcessDapTestServer._.<fn>
  dart:async/zone.dart 1538:47                         _rootRunUnary
  dart:async/zone.dart 1429:19                         _CustomZone.runUnary
  dart:async/zone.dart 1329:7                          _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 381:11                   _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 312:7                    _BufferingStreamSubscription._add
  dart:async/stream_transformers.dart 67:11            _SinkTransformerStreamSubscription._add
  dart:async/stream_transformers.dart 13:11            _EventSinkWrapper.add
  dart:convert/string_conversion.dart 228:11           _StringAdapterSink.add
  dart:convert/string_conversion.dart 233:7            _StringAdapterSink.addSlice
  dart:convert/string_conversion.dart 313:20           _Utf8ConversionSink.addSlice
  dart:convert/string_conversion.dart 306:5            _Utf8ConversionSink.add
  dart:convert/chunked_conversion.dart 70:18           _ConverterStreamEventSink.add
  dart:async/stream_transformers.dart 115:24           _SinkTransformerStreamSubscription._handleData
  dart:async/zone.dart 1538:47                         _rootRunUnary
  dart:async/zone.dart 1429:19                         _CustomZone.runUnary
  dart:async/zone.dart 1329:7                          _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 381:11                   _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 312:7                    _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 798:19             _SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 663:7              _StreamController._add
  dart:async/stream_controller.dart 618:5              _StreamController.add
  dart:io-patch/socket_patch.dart 2912:41              _Socket._onData
  dart:async/zone.dart 1546:13                         _rootRunUnary
  dart:async/zone.dart 1429:19                         _CustomZone.runUnary
  dart:async/zone.dart 1329:7                          _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 381:11                   _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 312:7                    _BufferingStreamSubscription._add
  dart:async/stream_controller.dart 798:19             _SyncStreamControllerDispatch._sendData
  dart:async/stream_controller.dart 663:7              _StreamController._add
  dart:async/stream_controller.dart 618:5              _StreamController.add
  dart:io-patch/socket_patch.dart 2331:31              new _RawSocket.<fn>
  dart:io-patch/socket_patch.dart 1655:14              _NativeSocket.issueReadEvent.issue
  dart:async/schedule_microtask.dart 40:35             _microtaskLoop
  dart:async/schedule_microtask.dart 49:5              _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 127:13         _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 194:5          _RawReceivePort._handleMessage
  

00:06 [32m+4[0m[31m -1[0m: debug mode pauses on caught exceptions when mode=All[0m
```

**Comment by DanTup** [comment]
I landed a change that I expect to solve this - please let me know if you continue to see any flakes in this (or other DAP tests) after da8ed2208ec38a656b0ae2586e7ad426f5b4187a.
