### ISSUE TITLE
Analyzer fails when using the json macro on a class with a super initializer

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#55702]
Repro code:

```dart
import 'package:json/json.dart';

@JsonCodable()
class Point {
  final int x, y;
  Point(this.x, this.y);
}

@JsonCodable()
class ColoredPoint extends Point {
  final double color;
  ColoredPoint(super.x, super.y, this.color);
}

```

Error:
```
UnimplementedError: (SuperFormalParameterImpl) super.x #0      DeclarationBuilderFromNode._formalParameterDeclaration (package:analyzer/src/summary2/macro_declarations.dart:1727:9)
#1      DeclarationBuilderFromNode._executableFormalParameters (package:analyzer/src/summary2/macro_declarations.dart:1669:31)
#2      DeclarationBuilderFromNode.constructorDeclaration (package:analyzer/src/summary2/macro_declarations.dart:1237:9)
#3      DeclarationBuilderFromNode.declarationOf (package:analyzer/src/summary2/macro_declarations.dart:1265:16)
#4      DeclarationBuilder.declarationOfElement (package:analyzer/src/summary2/macro_declarations.dart:163:23)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#7      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:882:20)
#8      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#9      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#10     new List.of (dart:core-patch/array_patch.dart:39:18)
#11     Iterable.toList (dart:core/iterable.dart:497:7)
#12     _DeclarationPhaseIntrospector.constructorsOf (package:analyzer/src/summary2/macro_application.dart:1076:12)
<asynchronous suspension>
#13     new ExternalMacroExecutorBase.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:_macros/src/executor/executor_base.dart:153:43)
<asynchronous suspension>

```

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/366225
