### ISSUE TITLE
Some of the backlog computations aren't processed by the CFE under certain conditions

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#55849]
The following program makes the CFE fail an assertion check that makes sure the delayed computations are processed at a certain point.

```dart
class A<X> {
  const A.foo(X x);
}

typedef F<Y> = A<Y>;

@F.foo("foo")
void bar() {}
```

The stack trace is as follows:

```
Unhandled exception:
Crash when compiling file:///tmp/asdf.dart at character offset 81:
'package:front_end/src/fasta/kernel/body_builder.dart': Failed assertion: line 1100 pos 11: 'delayedActionPerformers != null': Body builder has delayed actions that cannot be performed: [TypeAliasedConstructorInvocation(const F.foo("foo"))]

#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      BodyBuilder.performBacklogComputations (package:front_end/src/fasta/kernel/body_builder.dart:1100:11)
#3      BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1416:5)
#4      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1220:19)
#5      DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:357:5)
#6      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3887:14)
#7      Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3619:14)
#8      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:617:14)
#9      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:412:15)
#10     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1182:12)
<asynchronous suspension>
#11     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:694:7)
<asynchronous suspension>
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:633:7)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#14     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:613:12)
<asynchronous suspension>
#15     _buildInternal (package:front_end/src/kernel_generator_impl.dart:218:19)
<asynchronous suspension>
#16     withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
```

**Comment by chloestefantsova** [comment]
This may be connected to https://github.com/dart-lang/sdk/issues/55755.
