### ISSUE TITLE
Unhandled exception in CFE at spurious type parameter list

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#55888]
Consider the following program:

```dart
class A<T> {
  final List<T> xs;
  A<T>(List<T> this.xs);
}
```

This program causes the CFE (35bc17a0fa3a347089dfcd7a1c4f781b37c32db7) to stop with an unhandled exception as follows:

```
type 'Constructor' is not a subtype of type 'GenericDeclaration' in type cast
#0      TypeParameter.declaration (package:kernel/ast.dart:13090:28)
#1      TypeParameter.isStructuralParameter (package:kernel/ast.dart:13176:37)
#2      TypeParameterType.hashCode (package:kernel/ast.dart:12639:26)
#3      InterfaceType.hashCode (package:kernel/ast.dart:11531:65)
#4      _OperatorEqualsAndHashCode._hashCode (dart:collection-patch/compact_hash.dart:254:33)
#5      _LinkedHashMapMixin._getValueOrData (dart:collection-patch/compact_hash.dart:587:26)
#6      _LinkedHashMapMixin.[] (dart:collection-patch/compact_hash.dart:610:13)
#7      BinaryPrinter._writeNodeMetadataImpl (package:kernel/binary/ast_to_binary.dart:664:47)
#8      BinaryPrinter._writeNodeMetadata (package:kernel/binary/ast_to_binary.dart:658:5)
#9      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:439:7)
#10     BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:2423:5)
#11     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:342:16)
#12     BinaryPrinter.writeVariableDeclarationList (package:kernel/binary/ast_to_binary.dart:2431:5)
#13     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1526:5)
#14     FunctionNode.accept (package:kernel/ast.dart:3877:38)
#15     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:448:10)
#16     BinaryPrinter.visitConstructor (package:kernel/binary/ast_to_binary.dart:1315:5)
#17     Constructor.accept (package:kernel/ast.dart:2676:40)
#18     BinaryPrinter.writeConstructorNode (package:kernel/binary/ast_to_binary.dart:504:10)
#19     BinaryPrinter.writeConstructorNodeList (package:kernel/binary/ast_to_binary.dart:406:7)
#20     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1280:5)
#21     Class.accept (package:kernel/ast.dart:1476:38)
#22     BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:483:10)
#23     BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:378:7)
#24     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1118:5)
#25     Library.accept (package:kernel/ast.dart:590:38)
#26     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:462:10)
#27     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:797:9)
#28     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:607:7)
#29     Timeline.timeSync (dart:developer/timeline.dart:173:22)
#30     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:588:14)
#31     serializeComponent (file:///b/f/w/pkg/vm/bin/kernel_service.dart:1031:11)
#32     _processLoadRequest (file:///b/f/w/pkg/vm/bin/kernel_service.dart:931:13)
<asynchronous suspension>
```

**Comment by eernstg** [comment]
@johnniwinther, I think this issue has been resolved. I see error messages (as expected), not unhandled exceptions in the CFE. I'll close it, please reopen if you disagree.
