### ISSUE TITLE
[dart2wasm] Compiler crash when using ffi Structs as a paramter to @Native

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#55933]
When compiling the following code via `dart compile wasm`:

```
import 'dart:ffi' as ffi;
 
final class CXString extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;
 
  @ffi.UnsignedInt()
  external int private_flags;
}
 
@ffi.Native<ffi.Pointer<ffi.Char> Function(CXString)>()
external ffi.Pointer<ffi.Char> clang_getCString(
  CXString string,
);
 
void main(List<String> arguments) {
  print("Hello World");
}
```

This causes a compiler crash: 

```
Unhandled exception:
Crash when compiling:
Null check operator used on a null value

#0      WasmFfiNativeTransformer._convertFfiTypeToWasmType (package:dart2wasm/ffi_native_transformer.dart:351)
#1      WasmFfiNativeTransformer.visitProcedure (package:dart2wasm/ffi_native_transformer.dart:171)
#2      Procedure.accept (package:kernel/ast.dart:3233)
#3      Transformer.transform (package:kernel/visitor.dart:1771)
#4      Transformer.transformList (package:kernel/visitor.dart:1788)
#5      Library.transformChildren (package:kernel/ast.dart:617)
#6      Transformer.defaultTreeNode (package:kernel/visitor.dart:1805)
#7      TreeVisitorDefault.defaultExpression (package:kernel/visitor.dart:618)
#8      FfiTransformer.visitLibrary (package:vm/modular/transformations/ffi/common.dart:678)
#9      FfiNativeTransformer.visitLibrary (package:vm/modular/transformations/ffi/native.dart:97)
#10     List.forEach (dart:core-patch/growable_array.dart:417)
#11     transformLibraries (package:dart2wasm/ffi_native_transformer.dart:54)
#12     WasmTarget.performModularTransformationsOnLibraries (package:dart2wasm/target.dart:304)
#13     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1601)
#14     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:664)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#16     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:613)
<asynchronous suspension>
#17     _buildInternal (package:front_end/src/kernel_generator_impl.dart:227)
<asynchronous suspension>
#18     withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#19     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#20     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:130)
<asynchronous suspension>
#21     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#22     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50)
<asynchronous suspension>
#23     compileToModule (package:dart2wasm/compile.dart:117)
<asynchronous suspension>
#24     generateWasm (package:dart2wasm/generate_wasm.dart:23)
<asynchronous suspension>
#25     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/dart2wasm/bin/dart2wasm.dart:10)
<asynchronous suspension>
```

Something about our mapping of ffi types is broken here.

**Comment by mkustermann** [comment]
We should have disallowed importing `dart:ffi` so one cannot run into this anymore, right?

As mentioned in may places, dart2wasm doesn't support `dart:ffi` at this moment. We do support a small subset of it, sufficient for skwasm.

The tracking bug for adding web support for `dart:ffi` is https://github.com/dart-lang/sdk/issues/46690 (structs-by-value is only one of the many `dart:ffi` things that haven't been implemented in dart2wasm)

If this isn't an immediate issue for skwasm (@eyebrowsoffire is it?) itself, then I suggest we close it in favor of https://github.com/dart-lang/sdk/issues/46690.

**Comment by mkustermann** [comment]
As we currently don't really support `dart:ffi`s full feature set and do not allow 3rd parties to import it anymore, I consider this more a feature request for `dart:ffi` for the web (or the specific struct-by-value feature) instead of a report of a bug.

So will close this in favor of the more general [support dart:ffi on the web](https://github.com/dart-lang/sdk/issues/46690). We have started discussions on this topic on the compiler teams and evaluate how we want to expose this in a way that makes sense for the product.

I hope that's ok.
