### ISSUE TITLE
Analyzer crash report: Invalid argument(s): Missing library

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#56013]
ArgumentError:

```none
Invalid argument(s): Missing library: package:xyz
Libraries: [dart:async, dart:collection, dart:convert, dart:core, dart:_internal, dart:math, dart:typed_data, package:abc
Root children: [dart:async, dart:collection, dart:convert, dart:core, dart:_internal, dart:math, dart:typed_data, package:abc
Readers: [dart:async, dart:collection, dart:convert, dart:core, dart:_internal, dart:math, dart:typed_data, package:abc
Log: [load][targetLibrary: package:xyz
[load][targetLibrary: package:xyz
[load][targetLibrary: <path>
[removeLibraries][uriSet: {package:xyz
#1      LibraryContext.remove (package:analyzer<path>
#2      AnalysisDriver._removePotentiallyAffectedLibraries (package:analyzer<path>
#3      AnalysisDriver._applyPendingFileChanges (package:analyzer<path>
#4      <filename> (package:analyzer<path>
<asynchronous suspension>
]
[load][targetLibrary: package:xyz
[load][targetLibrary: package:xyz
[load][targetLibrary: package:xyz
[load][targetLibrary: package:xyz
[load][targetLibrary: package:xyz
[load][targetLibrary: package:xyz
```

Stack trace:

```none
#1      LibraryContext.remove (package:analyzer<path>
#2      AnalysisDriver._removePotentiallyAffectedLibraries (package:analyzer<path>
#3      AnalysisDriver._applyPendingFileChanges (package:analyzer<path>
#4      
at LinkedElementFactory.createLibraryElementForReading	(linked_element_factory.dart:153)
at LinkedElementFactory.elementOfReference	(linked_element_factory.dart:212)
at LinkedElementFactory.libraryOfUri	(linked_element_factory.dart:241)
at LinkedElementFactory.libraryOfUri2	(linked_element_factory.dart:245)
at ResolutionReader.libraryOfUri	(bundle_reader.dart:1988)
at LibraryElementLinkedData._readLibraryOrAugmentation	(bundle_reader.dart:628)
at LibraryElementLinkedData._read	(bundle_reader.dart:577)
at ElementLinkedData.read	(bundle_reader.dart:254)
at LibraryElementLinkedData.read	(bundle_reader.dart:561)
at LibraryElementImpl.exportNamespace	(element.dart:4235)
at LibraryElementExtensions.exportedExtensions	(element.dart:61)
at _ImportLibraryContainingExtension.compute	(import_library.dart:484)
at FixProcessor._addFromProducers.compute	(fix_processor.dart:111)
at FixProcessor._addFromProducers	(fix_processor.dart:147)
at <asynchronous gap>	(async)
at FixProcessor.compute	(fix_processor.dart:76)
at <asynchronous gap>	(async)
at computeFixes	(fix_internal.dart:1719)
at <asynchronous gap>	(async)
at DartCodeActionsProducer.getFixActions	(dart.dart:178)
at <asynchronous gap>	(async)
at OperationPerformanceImpl.runAsync	(operation_performance.dart:174)
at <asynchronous gap>	(async)
at CodeActionHandler.handle.<fn>.<fn>	(handler_code_actions.dart:227)
at <asynchronous gap>	(async)
at ErrorOrRecord2Extension.mapResults	(error_or.dart:125)
at <asynchronous gap>	(async)
at ErrorOr.mapResult	(error_or.dart:94)
at <asynchronous gap>	(async)
at ServerStateMessageHandler.handleMessage	(handlers.dart:397)
at <asynchronous gap>	(async)
at LspAnalysisServer._handleRequestMessage	(lsp_analysis_server.dart:1006)
at <asynchronous gap>	(async)
at LspAnalysisServer.handleMessage.<fn>.<fn>	(lsp_analysis_server.dart:461)
at <asynchronous gap>	(async)
at OperationPerformanceImpl.runAsync	(operation_performance.dart:174)
at <asynchronous gap>	(async)
at LspAnalysisServer.handleMessage.<fn>	(lsp_analysis_server.dart:444)
```

Seen in, at least, 3.5.0-234.0.dev, 3.5.0-236.0.dev, 3.5.0-238.0.dev, 3.5.0-250.0.dev, 3.5.0-254.0.dev

**Comment by bwilkerson** [comment]
@scheglov

**Comment by keertip** [comment]
Still seen in 3.5.0-323.0.dev

**Comment by scheglov** [comment]
My long time hypothesis is that this is caused by attempt to run multiple async operations in parallel. Probably here quick fix, file system change event, and the analysis driver. We need to run them sequentially. AFAIK now there is a plan to do this.

**Comment by LahaLuhem** [comment]
Reproduced on 3.13.4, no cache state involve. Tt happens from a fresh pub get in an empty package.
```dart
// lib/owner.dart
/// @docImport 'member.dart';
library;

part 'member.dart';
```

```dart
// lib/member.dart
part of 'owner.dart';
```

Running `dart analyze .`:
```console
Internal error: Invalid argument(s): Missing library: package:docimport_part_repro/member.dart
#0      LinkedElementFactory._reportMissingLibrary (package:analyzer/src/summary2/linked_element_factory.dart:277)
#1      LinkedElementFactory.libraryOfUri2 (package:analyzer/src/summary2/linked_element_factory.dart:176)
#2      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:838)
#3      LibraryAnalyzer._parseAndResolve (package:analyzer/src/dart/analysis/library_analyzer.dart:690)
```

The trigger is a `@docImport` pointing at a file that is a `part of` something. Written as a plain `import`, the same reference reports `import_of_non_library` correctly, so only the doc-import path seems to be missing the check:
