### ISSUE TITLE
[Augmentations] Analyzer crash when analyzing augmentations

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#56144]
Two king of crashes. The first:

```
/====================================================================================================================\
| co19/LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t18 is new and failed (Crash, expected Pass) |
\====================================================================================================================/

--- Command "dart2analyzer" (took 131ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/gen/dartanalyzer.dart.snapshot -Dtest_runner.configuration=analyzer-asserts-linux --enable-experiment=macros --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json --format=json /b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t18.dart

analyzer json parse result:
- parse failed

exit code:
253

stderr:
Unhandled exception:
type 'AugmentedExpressionImpl' is not a subtype of type 'IdentifierImpl' in type cast
#0      AstBuilder.handleType (package:analyzer/src/fasta/ast_builder.dart:5543:22)
#1      SimpleNullableType.parseTypeRest (package:_fe_analyzer_shared/src/parser/type_info_impl.dart:331:21)
#2      SimpleType.parseType (package:_fe_analyzer_shared/src/parser/type_info_impl.dart:386:12)
#3      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3856:28)
#4      Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3619:14)
#5      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:617:14)
#6      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:412:15)
#7      Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:96:32)
#8      Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:92:12)
#9      FileState.parseCode.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:572:25)
#10     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:155:23)
#11     FileState.parseCode (package:analyzer/src/dart/analysis/file_state.dart:551:24)
#12     FileState.getParsed (package:analyzer/src/dart/analysis/file_state.dart:508:16)
#13     FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:777:16)
#14     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:625:29)
#15     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:155:23)
#16     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:624:17)
#17     FileSystemState._newFile.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:1598:12)
#18     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:155:23)
#19     FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1597:17)
#20     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:1424:14)
#21     FileState._buildDirectiveUri (package:analyzer/src/dart/analysis/file_state.dart:682:34)
#22     LibraryOrAugmentationFileKind.augmentationImports.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:2214:22)
#23     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#24     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#25     new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:163:27)
#26     new _List.of (dart:core-patch/array.dart:128:20)
#27     new List.of (dart:core-patch/array_patch.dart:39:50)
#28     ListIterable.toList (dart:_internal/iterable.dart:224:7)
#29     IterableExtension.toFixedList (package:analyzer/src/utilities/extensions/collection.dart:22:12)
#30     LibraryOrAugmentationFileKind.augmentationImports (package:analyzer/src/dart/analysis/file_state.dart:2238:8)
#31     LibraryFileKind.augmentations.visitAugmentations (package:analyzer/src/dart/analysis/file_state.dart:1854:31)
#32     LibraryFileKind.augmentations (package:analyzer/src/dart/analysis/file_state.dart:1864:5)
#33     _LibraryNode.computeDependencies (package:analyzer/src/dart/analysis/library_graph.dart:189:46)
#34     Node.getDependencies (package:_fe_analyzer_shared/src/util/dependency_walker.dart:150:40)
#35     DependencyWalker.walk.strongConnect (package:_fe_analyzer_shared/src/util/dependency_walker.dart:55:40)
#36     DependencyWalker.walk (package:_fe_analyzer_shared/src/util/dependency_walker.dart:121:5)
#37     computeLibraryCycle (package:analyzer/src/dart/analysis/library_graph.dart:20:17)
#38     LibraryFileKind.libraryCycle (package:analyzer/src/dart/analysis/file_state.dart:1891:7)
#39     LibraryContext.load.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:291:32)
#40     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:155:23)
#41     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:288:38)
#42     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:21)
#43     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:287:18)
#44     AnalysisDriver._getUnitElement.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1870:34)
#45     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:29)
#46     AnalysisDriver._getUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1867:27)
#47     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:29)
#48     AnalysisDriver._getUnitElement (package:analyzer/src/dart/analysis/driver.dart:1858:44)
#49     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1219:13)
#50     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2449:24)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n analyzer-asserts-linux co19/LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t18
```
And the second:
```
/====================================================================================================================\
| co19/LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t21 is new and failed (Crash, expected Pass) |
\====================================================================================================================/

--- Command "dart2analyzer" (took 146ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/gen/dartanalyzer.dart.snapshot -Dtest_runner.configuration=analyzer-asserts-linux --enable-experiment=macros --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json --format=json /b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t21.dart

analyzer json parse result:
- parse failed

exit code:
253

stderr:
Unhandled exception:
type 'AugmentedExpressionImpl' is not a subtype of type 'SimpleIdentifierImpl' in type cast
#0      AstBuilder.handleNamedArgument (package:analyzer/src/fasta/ast_builder.dart:4911:22)
#1      Parser.parseArgumentsRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7765:35)
#2      Parser.parseArguments (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7739:12)
#3      Parser.parseArgumentsOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7720:14)
#4      Parser.parseSend (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7659:13)
#5      Parser.parseSendOrFunctionLiteral (package:_fe_analyzer_shared/src/parser/parser_impl.dart:7182:12)
#6      Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6541:14)
#7      Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6432:12)
#8      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5875:13)
#9      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5815:15)
#10     Parser.parseExpressionStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5776:13)
#11     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8169:16)
#12     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5576:14)
#13     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5566:20)
#14     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5471:15)
#15     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3884:13)
#16     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3619:14)
#17     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:617:14)
#18     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:412:15)
#19     Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:96:32)
#20     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:92:12)
#21     FileState.parseCode.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:572:25)
#22     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:155:23)
#23     FileState.parseCode (package:analyzer/src/dart/analysis/file_state.dart:551:24)
#24     FileState.getParsed (package:analyzer/src/dart/analysis/file_state.dart:508:16)
#25     FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:777:16)
#26     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:625:29)
#27     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:155:23)
#28     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:624:17)
#29     FileSystemState._newFile.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:1598:12)
#30     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:155:23)
#31     FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1597:17)
#32     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:1424:14)
#33     FileState._buildDirectiveUri (package:analyzer/src/dart/analysis/file_state.dart:682:34)
#34     LibraryOrAugmentationFileKind.augmentationImports.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:2214:22)
#35     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#36     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#37     new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:163:27)
#38     new _List.of (dart:core-patch/array.dart:128:20)
#39     new List.of (dart:core-patch/array_patch.dart:39:50)
#40     ListIterable.toList (dart:_internal/iterable.dart:224:7)
#41     IterableExtension.toFixedList (package:analyzer/src/utilities/extensions/collection.dart:22:12)
#42     LibraryOrAugmentationFileKind.augmentationImports (package:analyzer/src/dart/analysis/file_state.dart:2238:8)
#43     LibraryFileKind.augmentations.visitAugmentations (package:analyzer/src/dart/analysis/file_state.dart:1854:31)
#44     LibraryFileKind.augmentations (package:analyzer/src/dart/analysis/file_state.dart:1864:5)
#45     _LibraryNode.computeDependencies (package:analyzer/src/dart/analysis/library_graph.dart:189:46)
#46     Node.getDependencies (package:_fe_analyzer_shared/src/util/dependency_walker.dart:150:40)
#47     DependencyWalker.walk.strongConnect (package:_fe_analyzer_shared/src/util/dependency_walker.dart:55:40)
#48     DependencyWalker.walk (package:_fe_analyzer_shared/src/util/dependency_walker.dart:121:5)
#49     computeLibraryCycle (package:analyzer/src/dart/analysis/library_graph.dart:20:17)
#50     LibraryFileKind.libraryCycle (package:analyzer/src/dart/analysis/file_state.dart:1891:7)
#51     LibraryContext.load.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:291:32)
#52     OperationPerformanceImpl.run (package:analyzer/src/util/performance/operation_performance.dart:155:23)
#53     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:288:38)
#54     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:21)
#55     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:287:18)
#56     AnalysisDriver._getUnitElement.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1870:34)
#57     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:29)
#58     AnalysisDriver._getUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1867:27)
#59     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:29)
#60     AnalysisDriver._getUnitElement (package:analyzer/src/dart/analysis/driver.dart:1858:44)
#61     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1219:13)
#62     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2449:24)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n analyzer-asserts-linux co19/LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t21
```

**Comment by sgrekhov** [comment]
No these crashes now. Closing.
