### ISSUE TITLE
UnusedLocalElementsVerifier attempts to use fragment to ask the interface

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#56184]
See https://github.com/dart-lang/sdk/issues/55931#issuecomment-2215487330

```
Unhandled exception:
Invalid argument(s): Interfaces can only be asked for declarations
#0      InheritanceManager3.getInterface (package:analyzer/src/dart/element/inheritance_manager3.dart:223:7)
#1      InheritanceManager3.getOverridden2 (package:analyzer/src/dart/element/inheritance_manager3.dart:327:21)
#2      UnusedLocalElementsVerifier._overriddenElements (package:analyzer/src/error/unused_local_elements_verifier.dart:935:31)
#3      UnusedLocalElementsVerifier._overridesUsedParameter (package:analyzer/src/error/unused_local_elements_verifier.dart:956:30)
#4      UnusedLocalElementsVerifier._isUsedElement (package:analyzer/src/error/unused_local_elements_verifier.dart:895:13)
#5      UnusedLocalElementsVerifier.visitFormalParameterList (package:analyzer/src/error/unused_local_elements_verifier.dart:588:12)
#6      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7603:50)
#7      ConstructorDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4297:17)
#8      RecursiveAstVisitor.visitConstructorDeclaration (package:analyzer/dart/ast/visitor.dart:996:10)
#9      UnusedLocalElementsVerifier.visitConstructorDeclaration (package:analyzer/src/error/unused_local_elements_verifier.dart:524:11)
```

**Comment by goderbauer** [comment]
Thank you for taking a look at this!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/374843
