### ISSUE TITLE
standalone/io/unix_socket_test went from flaky -> RuntimeError on vm-reload-linux-debug-x64

### ISSUE THREAD

**Issue by derekxu16** [dart-lang/sdk#56268]
The tests
```
standalone/io/unix_socket_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-reload-linux-debug-x64
```

```
stderr:
Unhandled exception:
Expect.fail('Unexpected exception SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = /b/s/w/it4m8w7g3a/unix_socket_testACCJIL/sock, port = 0 is thrown:
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1252:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:2010:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2487:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2222:28)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2174:11)
#5      _rootRunUnary (dart:async/zone.dart:1407:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#11     _StreamController._add (dart:async/stream_controller.dart:658:7)
#12     _StreamController.add (dart:async/stream_controller.dart:606:5)
#13     _StreamSinkImpl.add (dart:io/io_sink.dart:154:17)
#14     _IOSinkImpl.write (dart:io/io_sink.dart:287:5)
#15     _Socket.write (dart:io-patch/socket_patch.dart:2320:36)
#16     testSetSockOpt (file:///b/s/w/ir/tests/standalone/io/unix_socket_test.dart:270:10)
<asynchronous suspension>
#17     main.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/standalone/io/unix_socket_test.dart:1069:7)
<asynchronous suspension>
#18     withTempDir (file:///b/s/w/ir/tests/standalone/io/test_utils.dart:45:5)
<asynchronous suspension>
#19     main.<anonymous closure> (file:///b/s/w/ir/tests/standalone/io/unix_socket_test.dart:1068:5)
<asynchronous suspension>
')
```

https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-reload-linux-debug-x64/518/overview

**Comment by derekxu16** [comment]
cc @brianquinlan

**Comment by derekxu16** [comment]
happened again: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-reload-linux-debug-x64/630/overview

**Comment by mkustermann** [comment]
This also seems to happen in release mode, see [log](https://dart-ci.appspot.com/log/vm-reload-linux-release-x64/vm-reload-linux-release-x64/592/standalone/io/unix_socket_test)
```
--- Command "vm" (took 08.000865s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --hot-reload-test-mode --sound-null-safety -Dtest_runner.configuration=vm-reload-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/standalone/io/unix_socket_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.fail('Unexpected exception SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = /b/s/w/itmws4eefe/unix_socket_testRWCACX/sock, port = 0 is thrown:
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1475:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:2389:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2925:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2648:28)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2596:13)
#5      _rootRunUnary (dart:async/zone.dart:1538:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1429:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1329:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:798:19)
#11     _StreamController._add (dart:async/stream_controller.dart:663:7)
#12     _StreamController.add (dart:async/stream_controller.dart:618:5)
#13     _StreamSinkImpl.add (dart:io/io_sink.dart:155:17)
#14     _IOSinkImpl.write (dart:io/io_sink.dart:296:5)
#15     _Socket.write (dart:io-patch/socket_patch.dart:2754:36)
#16     testSetSockOpt (file:///b/s/w/ir/tests/standalone/io/unix_socket_test.dart:270:10)
<asynchronous suspension>
#17     main.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/standalone/io/unix_socket_test.dart:1069:7)
<asynchronous suspension>
#18     withTempDir (file:///b/s/w/ir/tests/standalone/io/test_utils.dart:45:5)
<asynchronous suspension>
#19     main.<anonymous closure> (file:///b/s/w/ir/tests/standalone/io/unix_socket_test.dart:1068:5)
<asynchronous suspension>
')
#0      Expect._fail (package:expect/expect.dart:880:5)
#1      Expect.fail (package:expect/expect.dart:349:5)
#2      main.<anonymous closure> (file:///b/s/w/ir/tests/standalone/io/unix_socket_test.dart:1112:14)
#3      _RootZone.runBinary (dart:async/zone.dart:1854:54)
#4      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:2002:18)
#5      _Zone._processUncaughtError (dart:async/zone.dart:1178:14)
#6      _ZoneDelegate.handleUncaughtError (dart:async/zone.dart:1033:23)
#7      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:2005:16)
#8      _Zone._processUncaughtError (dart:async/zone.dart:1178:14)
#9      _CustomZone.handleUncaughtError (dart:async/zone.dart:1399:5)
#10     Future._propagateToListeners (dart:async/future_impl.dart:832:24)
#11     Future._completeError (dart:async/future_impl.dart:730:5)
#12     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:816:7)
#13     _rootRun (dart:async/zone.dart:1525:13)
#14     _CustomZone.run (dart:async/zone.dart:1422:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1321:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1362:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:128:13)
#20     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:195:5)

--- Re-run this test:
python3 tools/test.py -n vm-reload-linux-release-x64 standalone/io/unix_socket_test
```
