### ISSUE TITLE
vm/dart/isolates/shared_primitives_test changing from flaky to RTE on vm-reload-linux-debug-x64

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#56277]
There are new test failures on [[wildcards] Call Hierarchy target tests...[cfe] Move scope/exportScope to Dill/SourceLibraryBuilder](https://github.com/dart-lang/sdk/compare/5ebf704aa49c6f6d2651f0823f1441e2a6bdd180~...5995cf6b00b7d27d88ba0afc3219ac95f594fb22).

The tests
```
vm/dart/isolates/shared_primitives_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-reload-linux-debug-x64
```

Looking at the history and the flakiness dashboard, the test has been flaky on this configuration and on `vm-reload-rollback-linux-debug-x64` since it was added in d2bc05565. Looking at the [log](), the error is in the `exitCode` check that's gated by a version `contains` check:

```
--- Command "vm" (took 02:06.000435s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --hot-reload-test-mode --sound-null-safety -Dtest_runner.configuration=vm-reload-linux-debug-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/runtime/tests/vm/dart/isolates/shared_primitives_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: <0>, actual: <255>) fails.
#0      Expect._fail (package:expect/expect.dart:881:5)
#1      Expect._failNotEqual (package:expect/expect.dart:174:5)
#2      Expect.equals (package:expect/expect.dart:157:5)
#3      main (file:///b/s/w/ir/runtime/tests/vm/dart/isolates/shared_primitives_test.dart:78:16)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-reload-linux-debug-x64 vm/dart/isolates/shared_primitives_test
```

The same failure also shows up in the RTE entries in the flakiness dashboard for `vm-reload-rollback-linux-debug-x64`.

**Comment by alexmarkov** [comment]
Similarly, `vm/dart/isolates/shared_primitives_test` turned flaky -> RuntimeError on `vm-reload-rollback-linux-debug-x64`:

```
--- Command "vm" (took 01:59.000790s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --hot-reload-rollback-test-mode --sound-null-safety -Dtest_runner.configuration=vm-reload-rollback-linux-debug-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/runtime/tests/vm/dart/isolates/shared_primitives_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: <0>, actual: <255>) fails.
#0      Expect._fail (package:expect/expect.dart:881:5)
#1      Expect._failNotEqual (package:expect/expect.dart:174:5)
#2      Expect.equals (package:expect/expect.dart:157:5)
#3      main (file:///b/s/w/ir/runtime/tests/vm/dart/isolates/shared_primitives_test.dart:78:16)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-reload-rollback-linux-debug-x64 vm/dart/isolates/shared_primitives_test
```
https://dart-ci.appspot.com/log/vm-reload-rollback-linux-debug-x64/vm-reload-rollback-linux-debug-x64/492/vm/dart/isolates/shared_primitives_test
