### ISSUE TITLE
Analyzer exception doesn't specify affected file

### ISSUE THREAD

**Issue by Lootwig** [dart-lang/sdk#56281]
Encountering this trying to run `dart fix --apply`:

<details>
<summary>Console output</summary>
```
Internal error: Exception while using a AvoidRedundantArgumentValues to visit a FunctionExpressionInvocationImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ListLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
Bad state: [library: null][this: (DefaultParameterElementImpl) {double? height}][enclosingElement: null][reference: null]
#0      ConstVariableElement.computeConstantValue (package:analyzer/src/dart/element/element.dart:1292:9)
#1      _Visitor.checkArgument (package:linter/src/rules/avoid_redundant_argument_values.dart:105:23)
#2      _Visitor.check (package:linter/src/rules/avoid_redundant_argument_values.dart:88:7)
#3      _Visitor.visitFunctionExpressionInvocation (package:linter/src/rules/avoid_redundant_argument_values.dart:126:5)
#4      FunctionExpressionInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8382:15)
#5      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:1096:14)
#6      LinterVisitor.visitFunctionExpressionInvocation (package:analyzer/src/lint/linter_visitor.dart:446:5)
#7      FunctionExpressionInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8382:15)
#8      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:12187:17)
#9      LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:663:10)
#10     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:12177:50)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12587:20)
#12     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:498:16)
#13     LinterVisitor.visitArgumentList (package:analyzer/src/lint/linter_visitor.dart:45:10)
#14     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:494:50)
#15     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10138:19)
#16     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:537:10)
#17     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:10127:15)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12587:20)
#19     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10978:15)
#20     LinterVisitor.visitListLiteral (package:analyzer/src/lint/linter_visitor.dart:597:10)
#21     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:10968:50)
#22     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:12187:17)
#23     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:663:10)
#24     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:12177:50)
#25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12587:20)
#26     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:498:16)
#27     LinterVisitor.visitArgumentList (package:analyzer/src/lint/linter_visitor.dart:45:10)
#28     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:494:50)
#29     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10138:19)
#30     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:537:10)
#31     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:10127:15)
#32     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:12187:17)
#33     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:663:10)
#34     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:12177:50)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12587:20)
#36     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:498:16)
#37     LinterVisitor.visitArgumentList (package:analyzer/src/lint/linter_visitor.dart:45:10)
#38     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:494:50)
#39     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10138:19)
#40     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:537:10)
#41     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:10127:15)
#42     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:15092:18)
#43     LinterVisitor.visitReturnStatement (package:analyzer/src/lint/linter_visitor.dart:873:10)
#44     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:15088:50)
#45     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12587:20)
#46     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2091:17)
#47     LinterVisitor.visitBlock (package:analyzer/src/lint/linter_visitor.dart:111:10)
#48     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:2087:50)
#49     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2047:12)
#50     LinterVisitor.visitBlockFunctionBody (package:analyzer/src/lint/linter_visitor.dart:117:10)
#51     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:2039:50)
#52     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11697:10)
#53     LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:639:10)
#54     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11689:50)
#55     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12587:20)
#56     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2954:13)
#57     LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:165:10)
#58     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2944:50)
#59     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12587:20)
#60     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3618:21)
#61     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:189:10)
#62     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:3611:50)
#63     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:406:12)
#64     LibraryAnalyzer._computeDiagnostics (package:analyzer/src/dart/analysis/library_analyzer.dart:331:7)
#65     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:109:5)
#66     AnalysisDriver._analyzeFileImpl.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1394:11)
<asynchronous suspension>
#67     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#68     AnalysisDriver._analyzeFile.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1308:9)
<asynchronous suspension>
#69     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#70     AnalysisDriver._analyzeFile (package:analyzer/src/dart/analysis/driver.dart:1305:5)
<asynchronous suspension>
#71     AnalysisDriver._getErrors (package:analyzer/src/dart/analysis/driver.dart:1739:5)
<asynchronous suspension>
#72     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1207:7)
<asynchronous suspension>
#73     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2449:7)
<asynchronous suspension>
```
</details>

When trying to pin down the problematic file(s) by running folder-by-folder, the error stopped occurring after processing a folder's subdirs (upon whose analysis the exception occurred) individually. None raised the error when analyzed by itself, after which the parent ran just fine as well.

Request: **It would be super helpful to include the currently processed file's _path_ whenever an exception is thrown.**

**Comment by Lootwig** [comment]
Update: I can reproduce the exception on _the very fist run_ of `dart fix --apply` after running `pub get`. If there were no fixes applied and I don't touch any files, the error does not appear again on subsequent runs.

**Comment by srawlins** [comment]
Great request! Might be tricky to implement, as we cannot collect any personally identifiable info, including file paths, in our crash reporting. A very good feature to have though.
