### ISSUE TITLE
[gardening] ASAN failure on [VM/Runtime] Ensure errno is saved to ensure it is not clobbered by a subsequent operation.

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#56299]
There are new test failures on [[VM/Runtime] Ensure errno is saved to ensure it is not clobbered by a subsequent operation.](https://github.com/dart-lang/sdk/commit/424c25450bebde379e653cf73e4c350f27097673).

The tests
```
standalone/io/file_test Crash (expected Pass)
standalone/io/read_into_const_list_test Crash (expected Pass)
```
are failing on configurations
```
vm-aot-asan-linux-release-x64
vm-asan-linux-release-x64
```

The captured error string doesn't seem to be released anywhere.

```
Direct leak of 26 byte(s) in 1 object(s) allocated from:
    #0 0x5623ae530dca in strdup ../../../../../../llvm-llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:593:3
    #1 0x5623af3b2a9b in dart::bin::OSError::SetMessage(char const*) out/ReleaseASANX64/../../runtime/bin/utils.h:47:18
    #2 0x5623af3b2a9b in dart::bin::OSError::SetCodeAndMessage(dart::bin::OSError::SubSystem, int) out/ReleaseASANX64/../../runtime/bin/utils_linux.cc:34:5
    #3 0x5623af3b2a9b in dart::bin::OSError::Reload() out/ReleaseASANX64/../../runtime/bin/utils_linux.cc:25:3
    #4 0x5623af3b2a9b in dart::bin::OSError::OSError() out/ReleaseASANX64/../../runtime/bin/utils_linux.cc:21:3
    #5 0x5623af398be1 in dart::bin::Builtin_File_ReadInto(_Dart_NativeArguments*) out/ReleaseASANX64/../../runtime/bin/file.cc:255:11
    #6 0x5623aeb19ce9 in dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) out/ReleaseASANX64/../../runtime/vm/native_entry.cc:219:7
    #7 0x7f836e783293  (<unknown module>)
    #8 0x7f836be3e307  (<unknown module>)
    #9 0x7f836be3dca4  (<unknown module>)
    #10 0x7f836be7e542  (<unknown module>)
    #11 0x7f836be5565c  (<unknown module>)
    #12 0x7f836be7e302  (<unknown module>)
    #13 0x7f836be69ada  (<unknown module>)
    #14 0x7f836be27765  (<unknown module>)
    #15 0x7f836be696e8  (<unknown module>)
    #16 0x7f836be64fdf  (<unknown module>)
    #17 0x7f836be64cdc  (<unknown module>)
    #18 0x7f836be649c7  (<unknown module>)
    #19 0x7f836be63bac  (<unknown module>)
    #20 0x7f836be628ed  (<unknown module>)
    #21 0x7f836be626e6  (<unknown module>)
    #22 0x7f836be62486  (<unknown module>)
    #23 0x7f836be620f1  (<unknown module>)
    #24 0x7f836be62012  (<unknown module>)
    #25 0x7f836be5f878  (<unknown module>)
    #26 0x7f836be24fc5  (<unknown module>)
    #27 0x7f836e7834d5  (<unknown module>)
    #28 0x5623aea0f90c in dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&) out/ReleaseASANX64/../../runtime/vm/dart_entry.cc:125:33
    #29 0x5623aea13f34 in dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&) out/ReleaseASANX64/../../runtime/vm/dart_entry.cc:37:10
    #30 0x5623aea13f34 in dart::DartLibraryCalls::HandleMessage(long, dart::Instance const&) out/ReleaseASANX64/../../runtime/vm/dart_entry.cc:717:28
    #31 0x5623aea7e0f7 in dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message>>) out/ReleaseASANX64/../../runtime/vm/isolate.cc:1461:15
    #32 0x5623aeaec220 in dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) out/ReleaseASANX64/../../runtime/vm/message_handler.cc:238:16
    #33 0x5623aeaecb40 in dart::MessageHandler::TaskCallback() out/ReleaseASANX64/../../runtime/vm/message_handler.cc:457:18

SUMMARY: AddressSanitizer: 26 byte(s) leaked in 1 allocation(s).
```

https://dart-ci.appspot.com/log/vm-aot-asan-linux-release-x64/vm-aot-asan-linux-release-x64/490/standalone/io/file_test

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/377780
