### ISSUE TITLE
Running `dart devtools` with `dart` on `PATH` fails on 3.5.1

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#56499]
Running `dart devtools` fails with an exception when running from `PATH` on the latest stable release:

```
❯ PATH=~/dart-sdk/sdk/out/ReleaseX64/dart-sdk/bin:$PATH dart devtools
Invalid argument(s): A directory corresponding to fileSystemPath "/usr/local/google/home/bkonyi/dart-sdk/sdk/./devtools" could not be found
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      defaultHandler (package:dds/src/devtools/handler.dart:62:38)
#2      DevToolsServer.serveDevTools (package:dds/devtools_server.dart:298:23)
<asynchronous suspension>
#3      DevToolsServer.serveDevToolsWithArgs (package:dds/devtools_server.dart:458:12)
<asynchronous suspension>
#4      DevToolsCommand.run (package:dartdev/src/commands/devtools.dart:58:20)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      DartdevRunner.runCommand (package:dartdev/dartdev.dart:236:18)
<asynchronous suspension>
#7      runDartdev (package:dartdev/dartdev.dart:47:16)
<asynchronous suspension>
#8      main (file:///b/f/w/pkg/dartdev/bin/dartdev.dart:13:5)
<asynchronous suspension>
```

**Comment by bkonyi** [comment]
This issue was resolved by [this CL](https://dart-review.googlesource.com/c/sdk/+/376860) but should be CP'd into stable.
