### ISSUE TITLE
Failures on [ DAP ] Migrate DAP to launch DDS with DartDevelopmentServiceLauncher

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#56557]
There are new test failures on [[ DAP ] Migrate DAP to launch DDS with DartDevelopmentServiceLauncher](https://github.com/dart-lang/sdk/commit/e0d140c01e1fcd6f822d115b14f292d08a51ada8).

The tests
```
pkg/dds/test/dap/integration/debug_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac-arm64
unittest-asserts-release-mac-x64
```

```
01:10 [32m+31[0m[33m ~1[0m[31m -1[0m: debug mode can run with ipv6 [1m[31m[E][0m[0m

  Expected: '::1'
    Actual: '127.0.0.1'
     Which: is different.
            Expected: ::1
              Actual: 127.0.0.1
                      ^
             Differ at offset 0
  

  package:matcher/src/expect/expect.dart 149:31       fail
  package:matcher/src/expect/expect.dart 144:3        _expect
  package:matcher/src/expect/expect.dart 56:3         expect
  pkg/dds/test/dap/integration/debug_test.dart 889:7  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 229:9    Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 227:7    Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9     Invoker._waitForOutstandingCallbacks.<fn>
  

01:10 [32m+31[0m[33m ~1[0m[31m -1[0m: [31mSome tests failed.[0m



Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

stderr:
STDERR output collected before app terminated:
Start
#0      main (file:///Volumes/Work/s/w/ir/x/t/dart-sdk-dap-testh5A11u/app2guALT/test_file.dart:1:2)
#1      main2 (package:foo/foo.dart:3:4)
#2      main3 (dart:isolate-patch/isolate_patch.dart:5:6)
EndSTDERR output collected before app terminated:
Start
#0      main (file:///Volumes/Work/s/w/ir/x/t/dart-sdk-dap-testp9ypwZ/appqGEzFp/test_file.dart:1:2)
#1      main2 (package:foo/foo.dart:3:4)
[2m#2      main3 (dart:isolate-patch/isolate_patch.dart:5:6)[0m
EndSTDERR output collected before app terminated:
Start
#0      main (file:///Volumes/Work/s/w/ir/x/t/dart-sdk-dap-testRr8Gof/appunMzXX/test_file.dart:1:2)
#1      main2 (package:foo/foo.dart:3:4)
#2      main3 (dart:isolate-patch/isolate_patch.dart:5:6)
EndUnhandled exception:
Dummy exception to set exit code.

--- Re-run this test:
python3 tools/test.py -n unittest-asserts-release-mac-x64 pkg/dds/test/dap/integration/debug_test
```

@bkonyi @derekxu16

**Comment by a-siva** [comment]
This is failing again here https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-win-release-arm64/2856/overview in pkg-win-release-arm64 configuration

**Comment by bkonyi** [comment]
@derekxu16 can you take a look at this when you get a chance?

**Comment by a-siva** [comment]
pkg-win-release  also had a similar failure, see https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-win-release/30217/overview
