### ISSUE TITLE
An unexpected error was encountered by the Analysis Server.

### ISSUE THREAD

**Issue by yevyevyev** [dart-lang/sdk#56561]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.1 23B2073 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.92.2)
[✓] Connected device (5 available)
[✓] Network resources
```

```
Internal error: Exception while using a AvoidRedundantArgumentValues to visit a FunctionExpressionInvocationImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
Bad state: [library: null][this: (DefaultParameterElementImpl) {double? height}][enclosingElement: null][reference: null]
#0      ConstVariableElement.computeConstantValue (package:analyzer/src/dart/element/element.dart:1292:9)
#1      _Visitor.checkArgument (package:linter/src/rules/avoid_redundant_argument_values.dart:105:23)
#2      _Visitor.check 
(package:linter/src/rules/avoid_redundant_argument_values.dart:88:7)
#3      _Visitor.visitFunctionExpressionInvocation (package:linter/src/rules/avoid_redundant_argument_values.dart:126:5)
#4      FunctionExpressionInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8378:15)
#5      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:1096:14)
#6      LinterVisitor.visitFunctionExpressionInvocation (package:analyzer/src/lint/linter_visitor.dart:446:5)
#7      FunctionExpressionInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8378:15)
#8      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:12183:17)
#9      LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:663:10)
#10     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:12173:50) 
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12583:20)
#12     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:498:16)
#13     LinterVisitor.visitArgumentList (package:analyzer/src/lint/linter_visitor.dart:45:10)
#14     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:494:50)
#15     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10134:19)
#16     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:537:10)
#17     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:10123:15)
#18     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:15088:18)
#19     LinterVisitor.visitReturnStatement (package:a
nalyzer/src/lint/linter_visitor.dart:873:10)
#20     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:15084:50)
#21     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12583:20)
#22     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2091:17)
#23     LinterVisitor.visitBlock (package:analyzer/src/lint/linter_visitor.dart:111:10)
#24     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:2087:50)
#25     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2047:12)
#26     LinterVisitor.visitBlockFunctionBody (package:analyzer/src/lint/linter_visitor.dart:117:10)
#27     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:2039:50)
#28     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:116
93:10)
#29     LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:639:10)
#30     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11685:50)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12583:20)
#32     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2954:13)
#33     LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:165:10)
#34     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2944:50)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12583:20)
#36     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3614:21)
#37     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:189:10)
[d
#38     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:3607:50)
#39     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:398:12)
#40     LibraryAnalyzer._computeDiagnostics (package:analyzer/src/dart/analysis/library_analyzer.dart:323:7)
#41     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:108:5)
#42     AnalysisDriver._analyzeFileImpl.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1394:11)
<asynchronous suspension>
#43     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#44     AnalysisDriver._analyzeFile.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1308:9)
<asynchronous suspension>
#45     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#46     AnalysisDriver._analyzeFile (package:analyzer/src/dart/analysis/driver.dart:1305:5)
<asynchronous suspension>
#47     AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:2020:5)
<asynchronous suspension>
#48     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1245:7)
<asynchronous suspension>
#49     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2449:7)
<asynchronous suspension>
null
```

**Comment by blaugold** [comment]
Here is a minimal reproducible example:

```dart
void f({String? a}) {}

const _f = f;

void main() {
  _f(a: 'a');
}
```

**Comment by blaugold** [comment]
@srawlins Friendly ping :) This is breaking my analyze step in CI and I would love to re-enable it again.

**Comment by srawlins** [comment]
I cannot reproduce this with a version of Dart from main branch as of a few days ago. Can you try to use a super recent version of Dart, like from the Dev channel? https://dart.dev/get-dart/archive

**Comment by blaugold** [comment]
Ah yes, on the Flutter main channel, which is on Dart 3.6.0-311.0.dev, the issue is fixed. Thanks!
