### ISSUE TITLE
`BOT=true dart --enable-vm-service` crashes

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#56606]
`Dart 3.6.0-175.0.dev (dev) (Fri Aug 23 09:07:06 2024 -0700) on "macos_arm64"` (Flutter HEAD as of today).

It seems like `BOT=true` as an environment variable informs some behavior of the `dart` CLI.

Assume I create the following file, `main.dart`:
```dart
void main() {}
```

And I run it like this (from my Flutter SDK cache):

```sh
dart main.dart # OK
dart --enable-vm-service=0 #OK
BOT=true dart --enable-vm-service=0 # Crashes
BOT=true dart --enable-vm-serivce=0 --disable-dart-dev # OK
```

The crash looks like this:

```txt
Could not start the VM service:
DartDevelopmentServiceException: WebSocketChannelException: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 58823
vm-service: Error: Unhandled exception:
HttpException: HttpServer is not bound to a socket
#0      _HttpServer.address (dart:_http/http_impl.dart:3327:17)
#1      Server.serverAddress (dart:vmservice_io/vmservice_server.dart:259:25)
#2      Server.startup (dart:vmservice_io/vmservice_server.dart:616:24)
<asynchronous suspension>
#3      _toggleWebServer (dart:vmservice_io:244:5)
<asynchronous suspension>

Unhandled exception:
HttpException: HttpServer is not bound to a socket
#0      _HttpServer.address (dart:_http/http_impl.dart:3327:17)
#1      Server.serverAddress (dart:vmservice_io/vmservice_server.dart:259:25)
#2      Server.startup (dart:vmservice_io/vmservice_server.dart:616:24)
<asynchronous suspension>
#3      _toggleWebServer (dart:vmservice_io:244:5)
<asynchronous suspension>
```

**Comment by bkonyi** [comment]
Oddly enough, passing `--pause-isolates-on-exit` stops the crash:

```
BOT=1 $DART_RELEASE --enable-vm-service=0 --pause-isolates-on-exit foo.dart
hello world!
The Dart VM service is listening on http://127.0.0.1:34171/gmEUu8VMLOE=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:34171/gmEUu8VMLOE=/devtools/?uri=ws://127.0.0.1:34171/gmEUu8VMLOE=/ws
```

This makes me think there's some sort of race between the VM service startup and the VM exiting. Removing most of the analytics logic in `dartdev.dart` (this is the only code in the CLI that uses the `BOT` environment variable) also resolves the issue.
