### ISSUE TITLE
[io]: Can't catch HttpException from malformed incoming HTTP request

### ISSUE THREAD

**Issue by kenballus** [dart-lang/sdk#56623]
# The bug

I'm trying to run a simple HTTP echo server using only `dart:io`. Here's what I have so far:
```dart
import 'dart:io';
import 'dart:convert';
import 'dart:typed_data';

Future<void> main() async {
  try {
    final server = await HttpServer.bind(InternetAddress.anyIPv4, 80);
    await server.forEach((HttpRequest request) async {
      String serialized_headers = '';
      bool first = true;
      request.headers.forEach((String name, List<String> values) async {
        values.forEach((String value) {
          if (!first) {
            serialized_headers += ',';
          } else {
            first = false;
          }
          serialized_headers += '["${base64.encode(latin1.encode(name))}","${base64.encode(latin1.encode(value))}"]';
        });
      });
      String body = (await request.toList()).map<String>((Uint8List chunk) => base64.encode(chunk.toList())).join('');
      String method = base64.encode(latin1.encode(request.method));
      String uri = base64.encode(latin1.encode(request.uri.toString()));
      String version = base64.encode(latin1.encode(request.protocolVersion));
      request.response.write('{"method":"${method}","uri":"${uri}","version":"${version}","headers":[${serialized_headers}],"body":"${body}"}');
      request.response.close();
    });
  } catch (e) {}
}
```

If I send this server a request with an invalid chunked message body, it will crash with an unhandled exception, even though everything is wrapped in a generic `try...catch`:
```sh
printf 'POST / HTTP/1.1\r\nHost: a\r\nTransfer-Encoding: chunked\r\n\r\n\r\r' | nc localhost 80
```
```
Unhandled exception:
HttpException: Failed to parse HTTP, 13 does not match 10, uri = /
#0      _HttpIncoming.listen.<anonymous closure> (dart:_http/http_impl.dart:442:7)
#1      Stream.handleError.<anonymous closure> (dart:async/stream.dart:930:16)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:267:17)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:155:13)
#4      _RootZone.runBinaryGuarded (dart:async/zone.dart:1621:10)
#5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:385:15)
#6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:403:7)
#7      _DelayedError.perform (dart:async/stream_impl.dart:553:14)
#8      _PendingEvents.handleNext (dart:async/stream_impl.dart:647:11)
#9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:618:7)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#12     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

# Versions
```
- Dart 3.6.0-edge.3cc6105316be32e2d48b1b9b253247ad4fc89698 (main) (Fri Aug 30 22:53:32 2024 +0000) on "linux_x64"
- on linux / Linux 6.10.2-arch1-2 #1 SMP PREEMPT_DYNAMIC Sat, 03 Aug 2024 17:56:17 +0000
- locale is en_US
```

**Comment by kenballus** [comment]
Using a `Zone` with `handleUncaughtError` solves this problem, but you'd think that since we're `await`ing all our futures here, we shouldn't have to use this workaround.

**Comment by lrhn** [comment]
You are not awaiting all your futures.
```dart
  await server.forEach((HttpRequest request) async {
```
The [`server.forEach`](https://api.dart.dev/stable/3.5.2/dart-async/Stream/forEach.html) parameter has type `void Function(HttpRequest)`, but the argument is `async` and returns a future.
Returning a future to a `void` type means it won't be awaited, or noticed.

Its error becoming an uncaught async error reported to the `Zone` is expected.

**Comment by kenballus** [comment]
You are right. Thank you. Sorry to bother. Closing.
