### ISSUE TITLE
Bug in dart2js compilation, with records and generics 

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#56741]
[This CL](https://dart-review.googlesource.com/c/sdk/+/376640) introduces extension members on records of iterables, and uses records of iterators internally, and type variables bound to those record types to abstract over the width.

It works in all other compilers, but in dart2js something goes wrong and a record access gives `null` where it should have been an iterator ([test error](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8736561035412387297/+/u/test_results/new_test_failures__logs_)).

The failing code is in:
```dart
  (Iterator<T1>, Iterator<T2>) iterator(
          (Iterable<T1>, Iterable<T2>) iterables) =>
      (iterables.$1.iterator, iterables.$2.iterator);
```
with the error
```
TypeError: t2.get$iterator is not a function
```

I don't have a smaller reproduction yet.

**Comment by lrhn** [comment]
Slightly smaller stand-alone reproduction, which errs with the message:
```
$DART_SDK//sdk/lib/_internal/js_runtime/lib/preambles/d8.js:265: TypeError: iterables._1.get$iterator is not a function
          throw e;
          ^
TypeError: iterables._1.get$iterator is not a function
    at _IterationStrategy2.iterator$1 (repro.dart.js:2990:73)
    at _ComputedIterable.get$length (repro.dart.js:3029:24)
    at main (repro.dart.js:2519:102)
    ...
```

The `repro.dart` file is:
```dart
void main() {
  // Non-efficient length iterables.
  var i1 = [for (var i = 0; i < 16; i++) i].where((_) => true);
  var i2 = [for (var i = 0; i < 15; i++) "$i"].where((_) => true);

  // Removing this line avoids the error.
  if (15 != (i1, i2).zip.length) throw "Bad";

  // Moving this declaration above the line above, or below the line below,
  // avoids the error?
  var i3 = [for (var i = 0; i < 17; i++) i.isEven].where((_) => true);

  print("Gets here");

  // This one fails in Dart2JS:
  if (0 != (i1, <bool>[]).zip.length) throw "Bad";

  print("Does not get here");

  // Removing this line avoids the error.
  if (15 != (i1, i2, i3).zip.length) throw "Bad";
}

/// Combines pairs of iterables into a single iterable.
extension IterableZip2<T1, T2> on (Iterable<T1>, Iterable<T2>) {
  /// Iterable of pairs of corresponding elements from both sources.
  ///
  /// Has as many elements as the shorter of the source iterables.
  Iterable<(T1, T2)> get zip => _ComputedIterable<
      (T1, T2),
      (Iterable<T1>, Iterable<T2>),
      (Iterator<T1>, Iterator<T2>)>(_IterationStrategy2<T1, T2>(), this);
}

/// Combines 3-tuples of iterables into a single iterable.
extension IterableZip3<T1, T2, T3> on (
  Iterable<T1>,
  Iterable<T2>,
  Iterable<T3>
) {
  /// Iterable of tuples of corresponding elements from all sources.
  ///
  /// Has as many elements as the shortest of the source iterables.
  Iterable<(T1, T2, T3)> get zip =>
      _ComputedIterable(_IterationStrategy3<T1, T2, T3>(), this);
}

class _IterationStrategy2<T1, T2>
    implements
        _IterationStrategy<(T1, T2), (Iterable<T1>, Iterable<T2>),
            (Iterator<T1>, Iterator<T2>)> {
  (Iterator<T1>, Iterator<T2>) iterator(
          (Iterable<T1>, Iterable<T2>) iterables) =>
      (iterables.$1.iterator, iterables.$2.iterator);

  (T1, T2) current((Iterator<T1>, Iterator<T2>) iterators) =>
      (iterators.$1.current, iterators.$2.current);

  (Iterator<T1>, Iterator<T2>)? moveNext(
      (Iterator<T1>, Iterator<T2>) iterators) {
    if (iterators.$1.moveNext() && iterators.$2.moveNext()) return iterators;
    return null;
  }
}

class _IterationStrategy3<T1, T2, T3>
    implements
        _IterationStrategy<
            (T1, T2, T3),
            (Iterable<T1>, Iterable<T2>, Iterable<T3>),
            (Iterator<T1>, Iterator<T2>, Iterator<T3>)> {
  (Iterator<T1>, Iterator<T2>, Iterator<T3>) iterator(
          (Iterable<T1>, Iterable<T2>, Iterable<T3>) iterables) =>
      (iterables.$1.iterator, iterables.$2.iterator, iterables.$3.iterator);

  (Iterator<T1>, Iterator<T2>, Iterator<T3>)? moveNext(
      (Iterator<T1>, Iterator<T2>, Iterator<T3>) iterators) {
    if (iterators.$1.moveNext() &&
        iterators.$2.moveNext() &&
        iterators.$3.moveNext()) {
      return iterators;
    }
    return null;
  }

  (T1, T2, T3) current((Iterator<T1>, Iterator<T2>, Iterator<T3>) iterators) {
    var (it1, it2, it3) = iterators;
    return (it1.current, it2.current, it3.current);
  }
}

/// General implementation of iterable based on some other iteration.
///
/// The type [T] is the element type of the iteration, the type [S]
/// is the state of an iterable, and [I] is the state of an iterator.
/// The [_strategy] operates on the [S] and [I] states to create
/// an iterator state from the iterable state, to move the iterator
/// state, or create a "current" value from the iterator state.
///
/// Can be used to, for example, iterate a record of iterables,
/// using a record of iterators as the iterator.
class _ComputedIterable<T, S, I extends Object> extends Iterable<T> {
  final _IterationStrategy<T, S, I> _strategy;
  final S _iterableState;

  factory _ComputedIterable(
          _IterationStrategy<T, S, I> strategy, S iterableState) =>
      _ComputedIterable._(strategy, iterableState);

  _ComputedIterable._(this._strategy, this._iterableState);

  Iterator<T> get iterator =>
      _ComputedIterator<T, I>(_strategy, _strategy.iterator(_iterableState));

  // A few simple and direct operations implemented inline to avoid allocating
  // an iterator.

  int get length {
    int length = 0;
    I iterators = _strategy.iterator(_iterableState);
    while (true) {
      I? nextIterators = _strategy.moveNext(iterators);
      if (nextIterators == null) return length;
      length++;
      iterators = nextIterators;
    }
  }

  bool get isEmpty => throw UnimplementedError("Not used");
  bool get isNotEmpty => throw UnimplementedError("Not used");
  T get first => throw UnimplementedError("Not used");
  T get single => throw UnimplementedError("Not used");
  T elementAt(int index) => throw UnimplementedError("Not used");
}

/// Computed iterator, generated by [_ComputedIterable].
///
/// Contains an abstract iteration state, which is updated and
/// interpreted using the [_strategy] object.
class _ComputedIterator<T, I extends Object> implements Iterator<T> {
  final _IterationStrategy<T, Object?, I> _strategy;
  I? _iteratorState;
  _ComputedIterator(this._strategy, this._iteratorState);

  bool moveNext() {
    var iteratorState = _iteratorState;
    return iteratorState != null &&
        (_iteratorState = _strategy.moveNext(iteratorState)) != null;
  }

  T get current {
    var iteratorState = _iteratorState;
    if (iteratorState != null) {
      return _strategy.current(iteratorState);
    }
    throw StateError("No element");
    ;
  }
}

/// Strategy for iterating a [_ComputedIterable] and [_ComputedIterator].
///
/// A [_ComputedIterable] represents iterable and iterator state as
/// the [S] and [I] types, wrapping that state in an [Iterable] and
/// [Iterator] which uses this strategy to update the state and
/// create iterator state from iterable state, and values from iterator state.
abstract class _IterationStrategy<T, S, I extends Object> {
  /// Creates iterator state from iterable state.
  I iterator(S iterable);

  /// Moves iterator state if possible.
  ///
  /// Returns `null` if it cannot move, and the iterator state if it can.
  /// This state may be the same state that has been mutated, or a new state.
  /// (The `null` value can be seen as the state of a terminated iteration.)
  I? moveNext(I iterator);

  /// Reads current values from the iterator state.
  T current(I iterator);
}
```

**Comment by biggs0125** [comment]
Fix landed. 

The issue was we didn't update the inferred receiver type for invocations on `Record` interfaces. This caused us to think we didn't need to use an interceptor for `iterables.$2.iterator`. The inference results were missing that the `iterables.$2` might be a `JSArray`.
