### ISSUE TITLE
Create an issue

### ISSUE THREAD

**Issue by ekuleshov** [dart-lang/sdk#56787]
Using the following snippet of code and assuming no file "aaa" is available:

```
Future<void> main() async {
  var file = File('aaa');
  Stream<List<int>> data = file.openRead();
  await data.listen((value) {}).asFuture();
}
```

It throws an exception with the following stacktrace

```
Unhandled exception:
PathNotFoundException: Cannot open file, path = 'aaa' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
<asynchronous suspension>
#2      _FileStream._start.onOpenFile (dart:io/file_impl.dart:153:5)
<asynchronous suspension>
```

As you can see, the stacktrace does not have the source pointer, i.e. the above File.openRead() call in the main() method. The same issue with `File.openWrite()` call.

This is similar to another async io stackterace issue as noted in https://github.com/dart-lang/sdk/issues/56431#issuecomment-2374041769

The above exceptions are from macos, but I've been getting similar errors from the user devices running iOS and Android and it is making it hard to track these issues back to the source code.

- Dart SDK version: 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "macos_arm64"

**Comment by a-siva** [comment]
//cc @brianquinlan I guess something similar to  #56431 has to be done here.
