### ISSUE TITLE
[gardening][vm] lib/mirrors/library_imports_prefixed_test failing

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#56827]
```
--- Command "vm" (took 02.000925s):
DART_CONFIGURATION=ReleaseTSANX64 out/ReleaseTSANX64/dart --sound-null-safety -Dtest_runner.configuration=vm-tsan-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/lib/mirrors/library_imports_prefixed_test.dart

exit code:
255

stderr:
Unhandled exception:
Expect.setEquals() fails
Missing expected elements: LibraryMirror on 'dart.core' 
#0      Expect._fail (package:expect/expect.dart:881:5)
#1      Expect.setEquals (package:expect/expect.dart:629:5)
#2      test (file:///b/s/w/ir/tests/lib/mirrors/library_imports_prefixed_test.dart:19:10)
#3      main (file:///b/s/w/ir/tests/lib/mirrors/library_imports_prefixed_test.dart:30:3)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n vm-tsan-linux-release-x64 lib/mirrors/library_imports_prefixed_test
```

Has been flipping from failing to flaky back to failing: https://dart-ci.web.app/#showLatestFailures=false&test=lib/mirrors/library_imports_prefixed_test&configurations=vm-tsan-linux-release-x64

This test is failing on all VM configurations: https://dart-current-results.web.app/#/filter=lib/mirrors/library_imports_prefixed_test&showAll

Low prio, as mirrors is not really supported.

**Comment by a-siva** [comment]
Since mirrors is not really supported this issue may never get fixed.
