### ISSUE TITLE
[analyzer] Non-null assertion error in AstRewriter

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#56833]
I'm not sure what code was being analyzed when this was triggered, but I was working in the SDK and this came from the analysis server.

SDK commit: https://github.com/dart-lang/sdk/commit/7bb6899a2c493b7946ce7ac6290c43050e6068b1

```
Internal error: Null check operator used on a null value
#0      AstRewriter._toMethodInvocationOfAliasedTypeLiteral (package:analyzer/src/dart/resolver/ast_rewrite.dart:651:44)
#1      AstRewriter.instanceCreationExpression (package:analyzer/src/dart/resolver/ast_rewrite.dart:57:16)
#2      ResolutionVisitor.visitInstanceCreationExpression (package:analyzer/src/dart/resolver/resolution_visitor.dart:955:32)
#3      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:10514:15)
#4      AstResolver.resolveExpression (package:analyzer/src/summary2/ast_resolver.dart:109:10)
#5      _PropertyInducingElementTypeInference.perform (package:analyzer/src/summary2/top_level_inference.dart:263:17)
#6      PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:8979:28)
#7      _InitializerInference.perform (package:analyzer/src/summary2/top_level_inference.dart:153:15)
#8      TopLevelInference.infer (package:analyzer/src/summary2/top_level_inference.dart:106:26)
#9      Linker._performTopLevelInference (package:analyzer/src/summary2/link.dart:424:29)
#10     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:268:5)
<asynchronous suspension>
#11     Linker.link.<anonymous closure> (package:analyzer/src/summary2/link.dart:123:7)
<asynchronous suspension>
#12     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#13     Linker.link (package:analyzer/src/summary2/link.dart:122:5)
<asynchronous suspension>
#14     link (package:analyzer/src/summary2/link.dart:41:3)
<asynchronous suspension>
#15     LibraryContext.load.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:197:22)
<asynchronous suspension>
#16     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#17     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:194:24)
<asynchronous suspension>
#18     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:282:7)
<asynchronous suspension>
#19     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#20     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:273:5)
<asynchronous suspension>
#21     AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1967:5)
<asynchronous suspension>
#22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1252:7)
<asynchronous suspension>
#23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2446:7)
<asynchronous suspension>
```

```
#0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:411:5)
#1      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:208:11)
<asynchronous suspension>
#2      LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:282:7)
<asynchronous suspension>
#3      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#4      LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:273:5)
<asynchronous suspension>
#5      AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1967:5)
<asynchronous suspension>
#6      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1252:7)
<asynchronous suspension>
#7      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2446:7)
<asynchronous suspension>
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by parlough** [comment]
I just hit this again but can't reproduce it. It might be related to analyzing augmentations tests?

**Comment by osa1** [comment]
I get this error all the time when working on SDK. I tried to find out when exactly this happens, *I think* it may be happening because of another LSP call that fails with `UnimplementedError`, which maybe leaving the language server in an inconsistent state.

I see this first:

```
An error occurred while handling textDocument/codeAction request: UnimplementedError
#0      ElementImpl2.enclosingElement2 (package:analyzer/src/dart/element/element.dart:3106:38)
#1      _ReferenceFinder.visitMethodInvocation (package:analysis_server/src/services/correction/dart/import_add_show.dart:95:56)
#2      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:12246:50)
#3      ConditionalExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3870:16)
#4      RecursiveAstVisitor.visitConditionalExpression (package:analyzer/dart/ast/visitor.dart:967:10)
#5      ConditionalExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:3861:15)
#6      VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:18577:19)
#7      RecursiveAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1806:10)
#8      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:18572:50)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:13009:20)
#10     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:18701:16)
...
```

then this after browsing for a while:

```
stderr: [Null check operator used on a null value
stderr: #0      AstRewriter._toMethodInvocationOfAliasedTypeLiteral (package:analyzer/src/dart/resolver/ast_rewrite.dart:651:44)
stderr: #1      AstRewriter.instanceCreationExpression (package:analyzer/src/dart/resolver/ast_rewrite.dart:57:16)
stderr: #2      ResolutionVisitor.visitInstanceCreationExpression (package:analyzer/src/dart/resolver/resolution_visitor.dart:956:32)
stderr: #3      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:10507:15)
stderr: #4      AstResolver.resolveExpression (package:analyzer/src/summary2/ast_resolver.dart:109:10)
stderr: #5      _PropertyInducingElementTypeInference.perform (package:analyzer/src/summary2/top_level_inference.dart:263:17)
stderr: #6      PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:9133:28)
stderr: #7      _InitializerInference.perform (package:analyzer/src/summary2/top_level_inference.dart:153:15)
stderr: #8      TopLevelInference.infer (package:analyzer/src/summary2/top_level_inference.dart:106:26)
stderr: #9      Linker._performTopLevelInference (package:analyzer/src/summary2/link.dart:424:29)
stderr: #10     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:268:5)
```

After the first error the language server is able to serve some requests for a while, but then it fails with the second error and dies.

**Comment by osa1** [comment]
I get this crash all the time when working on SDK, using the language server in SDK version 3.6.1, but if I build the analyzer from source using the current main branch it works much better. So far I'm unable to reproduce this crash. So this may be fixed in the main branch.

Note: it helps with number of warnings/errors generated if you add this `analysis_options.yaml` to your SDK root:

```
analyzer:
  exclude:
    - out/
    - benchmarks/
    - benchmarks-internal/
    - runtime/
    - sdk/
    - tests/
    - third_party/
    - utils/
    - samples/
```

The most important parts are `samples/` and `tests/`.

Also note: file extension needs to be `.yaml`, if you add it as `.yml` the language server won't use it.

**Comment by parlough** [comment]
Closing as this case can no longer be hit.

It seems like it previously occurred when an enum constant resolved to a function type alias with the same name that was declared first.
