### ISSUE TITLE
language/macros test failures

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#56901]
The tests
```
language/macros/augment/class_definition_macro_test Crash (expected Pass)
language/macros/augment/class_types_macro_test Crash (expected Pass)
language/macros/introspect/class_test Crash (expected Pass)
language/macros/introspect/declaration_introspect_cycle_failure_test Crash (expected Pass)
language/macros/json/json_serializable_test Crash (expected Pass)
language/macros/nesting/macro_impl_uses_macro1_test Crash (expected Pass)
language/macros/nesting/macro_impl_uses_macro2_test Crash (expected Pass)
```
are failing on configurations
```
dart2wasm-linux-jscm-chrome
```

**Comment by osa1** [comment]
It looks like language/macros tests fail on all dart2wasm platforms except jsc: https://dart-current-results.web.app/#/filter=dart2wasm,language/macros

Looking at the failure, they don't look like dart2wasm bugs. Example https://dart-ci.appspot.com/log/any/dart2wasm-linux-d8/2978/language/macros/augment/class_definition_macro_test:

```
Unhandled exception:
UnexpectedMacroException: stderr output by macro process: Failed to start the Dart CLI isolate. Could not resolve DartDev snapshot or kernel.

#0      _SingleProcessMacroExecutor.startWithSocket.<anonymous closure> (package:_macros/src/executor/process_executor.dart:74)
#1      _rootRunUnary (dart:async/zone.dart:1422)
#2      _CustomZone.runUnary (dart:async/zone.dart:1324)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63)
#7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:13)
#8      _StringAdapterSink.add (dart:convert/string_conversion.dart:228)
#9      _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233)
#10     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307)
#11     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300)
#12     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69)
#13     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111)
#14     _rootRunUnary (dart:async/zone.dart:1422)
#15     _CustomZone.runUnary (dart:async/zone.dart:1324)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:777)
#20     _StreamController._add (dart:async/stream_controller.dart:651)
#21     _StreamController.add (dart:async/stream_controller.dart:606)
#22     _Socket._onData (dart:io-patch/socket_patch.dart:2455)
#23     _rootRunUnary (dart:async/zone.dart:1430)
#24     _CustomZone.runUnary (dart:async/zone.dart:1324)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#28     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:777)
#29     _StreamController._add (dart:async/stream_controller.dart:651)
#30     _StreamController.add (dart:async/stream_controller.dart:606)
#31     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1942)
#32     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1385)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118)
#36     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185)
```

I don't understand how can these tests pass in jsc, but regardless, this doesn't look like a dart2wasm-related issue.
