### ISSUE TITLE
Out of Memory error in CI pipeline

### ISSUE THREAD

**Issue by garrettApproachableGeek** [dart-lang/sdk#56934]
Within our CI pipeline we are getting an Out of Memory error. Sometimes this occurs when running `flutter analyze` and other times when running `flutter test test/widget_tests.dart`. The VM is being run with 7 CPU and 7000 MB of memory using [tart](https://github.com/cirruslabs/tart/). Let me know what other information I can gather and provide to help identify the source of this issue.

Here is the output from a failed run:
```
Running widget tests
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
evacuation failed
Exhausted heap space, trying to allocate 2135008 bytes.
Crash when compiling file:///Users/admin/fvm/versions/3.24.1/bin/cache/flutter_tools.snapshot:
Out of Memory

#0      _StringBase._concatRangeNative (dart:core-patch/string_patch.dart:982:78)
#1      _JsonStringStringifier.stringify (dart:convert/json.dart:968:19)
#2      FormattedMessage.toJsonString (package:_fe_analyzer_shared/src/messages/codes.dart:[272](https://github.com/Approachable-Geek/abc/actions/runs/11420077419/job/31848879675#step:5:273):20)
#3      SourceLibraryBuilder.addProblem (package:front_end/src/source/source_library_builder.dart:4471:52)
#4      SourceLoader.tokenize (package:front_end/src/source/source_loader.dart:1030:25)
#5      _rootRunUnary (dart:async/zone.dart:1407:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:163:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:861:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:890:13)
#10     Future._completeWithValue (dart:async/future_impl.dart:666:5)
#11     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:736:7)
#12     _rootRun (dart:async/zone.dart:1399:13)
#13     _CustomZone.run (dart:async/zone.dart:1301:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#20     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

* Dart version and tooling diagnostic info (`dart info`)
```
#### General info

- Dart 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "macos_arm64"
- on macos / Version 14.4.1 (Build 23E224)
- locale is en-US

#### Project info

- sdk constraint: '>=3.2.4 <4.0.0'
- dependencies: cached_network_image, cloud_firestore, cloud_functions, collection, faker, file_picker, firebase_auth, firebase_core, firebase_messaging, firebase_storage, firebase_storage_mocks, flutter, flutter_dropzone, flutter_svg, http, image_picker, intl, ioc_container, jiffy, json_annotation, localstorage, mocktail, path, pdf, printing, provider, screenshot, squadron, squadron_builder, stack_trace, state_view, tuple, universal_html, url_launcher, uuid, web
- dev_dependencies: build_runner, dependency_validator, fake_cloud_firestore, firebase_auth_mocks, flutter_launcher_icons, flutter_test, integration_test, json_serializable, lints, mock_exceptions, network_image_mock
- elided dependencies: 1

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                               |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|  30 MB | 0.0% |        08:09 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/P1ygb6lrLmYsbg6u --port 9100 |
| 191 MB | 0.0% |        08:09 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.98.1            |
|  30 MB | 0.0% |        08:09 | dart tooling-daemon --machine                                                              |
|  63 MB | 0.7% |        08:09 | flutter_tools.snapshot daemon                                                              |
```
* Whether you are using Windows, macOS, or Linux (if applicable)
macoOS / Version 14.4.1 (Build 23E224)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Analyzer and running widget tests

**Comment by a-siva** [comment]
Do you know which 'dart' process out of the three that you have listed above had the OOM error ?

**Comment by garrettApproachableGeek** [comment]
Not exactly sure what you mean by dart process (maybe flutter_tools.snapshot test test/widget_tests.dart) Activity Monitor shows `dart:flutter_tools.snapshot` using 30+ GB
<img width="1137" alt="dart-flutter_tools_snapshot" src="https://github.com/user-attachments/assets/9555c548-5ef6-4f19-a98d-2faef8bb74fb">

**Comment by a-siva** [comment]
Looks like you have changed the issue description, in the original submission you had three Dart processes running and I was asking which of them crashed with the OOM.

From your updated description it is clear the flutter tools process which is running the test has crashed.

```
| Memory |  CPU | Elapsed time | Command line                                                                               |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|  30 MB | 0.0% |        08:09 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/P1ygb6lrLmYsbg6u --port 9100 |
| 191 MB | 0.0% |        08:09 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.98.1            |
|  30 MB | 0.0% |        08:09 | dart tooling-daemon --machine                                                              |
|  63 MB | 0.7% |        08:09 | flutter_tools.snapshot daemon  
```

Is this a regression you are seeing with Dart 3.5.3, i.e the same test was working fine with an older version of Dart ?

**Comment by mraleph** [comment]
It is a manifestation of the same old problem - `dart` seems to be trying to parse `flutter_tools.snapshot` as a Dart file. Notice this line:

```
Crash when compiling file:///Users/admin/fvm/versions/3.24.3/bin/cache/flutter_tools.snapshot:
```

Maybe `.snapshot` does not have correct magic and we instead pass it to the CFE as if it was a Dart file?

I suggest we make a breaking change and stop doing that to files which don't end with `.dart` extension.

**Comment by lrhn** [comment]
Not accepting non-`.dart` files could break scripts using `#! dart`.
We could check if the file starts with `#!` and give it a shot then.

I don't know why the parsing of the `.snapshot` takes so much memory. If it's because it keeps trying to parse random garbage as Dart, and recovering and recovering ... maybe we could have some small sanity check before trying to parse a big file. Or just a quicker bail-out from the tokenizer, if it sees too much noise, and too little signal. If the first 100 tokens are not a `#!`-line, Dart comments, string literals or valid Dart tokens, maybe just bail out and say "probably not Dart".

Compilers don't need to be quite as forgiving as the analyzer. They could stop at the first input that doesn't tokenize, and say "Not Dart!".

**Comment by a-siva** [comment]
//cc @johnniwinther is something like what @lrhn suggests above doable?

**Comment by a-siva** [comment]
There is also a possibility that we might have a race in the generation of the snapshot resulting in a corrupted snapshot.

**Comment by johnniwinther** [comment]
cc @jensjoha

**Comment by garrettApproachableGeek** [comment]
With something like this patched into dart we aren't seeing the issue with memory usage or parsing the flutter.snapshot, but this may be overly aggressive in skipping compilation or fully approached in the wrong way. Hopeful, this helps in someway.

Patched in before: https://github.com/dart-lang/sdk/blob/72644e4ec15ffb4fc11a9fbfdc602a6aec9f3661/pkg/front_end/lib/src/source/source_loader.dart#L1033
```
// Skip parsing and tokenization of files that don't end in .dart or have #! dart in the first line
if (!fileUri.path.endsWith('.dart') && bytes != null) {
  if (bytes.length >= 2 && bytes[0] == 0x23 && bytes[1] == 0x21) {
      String shebangLine = utf8.decode(bytes.sublist(0, bytes.indexOf(0x0A)));
      if(!shebangLine.contains('dart')) {
        return new Token.eof(-1);
      }
  } else {
    return new Token.eof(-1);
  }
}
```

**Comment by a-siva** [comment]
@garrettApproachableGeek do we know why the snapshot that is generated in your CI appears to be corrupted (magic number is missing) ? The Dart VM code checks for magic number and only when it doesn't recognize it we pass it on to the front end for compilation.

**Comment by garrettApproachableGeek** [comment]
I do not know why it would act differently, it isn't doing anything special other than using MacOS VM using Tart and standard FVM managed Flutter/Dart. Do you know what the magic number should be, or where this is set and checked?

**Comment by vikasgola** [comment]
facing similar issue.
```E/flutter (10164): #1      StringBuffer._compact (dart:core-patch/string_buffer_patch.dart:191:38)
E/flutter (10164): #2      StringBuffer._addPart (dart:core-patch/string_buffer_patch.dart:179:9)
E/flutter (10164): #3      StringBuffer.write (dart:core-patch/string_buffer_patch.dart:73:5)
E/flutter (10164): #4      ContentLexer._consumeValue (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/parser/content_lexer.dart:179:21)
E/flutter (10164): #5      ContentLexer._getLiteralString (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/parser/content_lexer.dart:221:14)
E/flutter (10164): #6      ContentLexer.getNextToken (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/parser/content_lexer.dart:43:16)
E/flutter (10164): #7      ContentParser._parseObject (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/parser/content_parser.dart:119:22)
E/flutter (10164): #8      ContentParser.readContent (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/parser/content_parser.dart:108:5)
E/flutter (10164): #9      XObjectElement.renderTextElement (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/xobject_element.dart:89:55)
E/flutter (10164): #10     ImageRenderer._getXObject (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/image_renderer.dart:602:60)
E/flutter (10164): #11     ImageRenderer.renderAsImage (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/image_renderer.dart:456:15)
E/flutter (10164): #12     PdfTextExtractor._getTextLine (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:346:14)
E/flutter (10164): #13     PdfTextExtractor._extractTextLineFromRange (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:262:40)
E/flutter (10164): #14     PdfTextExtractor._extractTextLines (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:207:16)
E/flutter (10164): #15     PdfTextExtractor.extractTextLines (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:131:12)```

**Comment by mraleph** [comment]
@vikasgola it is not the same issue. Your app is just running out of memory.
