### ISSUE TITLE
The `>` symbol causes Process to report an error: Missing extension byte (at offset 5)

### ISSUE THREAD

**Issue by ismanong** [dart-lang/sdk#56938]
• Flutter version 3.24.3 on channel stable at D:\_sdk\flutter
• Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
• Engine revision 36335019a8
• Dart version 3.5.3
• DevTools version 2.37.3

• Platform Windwos 10 22H2(19045.5011)

Use:
```dart
Process process = await Process.start(
  'Powershell.exe',
  ['-command',  'git commit -m "[DBG-30] Auto push => $lastVersion"'],
  runInShell: true,
);
process.stdout.transform(utf8.decoder).forEach(stdout);
process.stderr.transform(utf8.decoder).forEach(stderr);
```

Output:
```test
Unhandled exception:
FormatException: Missing extension byte (at offset 5)
#0 _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1956:7)
#1 _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
#2 _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#3 _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#4 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5 _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#7 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#8 _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#9 _StreamController._add (dart:async/stream_controller.dart:658:7)
#10 _StreamController.add (dart:async/stream_controller.dart:606:5)
#11 _Socket._onData (dart:io-patch/socket_patch.dart:2455:41)
#13 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#14 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#15 _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#16 _StreamController._add (dart:async/stream_controller.dart:658:7)
#17 _StreamController.add (dart:async/stream_controller.dart:606:5)
#18 new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1942:33)
#19 _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1385:14)
#20 _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21 _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
);
```

Discover a possibility:
Found out it was this `>` symbol
Removing this `>`  results in normal output. `(e.g.: "=>" replace ":")`

What is the reason for this, please?

**Comment by mraleph** [comment]
```
FormatException: Missing extension byte (at offset 5)
```

This sort of error occurs when you are trying to decode something as UTF8 but it is not in fact UTF8 encoded. For example, in your code you seem to assume that the process will produce UTF8 output, but Windows quite commonly does not actually use UTF8. Hence the error. I would guess your Windows installation might be actually using CP936 or CP950. 

Now you have another error in your code:

```
['-command',  'git commit -m "[DBG-30] Auto push => $lastVersion"'],
```

This does not actually do what you expect it to do because `>` get interpreted as a _redirection_ rather than part of the string due to bizarre Windows specific escaping rules. I suggest instead:

```
['-command',  'git commit -m \'[DBG-30] Auto push => $lastVersion\''],
```

**Comment by ismanong** [comment]
Thank you, I understood your words and got it.

Windows ran an internal error caused by `>` and the output to stderr was non-utf8.
FormatException: Missing extension byte (at offset 5)
