### ISSUE TITLE
building: When looking for build dpendencies, check pkgconfig and PATH also

### ISSUE THREAD

**Issue by solomoncyj** [dart-lang/sdk#56951]
when compiling the sdk, i repetedlyt came across issues then when running `./tools/build.py  --mode release --arch <arch> create_sdk`
I always get the error that some programs in ./buildtools was not present, but was installed system wide on my system, rady to use already. eg
```
> ./tools/build.py --no-clang --mode release --arch x64 create_sdk
Traceback (most recent call last):
  File "/home/solomoncyj/Downloads/sdk/./tools/build.py", line 325, in <module>
    sys.exit(Main())
             ~~~~^^
  File "/home/solomoncyj/Downloads/sdk/./tools/build.py", line 301, in Main
    gn_py.RunGnOnConfiguredConfigurations(options, env)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/solomoncyj/Downloads/sdk/tools/gn.py", line 673, in RunGnOnConfiguredConfigurations
    BuildGnCommand(args, mode, arch, target_os, sanitizer,
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                   out_dir))
                   ^^^^^^^^
  File "/home/solomoncyj/Downloads/sdk/tools/gn.py", line 642, in BuildGnCommand
    raise Exception("Couldn't find the gn binary at path: " + gn)
Exception: Couldn't find the gn binary at path: /home/solomoncyj/Downloads/sdk/buildtools/gn

> which gn
/usr/bin/gn
```
please make the build script check for tools alreay on the system, and run ln/ just call to thr applicvation exposed to the path

**Comment by solomoncyj** [comment]
> Usually when you get errors like this that means `gclient sync` / `gclient runhooks` had an error.
> 
> I am not sure that just falling back to systemwide tools is the right solution here - it will just hide the issue. Tools might not have compatible versions, etc.

well, for packaging dart in places such as fedora, we are required to use the tools already packaged, thus we need it to be able to use packages packaged in the package manager

**Comment by mraleph** [comment]
I guess the ask to have more graceful fallback hidden under some flag is reasonable. We can take a patch for that.

That being said: you can't really bootstrap Dart SDK without using some amount of prebuilt binaries. Using some prebuilt binaries and some preinstalled binaries is a questionable choice. If you use some - you can just as well use all of them.

**Comment by solomoncyj** [comment]
we will be fully vendoring the build requiremenmrts from our package manager

**Comment by LecrisUT** [comment]
There are projects which are bootstrapped like `cmake` and some `python` libraries as well, and that is fully allowed for base projects. But we would need to look at the build process that it takes and what artifacts are generated during bootstrap and outside of it.
