### ISSUE TITLE
`dart analyze` error with latest Flutter SDK

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#57022]
```
/home/runner/work/devtools/devtools/packages/devtools_app > /home/runner/work/devtools/devtools/tool/flutter-sdk/bin/dart analyze --fatal-infos
Analyzing devtools_app...
An unexpected error was encountered by the Analysis Server.
Please file an issue at https://github.com/dart-lang/sdk/issues/new/choose with the following details:

Internal error: Exception while using a AvoidClassesWithOnlyStaticMembers to visit a ClassDeclarationImpl in CompilationUnitImpl
type 'MethodMember' is not a subtype of type 'ExecutableFragment' in type cast
#0      Interface.map2.<anonymous closure> (package:analyzer/src/dart/element/inheritance_manager3.dart:1265:33)
#1      MapBase.map (dart:collection/maps.dart:82:28)
#2      Interface.map2 (package:analyzer/src/dart/element/inheritance_manager3.dart:1264:16)
#3      _Visitor.visitClassDeclaration (package:linter/src/rules/avoid_classes_with_only_static_members.dart:46:25)
#4      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2882:50)
#5      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:1083:14)
#6      LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:158:5)
#7      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2882:50)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12939:20)
#9      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3553:21)
#10     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:183:10)
#11     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:3546:50)
#12     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:410:12)
#13     LibraryAnalyzer._computeDiagnostics (package:analyzer/src/dart/analysis/library_analyzer.dart:334:7)
#14     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:109:5)
#15     AnalysisDriver._analyzeFileImpl.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1397:11)
<asynchronous suspension>
#16     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#17     AnalysisDriver._analyzeFile.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1311:9)
<asynchronous suspension>
#18     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#19     AnalysisDriver._analyzeFile (package:analyzer/src/dart/analysis/driver.dart:1308:5)
<asynchronous suspension>
#20     AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:2013:5)
<asynchronous suspension>
#21     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1248:7)
<asynchronous suspension>
#22     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2442:7)
<asynchronous suspension>
```

First noticed on this PR https://github.com/flutter/devtools/pull/8504, which upgrades the version of Flutter that DevTools is built with to `55c026a2304d9e0d8acc9f3843ee5900fabf96b4`.

Repro steps:
1. Checkout Flutter @ 55c026a2304d9e0d8acc9f3843ee5900fabf96b4
2. From the `devtools/packages/devtools_app` directory, run `dart analyze .` (provided that which dart points to the Dart from the Flutter SDK you just checked out flutter/bin/dart).

This may reproduce on other Dart or Flutter projects, but the DevTools repo has a consistent repro.

**Comment by pq** [comment]
Thanks for reporting this @kenzieschmoll!
