### ISSUE TITLE
Error when running the `tools/rev_sdk_deps.dart` script

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#57050]
```
 ~/develop/dart-lang/sdk/ [remotes/origin/HEAD] dart tools/rev_sdk_deps.dart
41 package dependencies found.
Not attempting to move forward the revisions for: dart_style, leak_tracker, native, pub.

Unhandled exception:
ProcessException: No such file or directory
  Command: git fetch
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:579:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      exec (file:///Users/kenzieschmoll/develop/dart-lang/sdk/tools/rev_sdk_deps.dart:333:30)
#5      GitHelper.fetch (file:///Users/kenzieschmoll/develop/dart-lang/sdk/tools/rev_sdk_deps.dart:170:12)
#6      main.<anonymous closure>.<anonymous closure> (file:///Users/kenzieschmoll/develop/dart-lang/sdk/tools/rev_sdk_deps.dart:53:21)
#7      Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:520:21)
<asynchronous suspension>
#9      main (file:///Users/kenzieschmoll/develop/dart-lang/sdk/tools/rev_sdk_deps.dart:49:6)
<asynchronous suspension>
```

**Comment by devoncarew** [comment]
Hmm, for some reason the script is not able to shell out to `git`.

**Comment by devoncarew** [comment]
For bumping an individual dep, you can also run `dart tools/manage_deps.dart bump third_party/pkg/tools`.
