### ISSUE TITLE
Dart Analysis Server server crashed on generics refactor

### ISSUE THREAD

**Issue by Solido** [dart-lang/sdk#57058]
* Dart analyzer and linter

Flutter master.

I’m working on a project that structure around a core class:

`sealed class Operation<T, C, R>`
Everything was working well but I found a solution to simplify to `<T, R>`

The moment I started the refactor I got this log analyze crashed living
whole source no more traversable.

```
Restarting the server crash it after 5 tentatives.
[19:45:28] [Analyzer] [Error] [Bad state: Empty path: []
#0      InterfaceLeastUpperBoundHelper._computeTypeAtMaxUniqueDepth (package:analyzer/src/dart/element/least_upper_bound.dart:314:5)
#1      InterfaceLeastUpperBoundHelper._computeLeastUpperBound (package:analyzer/src/dart/element/least_upper_bound.dart:176:12)
#2      InterfaceLeastUpperBoundHelper.compute (package:analyzer/src/dart/element/least_upper_bound.dart:103:18)
#3      LeastUpperBoundHelper.getLeastUpperBound (package:analyzer/src/dart/element/least_upper_bo…

```

Current status is I've been able to complete the refactor by hand, grep and memory 
so I'm not sure what was triggering this crash as the code base is as deep as wide.

The main culprit seems around a **Mixin without generics (dynamic) on Operation<T, C, R>**
A warning was thrown before crash that sub classes cannot implement both the typed and generic methods.

I'm sorry I can not pinpoint more precisely the root cause to reproduce it.

Some more not much actionnables hints but maybe helpful:

I was able to start the conversion starting by the leaf-classes and then trying to go up
in the hierarchy. Changing the root class generic, removing C, was my last operation to have it
work.

Starting the refactor by the root class nearly instantly kill the analyzer.

Dear analyzer team, you have all my gratitude for this tool.
I've never felt so alone with my own code than when he's not supporting me anymore... ;)

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Noted, but I was not able to reproduce it.
