### ISSUE TITLE
Response has unsupport header throw exception: Failed to parse header value.message

### ISSUE THREAD

**Issue by Nondirectional** [dart-lang/sdk#57117]
**Question:**

![image](https://github.com/user-attachments/assets/0d0388e4-1c63-4e41-9261-63a1a20238b4)

For this request, I can get the response header and status code information when using JavaScript.

However, when using http to send the request and parse the response, an exception is thrown, and I cannot get any information including the status code and response header except an error message.

**Reproducible example:** 

```dart
void main() async {
  final client = HttpClient();
  final request = await client.postUrl(
    Uri.parse('http://memos.w-wbr.space/api/v1/auth/status'),
  );
  final response = await request.close();
  print(response);
}
```

**Comment by mraleph** [comment]
The exception is thrown because `user not found` is not a valid value for `WWW-Authenticate` header, see [RFC 7235 Appendix C](https://datatracker.ietf.org/doc/html/rfc7235#appendix-C) for the correct format. 

I am not sure if we should be more lax when parsing the header though. 

cc @brianquinlan

**Comment by lrhn** [comment]
It's a question of what to do.
If it doesn't throw, then either
- The resulting header has an invalid value, or
- The resulting header has no entry even if the header sent by the server had *something*.

I guess the latter is better, but it still feels like dropping an error on the floor.

**Comment by brianquinlan** [comment]
The traceback looks like:

```
Unhandled exception:
HttpException: Failed to parse header value
#0      _HeaderValue._parse.expect (dart:_http/http_headers.dart:793:9)
#1      _HeaderValue._parse.parseParameters (dart:_http/http_headers.dart:873:9)
#2      _HeaderValue._parse (dart:_http/http_headers.dart:883:5)
#3      _HeaderValue.parse (dart:_http/http_headers.dart:703:12)
#4      _HttpClientResponse._authenticate (dart:_http/http_impl.dart:816:22)
#5      _HttpClientRequest._onIncoming (dart:_http/http_impl.dart:1504:25)
#6      _HttpClientConnection.send.<anonymous closure>.<anonymous closure> (dart:_http/http_impl.dart:2239:17)
<asynchronous suspension>
#7      _HttpClientConnection.send.<anonymous closure>.<anonymous closure> (dart:_http/http_impl.dart:2246:16)
<asynchronous suspension>
```

Maybe it would be enough to display the name of the header that we cannot parse? I wouldn't want to log the value because I'd worry that header values would end up in logs.

**Comment by brianquinlan** [comment]
> It's a question of what to do. If it doesn't throw, then either
> 
> * The resulting header has an invalid value, or
> * The resulting header has no entry even if the header sent by the server had _something_.
> 
> I guess the latter is better, but it still feels like dropping an error on the floor.

There is also the complication that the user gets to provide an [`authenticate`](https://api.dart.dev/dart-io/HttpClient/authenticate.html) function to handle server authentication requests. What would we provide as arguments if the header cannot be parsed?

I have a PR out that just changes the exception to "The authentication challenge sent by the server is not correctly formatted.":  https://dart-review.googlesource.com/c/sdk/+/402280/2/sdk/lib/_http/http_impl.dart

**Comment by PaulAllanSturm** [comment]
If the server returns a www-authenticate header with an unknown scheme, such as `WWW-Authenticate: NotBasicOrDigest`, no exception is thrown and no authentication happens. I think it would be better if a malformed header was treated the same as an unknown scheme with no arguments. Throwing an exception leaves the client code with no options to recover or provide its own handling.
