### ISSUE TITLE
CFE parser crash if run a script before "pub get"

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#59656]
It took me a little while to figure out, I guess before I "pub get" the language version is not available and that's why parsing fails? After "pub get" on the script package it works fine.

I think the crash is related to the use of records `for (var (:user, :repo) in repoPaths) {`.

The input script is this file:

https://github.com/dart-lang/language/pull/4193/files#diff-c5eb08ca5afe75c28c6ca230d436d3dc8d394055b0cfa412accb93d6e472f989

```
dart ~/git/language/tools/corpus/scripts/bin/clone_flutter_apps.dart
Crash when compiling file:///usr/local/google/home/davidmorgan/git/language/tools/corpus/scripts/bin/clone_flutter_apps.dart at character offset 687:
type 'ParserRecovery' is not a subtype of type 'Expression' in type cast

#0      BodyBuilder._computeForInElements (package:front_end/src/kernel/body_builder.dart:7779:34)
#1      BodyBuilder.endForIn (package:front_end/src/kernel/body_builder.dart:7837:9)
#2      Parser.parseForInRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8643:14)
#3      Parser.parseForStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8474:14)
#4      Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5672:14)
#5      Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5631:20)
#6      Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5536:15)
#7      DietListener.buildFunctionBody (package:front_end/src/source/diet_listener.dart:1281:14)
#8      DietListener.endTopLevelMethod (package:front_end/src/source/diet_listener.dart:389:7)
#9      Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3942:14)
#10     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3674:14)
#11     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:618:14)
#12     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:411:15)
#13     SourceLoader.buildBody (package:front_end/src/source/source_loader.dart:1296:12)
```

**Comment by jensjoha** [comment]
Sort of. Reproduction:

```dart
// @dart=2.12
void main() {
  var repoPaths = [(user: "a", repo: "b")];
  for (var (:user, :repo) in repoPaths)  {
    print(user);
    print(repo);
  }
}
```

I can't personally reproduce it without making the language version below 3.0. Normally, if no language version is specified, it will be the newest language version. I guess in this case you may have had done `pub get` or whatnot earlier so the language version was somehow specified to be below 3.0.

I'll try to fix it.

**Comment by davidmorgan** [comment]
Thanks!

That makes sense. Or maybe there was an old pubspec in some enclosing folder, I think it was a new folder so probably I hadn't already run pub get in it :)
