### ISSUE TITLE
Usage highlighting broken in VSCode

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#59695]
I recently re-built my SDK, and I'm no longer seeing usages highlighted when clicking on an identifier in VSCode.

I've bisected the issue and it appears to have started with 6f992aea0d548aed4f06a8da2c05e6893b7b5f79.

CC @bwilkerson @scheglov

**Comment by scheglov** [comment]
@DanTup What LSP command / handler does VS Code use to highlight usages?

@stereotype441 is it broken for all kinds of elements, e.g. local variables, classes, getters, etc?

**Comment by DanTup** [comment]
> @DanTup What LSP command / handler does VS Code use to highlight usages?

LSP calls these "Document Highlights" and the implementation uses `OccurrencesCollectorImpl` (which should match the legacy implementation).


In a quick test of class names (running from source as of around 4 hours ago) I do still see them showing up:

![image](https://github.com/user-attachments/assets/f24dc994-9111-41d2-8ffb-575672975680)

**Comment by stereotype441** [comment]
Hmm, I thought it was broken for everything, but now I can't reproduce the problem at all. I'm not sure what happened.

I will keep an eye out, and if it happens again, I'll post more exact repro instructions.

**Comment by stereotype441** [comment]
Ok, I have more information. The problem seems to happen only in certain files. For example, in my checkout of the Dart SDK, document highlights work in `pkg/analyzer/lib/dart/analysis/analysis_context_collection.dart`, but not in `pkg/analyzer/lib/src/dart/analysis/analysis_context_collection.dart`.

I played around a bit in `pkg/analyzer/lib/src/dart/analysis/analysis_context_collection.dart`, and found that if I modify the `AnalysisContextCollectionImpl` constructor so that its `updateAnalysisOptions2` argument has type `void Function()?` instead of `void Function({required AnalysisOptionsImpl analysisOptions, required ContextRoot contextRoot, required DartSdk sdk})?`, then highlights begin to work throughout the file.

Does that help?

**Comment by bwilkerson** [comment]
I don't see anything obviously wrong with the AST structure created for that constructor. My best guess at this point is that the code might be throwing an exception that's being caught in such a way that it's returning an empty list of references.

**Comment by DanTup** [comment]
@stereotype441 do you have an exact git hash and example offset where it's not working? I'm browsing the source at 8a28378458a and running the server from `Dart SDK version: 3.7.0-edge.0c527e1b9f187c823263d19f9a3c2df8a76ccc22 (main) (Tue Dec 10 04:36:59 2024 +0000) on "windows_x64"` but it does seem to work in the noted file for me:

![image](https://github.com/user-attachments/assets/18bbcf8a-b5a8-4e4c-a559-e65dcbac16ed)

**Comment by DanTup** [comment]
An issue came up at https://github.com/Dart-Code/Dart-Code/issues/5369 that may or may not be related. In this case, we're throwing exceptions, and that causes VS Code to fall back to doing a text search for highlights.

The exceptions are like:

```
Unsupported operation: This is not a fragment,
#0      FunctionElementImpl.enclosingFragment (package:analyzer/src/dart/element/element.dart:5057:5)
#1      FragmentExtension.withAncestors (package:analysis_server/src/utilities/extensions/element.dart:81:31)
#2      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:595:13)
#3      _getUnitElement (package:analysis_server/src/protocol_server.dart:443:49)
#4      newLocation_fromElement (package:analysis_server/src/protocol_server.dart:306:21)
#5      convertElement (package:analysis_server/plugin/protocol/protocol_dart.dart:35:15)
#6      addDartOccurrences.<anonymous closure> (package:analysis_server/src/domains/analysis/occurrences_dart.dart:18:34)
#7      _LinkedHashMapMixin.forEach (dart:_compact_hash:756:13)
#8      addDartOccurrences (package:analysis_server/src/domains/analysis/occurrences_dart.dart:16:27)
```

And in the case I'm seeing, it's caused by code like this (the function passed to `mapResultsSync` is where it throws):

```dart
class CompletionHandler {

  @override
  Future<ErrorOr<CompletionList>> handle(
    CompletionParams params,
    MessageInfo message,
    CancellationToken token,
  ) async {
  // ...

    var offset = lineInfo.mapResultSync((lineInfo) => toOffset(lineInfo, pos));
```

I'll try to reproduce in a test, but I'm not certain if it's the same issue, as from the original description here it sounds like nothing was highlighted, rather than all matching names (I guess it's possible there's a setting for the fallback that maybe @stereotype441 has changed though?).

**Comment by DanTup** [comment]
@stereotype441 have you seen this at all recently? It might be difficult to do anything with this issue without knowing it's still happening (and ideally an exact repro - as a location + commit hash, and SDK build version/hash).

**Comment by stereotype441** [comment]
@DanTup I haven't seen this issue in a long time. I'm sorry we weren't able to root cause it, but I think at this point it's not worth worrying about anymore. I'm going to go ahead and close the issue.

**Comment by DanTup** [comment]
np! If you do see it again (or any other similar LSP weirdness), do let me know :-)
