### ISSUE TITLE
ErrorResult lib path is required

### ISSUE THREAD

**Issue by SandPod** [dart-lang/sdk#59744]
### Observed behavior

When running `dart analyze --fatal-infos` in GitHub actions in a closed source repository, with no info warnings left in the project, the analyzer crashes with the following stack trace:

```bash
ERROR: ERROR: An unexpected error was encountered by the Analysis Server.
Please file an issue at https://github.com/dart-lang/sdk/issues/new/choose with the following details:

ErrorResult lib path is required
#0      new FilePathResourceLocator.fromUri (package:import_lint/src/analyzer/resource_locator.dart:75:7)
#1      DriverBasedAnalysisContextAnalyzer.analyzeFile (package:import_lint/src/analyzer/analyzer.dart:38:61)
<asynchronous suspension>
#2      ImportLintPlugin.analyzeFile (package:import_lint/src/plugin/plugin.dart:36:22)
<asynchronous suspension>
#3      ServerPlugin.analyzeFiles (package:analyzer_plugin/plugin/plugin.dart:119:7)
<asynchronous suspension>
#4      ServerPlugin.afterNewContextCollection.<anonymous closure> (package:analyzer_plugin/plugin/plugin.dart:86:7)
<asynchronous suspension>
#5      ServerPlugin._forAnalysisContexts (package:analyzer_plugin/plugin/plugin.dart:525:7)
<asynchronous suspension>
#6      ServerPlugin.afterNewContextCollection (package:analyzer_plugin/plugin/plugin.dart:84:5)
<asynchronous suspension>
#7      ServerPlugin.handleAnalysisSetContextRoots (package:analyzer_plugin/plugin/plugin.dart:273:5)
<asynchronous suspension>
#8      ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:544:18)
<asynchronous suspension>
#9      ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:611:18)
<asynchronous suspension>
```

### Expected behavior
The analyzer should execute correctly when no info warnings are left in the project.

### Additional context

- This started happening when we upgraded to Dart `3.6.0`.
- This is used in a fairly large project.
- This does not happen when running the same command locally.
- This could be related to: https://github.com/dart-lang/sdk/issues/59560

### Project info
- Dart version: `Dart SDK version: 3.6.0 (stable) (Thu Dec 5 07:46:24 2024 -0800) on "linux_x64"`
- Runs on: `Ubuntu 24.04.1 LTS`

I'll see if I can create a repro of the issue in a public repository.

**Comment by SandPod** [comment]
I have not been able to create a stable repro in an open-source repository.

But we are running the analyzer through `melos`, and if we add `-c 1`  to the command, forcing it to run with concurrency 1, the crashing stops (`melos analyze -c 1 --fatal-infos`).

Our setup is a mono repo where `melos` is used to to manage dependencies and run shared scripts.

**Comment by lrhn** [comment]
The error seems to come from code in the [`import_lint`](https://github.com/kawa1214/import-lint/tree/main) package.
It seems to be doing some file path checking, and complains like this if the file is not inside a directory ending in `lib`. (Probably intended to check that it was a directory named `lib`, but it uses RegExps.)

**Comment by SandPod** [comment]
@lrhn - You are correct; how clumsy of me not to inspect the stack trace more carefully.

This should probably be reported there instead.

Thank you for the clarification! 🙏

**Comment by SandPod** [comment]
Removing `import_lint` resolved the issue.
