### ISSUE TITLE
dart analysis server client couldn't create connection to server

### ISSUE THREAD

**Issue by DjordjeMancic97** [dart-lang/sdk#59743]
- dart analysis server client couldn't create connection to server
- not sure I have steps to reproduce, it was working well until yesterday
- Dart SDK version: 3.5.4 (stable) (Wed Oct 16 16:18:51 2024 +0000) on "macos_arm64"

I have logs [here](https://justpaste.it/ha85j)

**Comment by DanTup** [comment]
Some snippets from the logs:

```
[16:27:53] [Analyzer] [Error] on_weather/weather/weather_sheet.dart), (uri: dart:ui/weather/weather/weather/weather/weather/weather/weather/weather/weather, path: /Users/user/DevTools/flutter/bin/cache/pkg/sky_engine/lib/ui/weather/weather/weather/weather/weather/weather/weather/weather/weather), (uri: dart:ui/weather/weather/weather/weather/weather/weather/weather/weather/r…
[16:27:53] [Analyzer] [Error] er/weather/weather/weather/weather/weather/weather_sheet.dart), (uri: dart:ui/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather, path: /Users/user/DevTools/flutter/bin/cache/pkg/sky_engine/lib/ui/weather/weather/weather/weather/weather/weather/weather/weather/weather/rec…
[16:27:53] [Analyzer] [Error] er/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather_sheet.dart, path: /Users/user/DevTools/flutter/bin/cache/pkg/sky_engine/lib/ui/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather/weather_sheet…
```

and

```
[16:27:53] [Analyzer] [Error] vices/available_declarations.dart:813:5)
#2      _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1888:20)
#3      _File.refresh (package:analyzer/src/services/available_declarations.dart:1344:19)
#4      DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:814:10)
#5      _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1888:20)
#6      _File.refresh (package:analyzer/src/services/ava…
```


@scheglov I feel like we've seen this error come up before, but I'm failing to find any other issues. The stack includes Declarations which I think are gone now, although I'm not sure whether there are other code paths that could call `_File.refresh` in the same way that could still trigger this.

**Comment by DanTup** [comment]
Ah, found another issue:

https://github.com/dart-lang/sdk/issues/51455



> The path keeps growing with the "components" section being repeated:
> 
> uri:: dart::_internal/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/ui_settings_security.dart

Deleting the `C:\Users\USERNAME\AppData\Local\.dartServer\.analysis-driver` folder resolved the issue for that user. @scheglov is there anything else to try (or try to extract from that folder) before testing if deleting it also solves the problem here?

**Comment by DjordjeMancic97** [comment]
> Ah, found another issue:
> 
> #51455
> 
> > The path keeps growing with the "components" section being repeated:
> > uri:: dart::_internal/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/components/ui_settings_security.dart
> 
> Deleting the `C:\Users\USERNAME\AppData\Local\.dartServer\.analysis-driver` folder resolved the issue for that user. @scheglov is there anything else to try (or try to extract from that folder) before testing if deleting it also solves the problem here?

Sadly I already deleted it, and this solved the issue. Although thing to note is that I am on Mac so folder is located at root of my user folder.

Few more things, looks like this path was cached because even after I switched to branch which didn't have the folder mentioned in logs - server still crashed with same error, this continued to happen even after I opened another project.

Ofc root cause should be identified and fixed, but in situation where server keeps failing would it make sense to delete the cached data automatically and assume it is corrupted...

**Comment by scheglov** [comment]
The whole `available_declarations.dart` file was removed.
So, this should not cause issues in the next release.
