### ISSUE TITLE
udp

### ISSUE THREAD

**Issue by ARDUTECH0** [dart-lang/sdk#59818]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 4210
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      UDP.send.<anonymous closure> (package:udp/src/udp_base.dart:120:12)
#3      new Future.microtask.<anonymous closure> (dart:async/future.dart:285:40)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by mraleph** [comment]
Impossible to say what is going on without a way to reproduce the issue. An underlying OS syscall is returning `EHOSTUNREACH`.
